### ISSUE TITLE
BSOD Driver Manual Map [Windows 10 14393]

### ISSUE THREAD

**Issue by x64architecture** [DarthTon/Blackbone#100]
Heres the trace (I can send you the full dump if you want):
https://paste.ubuntu.com/23072373/

Most of the interesting details begin on line 1028.

**Comment by DarthTon** [comment]
It's a known issue with GetPteForVA/Page tables in build 14393.

**Comment by x64architecture** [comment]
Thank you for the quick response and fix.

**Comment by x64architecture** [comment]
Great read for people interested in this (now resolved) issue: [http://www.alex-ionescu.com/?p=323](http://www.alex-ionescu.com/?p=323).
