### ISSUE TITLE
Manual map x64 dll into x64 process crashes

### ISSUE THREAD

**Issue by Kinsageme** [DarthTon/Blackbone#101]
Hi

Trying to manual map a x64 dll into a x64 process. The dll is just an empty dll so shouldn't be causing crashing. Here's the code:

```
    Process injectProc;
    injectProc.Attach(pid);
    if (injectProc.valid())
    {
        //injectProc.modules().Inject(L"Loader.dll");
        eLoadFlags flags = NoFlags;
        injectProc.mmap().MapImage(L"Loader.dll", flags);
    }   
```

Using x64 debugger the exception caused is an Access Violation 0xC0000005, located at ntdll.RtlReleaseActivationContext+0x21.

Interestingly injecting using the "standard" method is fine; no crash. Perhaps I should mention the Injection/mapping is being done from a x64 C++/CLR application but the injected dll (Loader.dll) is a **pure c++** dll.

Thanks

**Comment by staticinvocation** [comment]
unless you particularly need SxS support, try adding the flag `NoSxS`.
