### ISSUE TITLE
Don't compiling!

### ISSUE THREAD

**Issue by tijesef** [DarthTon/Blackbone#104]
I tried all but that's cod3 DOES NOT COMPILING

VS says:
Cant open include file cor.h no s f or dir.

OK! I delete the #include from this file (no include no problems!))

BUT!! There's MORE errors! I try repairing my VS re-installing my VS but It didn't work!

How do I can fix this?
Build Settings:
WSDK ver. 10.0.14393.xxx and I have installed 10586 too...
VS2015 Ex. upd 3

PS: If I using the 8.1 SDK Its fking building!!

**Comment by tijesef** [comment]
c:\n\blackbone\src\blackbone\pe\ImageNET.h(11): fatal error C1083: Cannot open include file: 'cor.h': No such file or directory

**Comment by DarthTon** [comment]
Something is wrong with your built-in include directories. Maybe 14393 SDK broke 10586 one which is currently used by project. There are probably no drawbacks in using 8.1 SDK instead if it compiles.

**Comment by tijesef** [comment]
I solve the problem! (by the wrong way!) I just copy all not-existing files from 8.1 folder to 10.0.14393 folder (I know It's NOT a GOOD way but I didn't find anything better!) don't wont to reinstall my windows then installing the vs

**Comment by tijesef** [comment]
Is it good way for me? And yep I test the kernel manual map tomorrow! (just inject a hack into a csgo) WDK installed too... Now I our o'clock in Perm is 23:23 so my time is over!

**Comment by tijesef** [comment]
OK, krnl manual map works fine! (Closing Issuse!)

**Comment by RobertZFord** [comment]
As a heads up, I found that on a stock Visual Studio 2017 installation, adding the directory "C:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.2\Include\um" to the include directory list on all projects was sufficient to resolve this issue.  I was able to compile Xenos and Blackbone and inject a test DLL into Notepad

**Comment by nhozcodon159n** [comment]
hi guys, how to compile xenos and blackbone ? i new for xenos and cant use kenel (create thread) window 10 1809
