### ISSUE TITLE
Is there any way to hook __cdecl var args function

### ISSUE THREAD

**Issue by residentkms** [DarthTon/Blackbone#107]
Hello, can I instantilate local hook (inline/hwbp) to cdecl function with var args (e.g. (__cdecl *func)(void *this, char *f, ...)) ?

**Comment by DarthTon** [comment]
No. Although it is possible to implement ellipsis argument passing into hook callback function, it's impossible to call original function unless there is an equivalent one which takes va_list instead of ellipsis.
