### ISSUE TITLE
BSOD critical structure position

### ISSUE THREAD

**Issue by UIysse** [DarthTon/Blackbone#109]
Happens in a 2 hour range after loading the blackbone driver.
I built the latest driver version from source files.
Windows 10 x64 version 1607.
Here is a rar archive containing 4 dumps. 
http://www.filedropper.com/crashdumps

**Comment by DarthTon** [comment]
Driver loading by itself should not lead to any instability. Did you call any driver functions after loading?

**Comment by UIysse** [comment]
Yes, I use the testApp.exe.
I think i called all the functions of the testApp.exe

**Comment by DarthTon** [comment]
Can you comment out this part and test it again?
```C++
status = Driver().UnlinkHandleTable( proc.pid() );
if (!NT_SUCCESS( status ))
    std::cout << "TestDriver: IOCTL_BLACKBONE_UNLINK_HTABLE failed, status 0x" << std::hex << status << "\r\n";
else
    std::cout << "TestDriver: IOCTL_BLACKBONE_UNLINK_HTABLE succeeded\r\n";
```

**Comment by UIysse** [comment]
Done, will give results in 24h

**Comment by dummy0stud** [comment]
removing from linktable on kernelmode do not trigger KPP?

**Comment by UIysse** [comment]
After around 24h uptime, no BSOD

**Comment by DarthTon** [comment]
Looks like Process handle table list is now protected by KPP then.

**Comment by chico-depressive** [comment]
http://www.alex-ionescu.com/?p=290

attach kd to kernel and type "!analyze -show 109" can help to find if KPP is checking the structure

**Comment by DarthTon** [comment]
Process handle table list is now protected by KPP. Excluded it from test.
