### ISSUE TITLE
NtWow64ReadVirtualMemory64 fails; TestApp.exe stops working

### ISSUE THREAD

**Issue by UIysse** [DarthTon/Blackbone#111]
ptr_t NativeWow64::getPEB( _PEB64* ppeb )
{
    _PROCESS_BASIC_INFORMATION_T<DWORD64> info = { 0 };
    ULONG bytes = 0;

	if (NT_SUCCESS(SAFE_NATIVE_CALL(NtWow64QueryInformationProcess64, _hProcess, ProcessBasicInformation, &info, (ULONG)sizeof(info), &bytes)))
		std::cout << "good query info" << std::endl;
	else
		std::cout << "Failed query info" << std::endl;
	if (bytes > 0 && NT_SUCCESS(SAFE_NATIVE_CALL(NtWow64ReadVirtualMemory64, _hProcess, info.PebBaseAddress, ppeb, (ULONG)sizeof(_PEB64), nullptr)))
		return info.PebBaseAddress;
	else
		std::cout << "Error reading the PEB from process. bytes : " << bytes << std::endl;
    return 0;
}
output is : 
good query info
Error reading the PEB from process. bytes : 48
After some digging, the error code is 0xc0000022. (ntwow64readvirtualmemory64)
=> 0xC0000022 STATUS_ACCESS_DENIED
{Access Denied} A process has requested access to an object but has not been granted those access rights.
Any hints to work around this ?  Target is XIGNCODE3 protected (works fine on other targets).

**Comment by staticinvocation** [comment]
If the target process is protected, either with a kernel callback or a usermode hook, then you're probably going to have to use BlackBoneDrv to accomplish your task.  This is not a bug with Blackbone.

Furthermore, opening a ticket on this project is not really the best place to ask for help in cheating in a video game.

**Comment by UIysse** [comment]
Okay, I apologize for posting in the wrong place, I will no longer open non BSOD tickets.

This being said, I am a little surprised at what you said because it looked to me like the DeviceIoControl function from test app was directly calling the driver (ie same as using BlackBoneDrv i would have thought).
Furthermore, I moved the DeviceIoControl grant access function at the top of the DriverTests (ie before the driver fails to call ntwow64readvirtualmemory64) and it resulted in all tests resulting successivly.
If I may I'd suggest you guys to move this function as the first driver test being done so that it can give full access to further tests.
That being said, this library is amazing, this mere testapp.exe has defeated one of the hardest game protection where other elaborate memory engines will fail.
I am now closing the ticket. Many thanks.

**Comment by staticinvocation** [comment]
I didn't mean to discourage you from opening issues when there is an issue with Blackbone.  I was just trying to point out that your question seemed less about Blackbone and more about bypassing a specific anti-cheat.

**Comment by DarthTon** [comment]
TestApp is just a bunch of unit-test for all major aspects of library and driver. It's not designed to do anything meaningful. 
Issue tickets are useful, you shouldn't stay away from that.
