### ISSUE TITLE
Exception handling not working in Win7 & Win8 @64bit.

### ISSUE THREAD

**Issue by MINIONBOTS** [DarthTon/Blackbone#112]
Hello again, I just wanted to ask a general question if you know something about that. I'm injecting a dll with manual mapping into a 64bit process, flags are NoDelayLoad | WipeHeader. In Win10 the exception handling is fine, but it instantly crashes in win7 and win8 systems the moment an exception happens. The dll (and all libs it used) are compiled  with SEH Exceptions (/EHa). 
Do you maybe have an idea where I can start looking for the cause of it ?

**Comment by DarthTon** [comment]
Can you compile a sample dll that reproduces that crash in DllMain for me?

**Comment by MINIONBOTS** [comment]
Thank you for the reply. 
I'll try to make a "blank" dll,  but I'll need a few days ...Monday == tons of other work :D

**Comment by MMOMinion-Powder** [comment]
I've narrowed it down to exceptions work when you load from and actual file. It doesn't when you load from an image in memory.  This again, works fine in windows 10. It does not work in 8.1, 8 or 7.

Here is a simple dll that pops a messagebox before trying to throw an exception it should pop a messagebox again if it catches it correctly.


[Win32Project1.zip](https://github.com/DarthTon/Blackbone/files/626213/Win32Project1.zip)

**Comment by MINIONBOTS** [comment]
That did the trick :) Amazing work, thanks for the fast fix!

(I'm still not seeing any way to give you a bit of "thank you" $ for your hard work, let me know when this changes ;) )
