### ISSUE TITLE
#include <cor.h> in VS2017

### ISSUE THREAD

**Issue by S0pex** [DarthTon/Blackbone#113]
Hey,

this is a Problem but it isnt directly caused by bb.
So i switched some days ago to vs 2017 rc and today I tried to use bb, the problem is sdk 10.10586 doesnt have cor.h.
Is there a new header ? Since I googled and found nearly nothing about cor.h.
So i could just undef COMPILER_MSVC but wanna know if there is another quick fix.
Regards Artur

**Comment by DarthTon** [comment]
I have no idea currently. Maybe I'll find some time to install VS2017 myself. If you don't require mapping managed/mixed code executable you can safely disable everything related to <cor.h>.

**Comment by S0pex** [comment]
Hey, thanks for the answer.
I undefed COMPILER_MSVC a time ago and compiled the project, all works fine
