### ISSUE TITLE
Blackbone: NativeLdr: LdrKernel32PatchAddress not found

### ISSUE THREAD

**Issue by Cotino** [DarthTon/Blackbone#115]
Hi,

I'm nowhere near an expert at programming, however for one of my project i've been told this library could help me.
I've been trying to run TestDriver(), however i get this error (see title).
I managed to narrow it down to NtLoader.cpp line 970,

`PatternSearch ps2( "\x48\x8D\x8C\x24\x98\x00\x00\x00\x41\xb0\x01", 11 );`
`s2.Search( pStart, scanSize, foundData );`

But it cannot find any data.
I'm running Windows 7 x64 and Visual Studio Enterprise 2015, at this point i don't know what to do.
I also have an error loading the driver 0xc000012f, but i assume that's because of this previous error.
Any help would be greatly appreciated.

**Comment by DarthTon** [comment]
LdrKernel32PatchAddress is only used in exotic case of mapping x64 image into x32 process. Driver error is not related to that and your NTSTATUS is related to driver image being invalid.

**Comment by Cotino** [comment]
That's weird, the only thing i did was give the path for Driver().EnsureLoaded to src/bin/x64/Win7Release/BlackBoneDrv/BlackBoneDrv7.sys considering that i'm under windows 7.
Is that not what it's expecting ?

**Comment by Cotino** [comment]
Anyone ?

**Comment by staticinvocation** [comment]
DriverControl::EnsureLoaded should automatically resolve the path to BlackBoneDrv7.sys assuming it is in the same directory as the executable.  You shouldn't need to set the path.

**Comment by Cotino** [comment]
It wasn't in the same directory, which is why i set the path to it. Even if i copy it in the same directory (build\x64\Debug) i still get failed to load.
Maybe this will help clear the situation : http://i.imgur.com/U9oj4gj.png

**Comment by staticinvocation** [comment]
The BlackBoneDrv7.sys you have is only 1kb in size.

**Comment by Cotino** [comment]
That is really weird. When i download the zip, src/BlackBoneDrv/bin/x64/Win7Release/BlackBoneDrv7.sys is 140 bytes.
However when navigating to it through github shows it as 61kb.
I have no idea why that is happening.

So i downloaded BlackBoneDrv7.sys alone, which is 61kb this time, and replaced the 1kb file. Now i get status 0xc0000428
I assume there are probably other files that have the same problem as the driver and that would be the source of the error.

Thanks for pointing that out in any case !

**Comment by staticinvocation** [comment]
Nope.  0xc0000428 means you have to sign your driver or enable test mode.

**Comment by Cotino** [comment]
Is there a list of the error status somewhere ?

I commented out TestLocalHook() as it triggers a breakpoint, perhaps the test mode enabling was in there ?
What would the function be to enable test mode ?

**Comment by staticinvocation** [comment]
You can view the list of NTSTATUS codes [here](https://msdn.microsoft.com/en-us/library/cc704588.aspx).

Kernel device drivers on Windows must be digitally signed using a code signing certificate.  These cost about $100/year to purchase and are subject to identity verification.

For personal use, you can bypass this restriction by enabling Test Signing mode in Windows.  A tutorial on how to do that is available [here](http://www.queryadmin.com/147/enable-disable-windows-7-test-mode/).

**Comment by Cotino** [comment]
To be honest i don't know, i have to bypass a protection which uses a driver. Someone redirected me here saying that Blackbone could provide that, and here I am.
