### ISSUE TITLE
Crashing and working somtimes.

### ISSUE THREAD

**Issue by vldr** [DarthTon/Blackbone#116]
I'm downloading the data, and I use the code below. It works sometimes and crashes sometimes.
When it crashes, I dump out the buffer into a file and I am still able to inject it just fine.
The code is inside a dll, the dll injects a dll inside a process.

It simply crashes most of the time, and sometimes it works. When I debug the program after the dll gets injected into the process the moment it crashes it replies with "0xC0000005: Access violation reading location"

![u9av06](https://cloud.githubusercontent.com/assets/9101924/21077988/4258a0d0-bf24-11e6-9daa-c9d4535e66e0.png)

**Comment by staticinvocation** [comment]
Is the Blackbone process crashing or the target process crashing?

**Comment by vldr** [comment]
Hi, the target process (csgo.exe) keeps crashing. I've test many different dlls and the result presists. When debugging the target process on when it crashes it replies with something similar to ` ntdll.dll hex offset - and access violation.`

**Comment by DarthTon** [comment]
Can you make a process dump during crash and post it?

**Comment by vldr** [comment]
`Unhandled exception at 0x772F8EC1 (ntdll.dll) in csgo.exe: 0xC0000005: Access violation reading location 0x0094D164.`

I haven't done this before but I used Visual Studio to dump it, the dll isn't inside it ethier.
https://mega.nz/#!HcM0lYIJ!rhW3YRkyBYALJL1Um7fymkVLHjRS06vKDm_h48WZRko

**Comment by staticinvocation** [comment]
Seems to be the same issue as #106 #101.  RtlDispatchAPC seems to be releasing an invalid activation context.  WinSxS is such a pain in the ass and unfortunately I do not know enough about SxS to explain why this is behavior is happening.

I'm going to try replacing QueueUserApc with NtQueueApcThread with arg5 set to -1.  This should jump out the activation context code.  This is probably not the best solution, but it might work.

**Comment by DarthTon** [comment]
Potential fix in 04808dcc23ebc0b33daf04237b33913a5e590b0e. #106 #101 should be affected too.

**Comment by vldr** [comment]
Hah no way. It's working for me now. Thanks a lot guys!

**Comment by staticinvocation** [comment]
any idea why this was happening @DarthTon ?

**Comment by DarthTon** [comment]
Looks like it has something to do with the way I utilize activation context.
Maybe it should be activated once, before queuing any APC to worker thread. But currently I activate it each time when calling module initializes.
