### ISSUE TITLE
BSOD when trying to map my driver with BlackboneDrv

### ISSUE THREAD

**Issue by wczmich** [DarthTon/Blackbone#121]
Hi,
I'm trying to map my own KMDF driver with blackbone but I get BSOD with following reason PAGE_FAULT_IN_NONPAGED_AREA. I'm on windows 8.1. Can you suggest what could be the reason for this ? Are there any requirements for driver im trying to map ? Should it be WDM/KMDF ? Can you provide a link to any test driver I use can check if this is the reason for BSOD ?
Regerds

**Comment by staticinvocation** [comment]
Both arguments of DriverEntry, DriverObject and RegistryPath, are set to null (0x00000000`00000000).

**Comment by wczmich** [comment]
staticinvocation - thanks for fast response. You are right - didnt get bsod when returning from DriverEntry without calling DriverInitialize. Does it mean that driver I'm tring to map must be driverless like TDL requries ?

**Comment by staticinvocation** [comment]
Yes.  You cannot use DriverObjects because then your driver would have to be linked in PsLoadedModuleList which defeats the purpose of manual mapping a driver.

**Comment by wczmich** [comment]
I've successfully mmaped my driver but run into another problem when I try to communite with it using DeviceIoControl. I get BSOD KERNEL_SECURITY_CHECK FAILURE. Are there any restrictions/requirements in communication to mapped driver ?

**Comment by staticinvocation** [comment]
You're probably overrunning a buffer in your ioctl handler.  You're going to have to debug this yourself in WinDbg as it's out of Blackbone's scope.

**Comment by wczmich** [comment]
I've solved my problem by using release version of my driver being mapped. Can't explain why debug version cannot be mapped without BSOD. 
But I've run into same BSOD (KERNEL_SECURITY_CHECK_FAILURE) when initiating char array in my local function inside mapped driver. When I make array global - its ok, when I just declare it (without initiating it) - it is also ok. Can you drop some suggestions about memory used by driver being manually mapped ? 
thanks in advance

**Comment by DarthTon** [comment]
Probably stack protection functions rely on PsLoadedModuleList entry that is absent.

**Comment by wczmich** [comment]
Ok - working on release - no problem for me. 
Can you advice why I get KERNEL_SECURITY_CHECK_FAILURE when declaring and initiating local char array in function MyFunction used for notiftying of thread creation - I'm callling PsSetCreateThreadNotifyRoutine (MyFunction)? The only difference is that MyFuction is called in context of process creating thread.
Everything works when I load my driver in test mode. Problem appears only when mapping using blackbone.

**Comment by wczmich** [comment]
closing this issue as main problem solved using release versio - will create new one problem that remained
