### ISSUE TITLE
I have problem loading driver

### ISSUE THREAD

**Issue by Zibux** [DarthTon/Blackbone#122]
Driver functionality test
TestDriver: Failed to load driver. Status 0xc0000034

**Comment by staticinvocation** [comment]
BlackBoneDrvX.sys must be in the same directory as TestApp

**Comment by Zibux** [comment]
Where can i get the BlackBoneDrvX.sys file. I googled it and didn't find anything.

**Comment by DarthTon** [comment]
Compile it yourself or use release version from repo.

**Comment by Zibux** [comment]
I compile it no blackbonedrvx generates?

**Comment by Zibux** [comment]
ok i put the file in same folder as .exe 
now i get "TestDriver: Failed to load driver. Status 0xc000012f"

**Comment by DarthTon** [comment]
Driver file is not an actual PE file. Something is wrong with driver.

**Comment by DarthTon** [comment]
Duplicate #132
