### ISSUE TITLE
Detour.CallOriginal() for x64

### ISSUE THREAD

**Issue by Randshot** [DarthTon/Blackbone#124]
Hi,

just noticed that the CallOriginal() function is only available for WIN32.
Is there a reason for this?

```C++
typedef BOOL(WINAPI *tIsDebuggerPresent)(void);
tIsDebuggerPresent oIsDebuggerPresent = (tIsDebuggerPresent)GetProcAddress(GetModuleHandle(L"kernel32.dll"), "IsDebuggerPresent");
Detour<tIsDebuggerPresent> xIsDebuggerPresent;
BOOL WINAPI hIsDebuggerPresent(void)
{
	BOOL result = xIsDebuggerPresent.CallOriginal();         //<-- error here
	std::cout << "IsDebuggerPresent: " << result << "\n";
	return false;
}
```

^ This code only works on win32 for me. On x64 it gives me a missing member error.

 I noticed that in the '_HookHandlers.h_' file, it excludes __stdcall, __thiscall and __fastcall, and thus resulting in the missing CallOriginal() error, since WINAPI equals __stdcall.

```C++
#include "HookHandlerCdecl.h"

#ifndef USE64
#include "HookHandlerStdcall.h"
#include "HookHandlerThiscall.h"
#include "HookHandlerFastcall.h"
#endif
```

**Comment by DarthTon** [comment]
Intellisense can give you an error, but compiler shouldn't. On x64 __cdecl, __stdcall, __fastcall, __thiscall are all the same. And Hook isn't really designed for user to call 'CallOriginal'. Hook engine does it by itself and your function is merely a callback. Although it is possible to use it the way you wrote, but you should explicitly specify CallOrder::NoOriginal.

**Comment by Randshot** [comment]
Hm, ok. I will try disabling it.
I did specify 'CallOrder::NoOrigina'. Just forgot to inlcude it in the question.
