### ISSUE TITLE
Manual map driver directly from memory, without using full path

### ISSUE THREAD

**Issue by steffenbrem** [DarthTon/Blackbone#125]
I want to manual map a driver directly from memory without it ever being on the harddisk. I came across one issue and that is the `InitializeObjectAttributes` call which uses the full path of the driver. Is it possible to somehow change this so you don't need to store the driver on the disk?

I am refering to this line: https://github.com/DarthTon/Blackbone/blob/e59f720e802ee83cc2c292361057595223ace247/src/BlackBoneDrv/Loader.c#L700`

**Comment by staticinvocation** [comment]
Yes, of course.  Just strip out all of the file code and copy your driver buffer into fileData.

**Comment by steffenbrem** [comment]
@staticinvocation Alright, so I could leave a fake path or a path to some random file as the second argument of the `InitializeObjectAttributes` function?

**Comment by staticinvocation** [comment]
All that does is initialize the OBJECT_ATTRIBUTES struct which is passed into ZwCreateFile.  Obviously, if you remove the file code you don't need that call.

**Comment by steffenbrem** [comment]
Ah that is what I thought, thanks for confirming!
