### ISSUE TITLE
Update to Windows "creators update" sdk

### ISSUE THREAD

**Issue by mirh** [DarthTon/Blackbone#128]
Aka build 10.0.15063.0. 
...

I mean, if it was for me I'd ask to just stick to W7 one, profit, stable forever. 
But I do see that with W10 issues left and right, keeping up-to-date is the only viable thing possible.

**Comment by DarthTon** [comment]
I'll switch when possible, but that won't have any noticeable effect :-)

**Comment by DarthTon** [comment]
implemented in bb9004bd0a17730097411fac12f3c22890d6d8f8
