### ISSUE TITLE
Another Driver not loading error.

### ISSUE THREAD

**Issue by Zibux** [DarthTon/Blackbone#132]
Now i get this on test app  http://prntscr.com/ec38b4

**Comment by glebious** [comment]
you system is enabled certificate check's, disabled Driver verification is command - bcdedit /set TESTSIGNING ON
and reboot computer

**Comment by Zibux** [comment]
Now i get this http://prntscr.com/ec7c9i

**Comment by staticinvocation** [comment]
update your windows, only 10586 and 14393 is supported by blackbone
