### ISSUE TITLE
Possible to use with C# Application?

### ISSUE THREAD

**Issue by YourOwnDev** [DarthTon/Blackbone#133]
Is it at all possible to use this library in a C# application? If so, can someone help me set that up please?

**Comment by extperl** [comment]
you can compile it as a dll and export/import the functions.
you will have to find out yourself how to do it.

**Comment by YourOwnDev** [comment]
I changed the configuration type of the blackbone project to .dll and get this now:

> TraceHook.obj : error LNK2001: unresolved external symbol __imp__Disasm@4

**Comment by extperl** [comment]
there already a premade build type release(dll)

**Comment by YourOwnDev** [comment]
ahhh, yes i see. thank you. okay now in my C# application, can i just go ahead and start importing functions, or in the blackbone source for the dll do i neeed to __declspec(dllexport) what i want first?

**Comment by DarthTon** [comment]
You need to create a C++/CLI proxy dll that will export blackbone functions as managed code and then use it in your C# app.
