### ISSUE TITLE
Issues mmapping packed/protected DLL

### ISSUE THREAD

**Issue by steffenbrem** [DarthTon/Blackbone#135]
Lately I have been trying to get manual mapping to work with a packed/protected DLL (VMProtect 3 in my case). I couldn't get it to work, have tried all possible combinations of the mapping flags. Is it possible to even make packed binaries work with Blackbones mmap? Has anyone else succeeded in mmapping a packed binary?

**Comment by extperl** [comment]
for me it works, check your compile and packer settings

**Comment by vldr** [comment]
turn off anti debug and anti vm. blackbone mmap doesnt work with _exception_

**Comment by steffenbrem** [comment]
No luck when mmapping a simple packed dll. I am doing the following:
```
process.mmap().MapImage(byteArray.size(), byteArray.data(), false, RebaseProcess | NoSxS | NoExceptions | NoTLS | WipeHeader, nullptr, nullptr, &args)
```

It crashes on `PEImage::GetTLSCallbacks`:
![](https://i.imgur.com/YrOK2pW.png)

This is the profile I use for the protected dll. No VM, only packed output.
![](https://i.imgur.com/3NxiBxV.png)

**Comment by DarthTon** [comment]
Seems like a bug in library. Can you post me a packed dll?

**Comment by vldr** [comment]
I know your problem, you can't mmap a file with "Pack the Output File" option on... 

You can have everything except: anti debug, anti vm, and pack output file.

**Comment by steffenbrem** [comment]
@DarthTon https://s3.eu-central-1.amazonaws.com/divinelabs/DarthTon.vmp.dll

Here you have very minimalistic packed binary. It is using CppRestSDK which seems to be the root cause of the mapping error. It runs perfectly fine if you don't manual map it and load it with `LoadLibrary`. 

If I remove the statically linked CppRestSDK I can manual map it without issues.
