### ISSUE TITLE
Issues manual mapping binary with toolset v141

### ISSUE THREAD

**Issue by koemeet** [DarthTon/Blackbone#137]
I've recently switched my binary from v140 to v141 toolset. Using `LoadLibrary` to load it into other processes work fine with the new binary, but when I manual map it, it behaves very strange. Since the new binary itself works fine, the first question for me was if Blackbones `Process.mmap()` is compatible with the newer toolset? From what I have debugged, applications seem to work for 50%. It kinda works and breaks on the most ridiculous places. 

Any idea if its possible to make process.mmap() work with the v141 toolset?

In my case, I was using the following arguments:
```
process.mmap().MapImage(size, binaryData, false, NoSxS | WipeHeader | RebaseProcess | NoDelayLoad, nullptr, nullptr, &args);
```

**Comment by staticinvocation** [comment]
are you using 141 to build blackbone or the image you wish to map?

**Comment by steffenbrem** [comment]
I was mapping a v141 dll with Blackbone running with v140. Should I try compiling blackbone to 141 also?

**Comment by DarthTon** [comment]
I haven't tested it yet with the new toolset.

**Comment by koemeet** [comment]
Doesn't seem to be an issue anymore.
