### ISSUE TITLE
Can't open project in Visual Studio 2017

### ISSUE THREAD

**Issue by tijesef** [DarthTon/Blackbone#138]
Here is an error
C:\Users\s0m3b0dYy\Desktop\blackbon\Blackbone\src\BlackBoneDrv\BlackBoneDrv.vcxproj : error  : Не удалось прочесть файл проекта BlackBoneDrv.vcxproj.
C:\Program Files (x86)\Windows Kits\10\build\WindowsDriver.KernelMode.Default.props(15,11): в условии "$(_NT_TARGET_VERSION) >= $(_NT_TARGET_VERSION_WIN10)" была попытка числового сравнения выражения "$(_NT_TARGET_VERSION)", равного не числу, а "".

**Comment by tijesef** [comment]
C:\Users\s0m3b0dYy\Desktop\blackbon\Blackbone\src\BlackBoneDrv\BlackBoneDrv.vcxproj : error  : Can't read the project file BlackBoneDrv.vcxproj.
C:\Program Files (x86)\Windows Kits\10\build\WindowsDriver.KernelMode.Default.props(15,11): in the condition "$(_NT_TARGET_VERSION) >= $(_NT_TARGET_VERSION_WIN10)" there was an attempt a numeric comparison expression "$(_NT_TARGET_VERSION)", equal not the number, but "".

the translated to english error (used yandex.translate)

**Comment by DarthTon** [comment]
VS 2017 doesn't support any WDK yet. 2015 is the way to go for now.

**Comment by mirh** [comment]
It does now.

**Comment by DarthTon** [comment]
Yeap, new WDK supports VS2017.
