### ISSUE TITLE
Kernel Driver Manual Map always returning 0x0

### ISSUE THREAD

**Issue by arpski** [DarthTon/Blackbone#140]
I've been trying to manual map my driver with Black Bone Driver().MMapDriver() function with no goal.

I don't know why but it is always returning 0 even if the path to the driver is incorrect.

`{
		auto status = Driver().EnsureLoaded();
		if (status == STATUS_SUCCESS) {

			printf("Driver handle acquired successfully, status: 0x%X \n", status);
			Sleep(1000);
		}
		else {
			printf("Failed to grab device handle, status: 0x%X \n", status);
			printf("Aborting... \n");
			Sleep(3000);

			return NULL;
		}
	}
	auto status = Driver().MMapDriver(L"GXTHFV.sys");
	if (status == STATUS_SUCCESS) {
		printf("Driver has been manual mapped into system space, status: 0x%X \n", status);
	}
	else {
		printf("Failed to manual map driver, status: 0x%X \n", status);
	}`

So that way it doesn't matter if path to the driver is correct or not, it is returning 0x0 code anyway.

Any idea what am I missing there?

**Comment by DarthTon** [comment]
Probably status code isn't returned properly from driver mapping thread in r0.

**Comment by arpski** [comment]
I have checked with the DbgView and it ineed was wrong, DbgView was looking for wrong path and when i gave the "right path" it returned BBMapWorker: Successfully mapped image at :address: ;)
