### ISSUE TITLE
Manual Injection from 64bit process to 32bit process

### ISSUE THREAD

**Issue by injara2** [DarthTon/Blackbone#141]
Hey,

When I try to inject from a 32bit process a 32bit dll to a 32bit destination process everything works fine.
But when I change the injecting process to 64bit(inject from a 64bit process a 32bit dll to a 32bit destination process) the injection crashes the destination process.
The crash happens at this phase of the injection:
BlackBone: ManualMap: Enabling exception support for image 'kernelbase.dll'

Any recommendations how to overcome this?

Thanks

**Comment by DarthTon** [comment]
Source and target process architecture must match because of current assembly generation model.

**Comment by injara2** [comment]
Thanks
