### ISSUE TITLE
Driver doesnt support Windows 10 Creators Update

### ISSUE THREAD

**Issue by boris768** [DarthTon/Blackbone#145]
The driver starts with the status 0xC00000BB. Is there any information about the new SSDT?

**Comment by DarthTon** [comment]
I'll update driver when ntoskrnl symbols become available.

**Comment by fisherprice84** [comment]
https://download.microsoft.com/download/6/9/C/69C86A1F-C8E9-4F28-B6FC-9FA2BCE98BC0/Windows_Rs2.15063.0.170317-1834.x64FRE.Symbols.msi

15063.0 - i dont think many chance in .11

**Comment by boris768** [comment]
Okay, i parsed it from windbg. If you need tables or any other data - you can write to me

pData->KExecOpt = 0x1BF; 
pData->Protection = 0x6CA; 
pData->ObjTable = 0x418; 
pData->VadRoot = 0x628;
pData->NtProtectIndex = 0x50;
pData->NtCreateThdIndex = 0xB9; 
pData->NtTermThdIndex = 0x53; 
pData->PrevMode = 0x232;
pData->ExitStatus = 0x6F8;

**Comment by fisherprice84** [comment]
thankyou
