### ISSUE TITLE
GetExport() fails for .Net x64 exe

### ISSUE THREAD

**Issue by HubbyteDev** [DarthTon/Blackbone#146]
Hi.

I am attempting to call an export that I have in a C# 64bit exe. It was created with [DllExport] using UnmanagedExports from nuget.

The code I am using is:
```
auto test = _process.modules().GetModule(L"Test.dll);
auto pRemote = _process.modules().GetExport(test, "RunMe");
```

However, it is erroring inside GetExport. I have stepped though and found it had a problem reading the export name at this line:
`pName = (char*)(pAddressOfNames[i] + reinterpret_cast<uintptr_t>(pExpData) - expBase);`

You can see from the screenshot below that it fails to read
![export](https://cloud.githubusercontent.com/assets/3884418/24839725/e9496668-1d57-11e7-985b-eac40aefeb6f.png)

Also, to avoid the questions about if the export exists:
![cf2](https://cloud.githubusercontent.com/assets/3884418/24841448/dff11bae-1d7c-11e7-8cc6-0e940b3ce17f.png)

Does anyone have any ideas?

Edit: Now shows the test.dll example as that is the example I have provided

**Comment by DarthTon** [comment]
Can you upload this file somewhere?

**Comment by HubbyteDev** [comment]
https://drive.google.com/open?id=0ByvbwOgGvJ04R0pBTUdtOHA5OHc

I have this now working with some small modifications. I have created a Pull Request.

My next issue is getting the .Net code to run. It should just open a MessageBox right now.

**Comment by DarthTon** [comment]
Problem with your dll is that it has sort of invalid size of export directory. Export directory contains only export header when it should contain also name and ordinal tables.

**Comment by HubbyteDev** [comment]
I used https://www.nuget.org/packages/UnmanagedExports, which from what I could tell it all works fine.

Any ideas what else to use without a manual C++ wrapper?

**Comment by DarthTon** [comment]
I'm fixing this issue now, it would work.

**Comment by HubbyteDev** [comment]
Thank you. I look forward to trying it out 👍
