### ISSUE TITLE
Creator's update  @ fix#144

### ISSUE THREAD

**Issue by MMOMinion-Powder** [DarthTon/Blackbone#148]
Hi, Manual map is now working on the creator's updated windows 10, however it is broken for the old windows 10 version.

**Comment by MINIONBOTS** [comment]
![grafik](https://cloud.githubusercontent.com/assets/2842405/24897699/394d4fba-1e9a-11e7-9ba7-351301374525.png)

Just fix the VersionHelper.h, problem solved.
