### ISSUE TITLE
Can't compile.

### ISSUE THREAD

**Issue by tijesef** [DarthTon/Blackbone#151]
Don't compiling 8 8.1 and 7 versions of driver with the 10.15063.0 ver of WDK

1>MMap.c(23): error C2061: синтаксическая ошибка: идентификатор "PAPISET_VALUE_ENTRY"
1>MMap.c(23): error C2059: синтаксическая ошибка: ;
1>MMap.c(24): error C2061: синтаксическая ошибка: идентификатор "PAPISET_VALUE_ARRAY"
1>MMap.c(24): error C2059: синтаксическая ошибка: ;
1>MMap.c(25): error C2061: синтаксическая ошибка: идентификатор "PAPISET_NAMESPACE_ENTRY"
1>MMap.c(25): error C2059: синтаксическая ошибка: ;
1>MMap.c(26): error C2061: синтаксическая ошибка: идентификатор "PAPISET_NAMESPACE_ARRAY"
1>MMap.c(26): error C2059: синтаксическая ошибка: ;
1>MMap.c(860): error C2065: PAPISET_NAMESPACE_ARRAY: необъявленный идентификатор
1>MMap.c(860): error C2146: синтаксическая ошибка: отсутствие ";" перед идентификатором "pApiSetMap"
1>MMap.c(860): error C2065: pApiSetMap: необъявленный идентификатор
1>MMap.c(860): error C2064: результатом вычисления фрагмента не является функция, принимающая 337 аргументов
1>MMap.c(868): error C2065: pApiSetMap: необъявленный идентификатор
1>MMap.c(868): error C2223: выражение слева от "->Count" должно указывать на структуру или объединение
1>MMap.c(870): error C2065: PAPISET_NAMESPACE_ENTRY: необъявленный идентификатор
1>MMap.c(870): error C2146: синтаксическая ошибка: отсутствие ";" перед идентификатором "pDescriptor"
1>MMap.c(870): error C2065: pDescriptor: необъявленный идентификатор
1>MMap.c(870): warning C4047: =: "int" отличается по уровням косвенного обращения от "void *"
1>MMap.c(871): error C2065: PAPISET_VALUE_ARRAY: необъявленный идентификатор
1>MMap.c(871): error C2146: синтаксическая ошибка: отсутствие ";" перед идентификатором "pHostArray"
1>MMap.c(871): error C2065: pHostArray: необъявленный идентификатор
1>MMap.c(871): warning C4047: =: "int" отличается по уровням косвенного обращения от "void *"
1>MMap.c(881): error C2065: pDescriptor: необъявленный идентификатор
1>MMap.c(881): error C2065: pApiSetMap: необъявленный идентификатор
1>MMap.c(881): error C2223: выражение слева от "->Array" должно указывать на структуру или объединение
1>MMap.c(882): error C2065: pApiSetMap: необъявленный идентификатор
1>MMap.c(882): error C2065: pDescriptor: необъявленный идентификатор
1>MMap.c(882): error C2223: выражение слева от "->NameOffset" должно указывать на структуру или объединение
1>MMap.c(882): error C2223: выражение слева от "->NameLength" должно указывать на структуру или объединение
1>MMap.c(882): error C2168: memcpy: слишком мало фактических параметров для подставляемой функции
1>MMap.c(889): error C2065: PAPISET_VALUE_ENTRY: необъявленный идентификатор
1>MMap.c(889): error C2146: синтаксическая ошибка: отсутствие ";" перед идентификатором "pHost"
1>MMap.c(889): error C2065: pHost: необъявленный идентификатор
1>MMap.c(889): warning C4047: =: "int" отличается по уровням косвенного обращения от "void *"
1>MMap.c(896): error C2065: pHostArray: необъявленный идентификатор
1>MMap.c(896): error C2065: PAPISET_VALUE_ARRAY: необъявленный идентификатор
1>MMap.c(896): error C2064: результатом вычисления фрагмента не является функция, принимающая 337 аргументов
1>MMap.c(896): error C2065: pApiSetMap: необъявленный идентификатор
1>MMap.c(896): error C2065: pDescriptor: необъявленный идентификатор
1>MMap.c(896): error C2223: выражение слева от "->DataOffset" должно указывать на структуру или объединение
1>MMap.c(897): error C2065: pHost: необъявленный идентификатор
1>MMap.c(897): error C2065: pHostArray: необъявленный идентификатор
1>MMap.c(897): error C2223: выражение слева от "->Array" должно указывать на структуру или объединение
1>MMap.c(900): error C2065: pHostArray: необъявленный идентификатор
1>MMap.c(900): error C2223: выражение слева от "->Count" должно указывать на структуру или объединение
1>MMap.c(903): error C2065: pApiSetMap: необъявленный идентификатор
1>MMap.c(903): error C2065: pHost: необъявленный идентификатор
1>MMap.c(903): error C2223: выражение слева от "->ValueOffset" должно указывать на структуру или объединение
1>MMap.c(903): error C2223: выражение слева от "->ValueLength" должно указывать на структуру или объединение
1>MMap.c(903): error C2168: memcpy: слишком мало фактических параметров для подставляемой функции
1>MMap.c(907): error C2065: pHostArray: необъявленный идентификатор
1>MMap.c(907): error C2223: выражение слева от "->Count" должно указывать на структуру или объединение
1>MMap.c(921): error C2065: pApiSetMap: необъявленный идентификатор
1>MMap.c(921): error C2065: pHost: необъявленный идентификатор
1>MMap.c(921): error C2109: для индекса требуется массив или указатель
1>MMap.c(921): error C2168: memcpy: слишком мало фактических параметров для подставляемой функции

Is there any solution?

**Comment by luciouskami** [comment]
Not update yet?
