### ISSUE TITLE
Failed to load dependency...

### ISSUE THREAD

**Issue by ahmetabdi** [DarthTon/Blackbone#152]
```
Process Handle : 000000000000188C
Trying to inject...
BlackBone: ManualMap: Mapping image 'xx.dll' with flags 0x0
BlackBone: ManualMap: Loading new image 'xx.dll'
BlackBone: ManualMap: Image base allocated at 0x00000293ACA30000
BlackBone: ManualMap: Performing image copy
BlackBone: ManualMap: Relocating image 'xx.dll'
BlackBone: ManualMap: Loading new dependency 'd3dcompiler_43.dll'
BlackBone: ManualMap: Dependency path resolved to 'C:\WINDOWS\system32\d3dcompiler_43.dll'
BlackBone: ManualMap: Failed to load dependency 'C:\WINDOWS\system32\d3dcompiler_43.dll'. Status = 0x0
```

Code:

```
std::cout << "Process Handle : " << hProcess << std::endl;
std::cout << "Trying to inject... " << std::endl;

blackbone::Process injectProc;
injectProc.Attach(hProcess);
if (injectProc.valid())
{
	blackbone::eLoadFlags flags = blackbone::NoFlags;
	injectProc.mmap().MapImage(L"xx.dll", flags);
}
```
I keep getting the `Failed to load dependency` error when trying to inject into any process, what does this mean? I've checked the system32 folder and the `dll` is present.

I've tried changing the flags same issue: 
`blackbone::eLoadFlags flags = blackbone::ManualImports | blackbone::RebaseProcess;`

**Comment by ahmetabdi** [comment]
Sidenote: working using memory map on xtreme injector

**Comment by DarthTon** [comment]
Can you post me your test dll?

**Comment by ahmetabdi** [comment]
@DarthTon https://drive.google.com/file/d/0B77HdSIB3VH1dnc5V3FkNWhzSzg/view?usp=sharing

**Comment by DarthTon** [comment]
Are you trying to map it using x86 library version?

**Comment by ahmetabdi** [comment]
I've included in my project and I'm building using x64 not sure how you select library version

**Comment by ahmetabdi** [comment]
I've tried creating a basic dll that just outputs a MessageBox on injection and even this basic example fails using Xenos when Manual Mapping does Xenos spit out logs anywhere?

**Comment by DarthTon** [comment]
Blackbone log is more complete than xenos'. Have you updated to the latest bbone commit? Weird, because it works totally fine on my machine.

**Comment by ahmetabdi** [comment]
Ok.. MessageBox works on Xenos but not when running through BlackBone manually, I don't get a MessageBox but it says the entrypoint was called. Something weird going on

```
BlackBone: ManualMap: Mapping image 'HelloWorld64.dll' with flags 0x4040
BlackBone: ManualMap: Loading new image 'HelloWorld64.dll'
BlackBone: ManualMap: Image base allocated at 0x0000017EA1680000
BlackBone: ManualMap: Performing image copy
BlackBone: ManualMap: Relocating image 'HelloWorld64.dll'
BlackBone: ManualMap: Enabling exception support for image 'HelloWorld64.dll'
BlackBone: ManualMap: Vectored hander: 0x0000017EA5A10000
BlackBone: ManualMap: Performing security cookie initializtion for image 'HelloWorld64.dll'
BlackBone: ManualMap: Calling entry point for 'HelloWorld64.dll', Reason: 1
```

```
BOOL APIENTRY DllMain( HMODULE hModule,
                       DWORD  ul_reason_for_call,
                       LPVOID lpReserved
					 )
{
	switch (ul_reason_for_call)
	{
	case DLL_PROCESS_ATTACH:
		MessageBox(NULL, "DLL_PROCESS_ATTACH", "caption", 0);
	case DLL_THREAD_ATTACH:
		MessageBox(NULL, "DLL_THREAD_ATTACH", "caption", 0);
	case DLL_THREAD_DETACH:
		MessageBox(NULL, "DLL_THREAD_DETACH", "caption", 0);
	case DLL_PROCESS_DETACH:
		MessageBox(NULL, "DLL_PROCESS_DETACH", "caption", 0);		
		break;
	}
	return TRUE;
}
```

**Comment by ahmetabdi** [comment]
Does attaching via a HANDLE make any difference?

**Comment by ahmetabdi** [comment]
Sorry for spam -  It has to be just tried injecting from PID and it works, is HANDLE attaching working?

**Comment by DarthTon** [comment]
I'm so sure it works after this :)

**Comment by ahmetabdi** [comment]
Thanks for help, I pretty sure the problem lies with the handle and not BB then.

I'm using https://drive.google.com/open?id=0B77HdSIB3VH1WTUzWmJRdzRNVDA

which grabs the process handles from services/protected processes like csrss and lsass

**Comment by DarthTon** [comment]
Ah, I see.

**Comment by ahmetabdi** [comment]
Thanks for your time.. all the dots connect now
