### ISSUE TITLE
CreateFileW returns "file not found"

### ISSUE THREAD

**Issue by alaknas** [DarthTon/Blackbone#157]
Hey, I'm wondering what the cause of this phenomena may be,

I tried adding some debugging to CreateFileW whilst trying to load the driver, and found that CreateFileW is returning error code 2 (File not found) and LoadDriver is returning "invalid arguments" (Error 87).

However when i debugged the path variable inside the Reload function the path seems to be correct (points to the exe dir, in which the named .sys file resides)

I'm actually thinking this may be a "general" problem more so than a project specific one, but nontheless as it is the blackbone project im buildning i thought i would ask here and see if anyone has a clue

**Comment by staticinvocation** [comment]
If the driver cannot be loaded, the Blackbone file device will not be created, thus causing `CreateFileW` to fail when attempting to open `\\.\Blackbone`.  `NtLoadDriver` gets passed a service entry in the registry, so I'd check to see if the service entry is proper and points to the driver on disk.

**Comment by alaknas** [comment]
@staticinvocation could you paste me a sample of what it _should_ look like so i have a good comparison? for example mine starts with \??\.C
And from what i've tried reading on MSDN etc that (depending on paper) doesn't exactly match what could be expected, some state it should be \?\.C and some say it should be \\.C so.. i'm a wee bit confused as to how it should be.

Thank you regardless for the reply

**Comment by DarthTon** [comment]
Path should be like this: \??\C:\BlackBoneDrv10.sys

**Comment by alaknas** [comment]
Ah, have to investigate why i have a dot before the C then, and remove it
