### ISSUE TITLE
Is it normal?

### ISSUE THREAD

**Issue by andy1279** [DarthTon/Blackbone#159]
I want to change Access Mask, so I called BBGrantAccess, and i know it changed, but i failed at ReadProcessMemory(Target Process is protected by ObRegisterCallbacks)
So i called ExpLookupHandleTableEntry Dynamically and when i changed Access Mask by return Handle Entry, then i get BSOD.

**Comment by DarthTon** [comment]
It's not normal. Can you post memory dump?
