### ISSUE TITLE
Xenos not recognized my driver

### ISSUE THREAD

**Issue by kediragg** [DarthTon/Blackbone#161]
I changed the name of everything related to '' BlackBone '' including driver name (L ''BlackBone'') to kedira (L ''Kedira'') and I load the driver but xenos does not recognize and it says that it does not have to start the driver that Has to be by test mode but the driver is already started. What can I do?

**Comment by DarthTon** [comment]
Duplicate https://github.com/DarthTon/Xenos/issues/33
