### ISSUE TITLE
Resolving WinHTTP using ManualImports flag

### ISSUE THREAD

**Issue by jl2378** [DarthTon/Blackbone#166]
I'm trying to manually map a DLL into a process. The DLL uses winhttp.lib and works fine with native inject, manual map without flags, but fails when I add the ManualImports flag.

I also have 3rd party static libs, but those get imported properly. Issue seems to only happen with dynamic libs.

**Comment by DarthTon** [comment]
Can you create some sample dll for me to reproduce this?

**Comment by jl2378** [comment]
I haven't been able to reproduce this. :/
