### ISSUE TITLE
Mapping Driver doesn't resolve HAL.dll

### ISSUE THREAD

**Issue by koemeet** [DarthTon/Blackbone#169]
I noticed it was unable to automatically resolve `HAL.dll` used by the driver I am trying to map.

![](https://images.discordapp.net/attachments/254177285349834762/334681416744828939/unknown.png)

The only import my driver uses from it is `KeQueryPerformanceCounter`:
![](https://images.discordapp.net/attachments/254177285349834762/334686051274850304/unknown.png)

Is this a bug or do you prefer us to manually resolve these kind of things?

**Comment by DarthTon** [comment]
It's expected. Currently blackbone doesn't even try to resolve existing kernel modules. I'm planning to change this in the future.

**Comment by koemeet** [comment]
Alright, thanks, will resolve needed modules manually.
