### ISSUE TITLE
Windows 10 Build 9926

### ISSUE THREAD

**Issue by navossoc** [DarthTon/Blackbone#17]
Hi...

Seems the newer versions from from Windows 10 changed their Major and Minor version.

I can confirm this behavior on Windows 10 Preview x64 Build 9926.

You can confirm the information here:
http://www.windowscentral.com/microsoft-confirms-nt-kernel-version-windows-10-will-go-100
http://en.wikipedia.org/wiki/Windows_10#Version_history
https://social.msdn.microsoft.com/Forums/windowsdesktop/en-US/6f22c643-7a33-4581-9fbb-5462c1602f8b/windows-10-getversionex?forum=windowssdk

Not sure if this helps, but you can check it later:

```
// Windows 10, technical preview, build 9926
pData->KExecOpt         = 0x1BF; // same
pData->Protection       = 0x69A;
pData->ObjTable         = 0x418;
pData->VadRoot          = 0x5F8;
pData->NtCreateThdIndex = 0xB2;
pData->NtTermThdIndex   = 0x53; // same
pData->PrevMode         = 0x232; // same
pData->ExitStatus       = 0x6E0;
pData->MiAllocPage      = 0;	// not sure
pData->ExRemoveTable    = 0;	// not sure
```

Thanks

**Comment by DarthTon** [comment]
Yeah. I'm just too lazy to update it :)

**Comment by tekniqq** [comment]
hey DarthTon are u selling your private injectors

**Comment by TheDeadCode** [comment]
I don't believe DarthTon has private injectors. You could very very easily make an injector with Blackbone's code. What I did is sign myself the drivers with a code signing certificate and I was done.

**Comment by tekniqq** [comment]
could u make me one i can pay u

**Comment by TheDeadCode** [comment]
Add me on skype: jadexkiller

**Comment by tekniqq** [comment]
added u

**Comment by DarthTon** [comment]
No, I'm not making private injectors, and this is not an appropriate place to ask for them.

**Comment by TheDeadCode** [comment]
@DarthTon What he meant is that he needed an injector not in test mode. Few games refuse to start if windows is in driver test mode, so I compiled him Xenos and Blackbone with my code signing certificate so he can inject with it.

**Comment by DarthTon** [comment]
Fixed in 15cee96ccf5e353d46e571ed76ff1e1e864f2150

**Comment by tekniqq** [comment]
darthton blackbone is detected  for arma battleye ban u for it any way to fix it

**Comment by DarthTon** [comment]
Rename and rewrite driver to exclude signature scans. Or hide it upon loading.

**Comment by TheDeadCode** [comment]
It is not detected. BattleEye simple bans everyone in test mode.

**Comment by tekniqq** [comment]
I wasn't in test mode

**Comment by tekniqq** [comment]
Darthon is there anyway u could help me out by making a injector for me or make something for me I pay u I don't thivk I should be contacting you this way but it's the only way sorry could I have your skype.

**Comment by DarthTon** [comment]
Sorry, but I have neither spare time nor desire to do this now. Maybe later.

**Comment by tekniqq** [comment]
darthon plz man i pay u alot

**Comment by tekniqq** [comment]
ur there man to go to ur are the owner of it

**Comment by TheDeadCode** [comment]
I suggest not pushing luck with DarthTon. You got your answer already.

**Comment by tekniqq** [comment]
sorry then but business is business if darthon wants to make money

**Comment by DarthTon** [comment]
Lol. This is not business if you haven't noticed yet.

**Comment by tekniqq** [comment]
okay then sorry

**Comment by tekniqq** [comment]
hey darthon
