### ISSUE TITLE
RemoteFunction conversion from 'const char' to 'const unsigned int' requires a narrowing conversion

### ISSUE THREAD

**Issue by 0blu** [DarthTon/Blackbone#170]
I tried to make a remote function call, but unfortunately the following code will not **Compile**.

``` cpp
#include "../Blackbone/src/BlackBone/Process/RPC/RemoteFunction.hpp"

int main()
{
	blackbone::Process p;
	p.Attach(1234);

	//Two argument = does work
	typedef char(__cdecl* add_numbers) (char number1, char number2);
	auto add_numbers_addr = p.modules().GetExport(p.modules().GetModule(L"someDll.dll"), "add_numbers");
	blackbone::RemoteFunction<add_numbers> add_numbers_function(p, (add_numbers)add_numbers_addr->procAddress);
	add_numbers_function.Call(1, 2, p.threads().getMain());
	
	//Single argument = does not work
	typedef char(__cdecl* add_one) (char number);
	auto add_one_addr = p.modules().GetExport(p.modules().GetModule(L"someDll.dll"), "addOne");
	blackbone::RemoteFunction<add_one> add_one_function(p, (add_one)add_one_addr->procAddress);
	add_one_function.Call(1, p.threads().getMain());
}
```

The compiler says that an C2397 Error occurred and ``conversion from 'const char' to 'const unsigned int' requires a narrowing conversion`` while referring to https://github.com/DarthTon/Blackbone/blob/339a686228cc29ac9a219460114b8c20d3ee988c/src/BlackBone/Process/RPC/RemoteFunction.hpp#L26

I think it has something to do with the numbers of arguments used in the typedef,
since it only occurs when <>.Call is being called.

I also tried to cast nearly everything to an ``const unsigned int`` and even tried to use
``` cpp
	decltype(add_one_function)::CallArguments args(1);
	add_one_function.Call(args, p.threads().getMain());
```

Is there a special function to call a remote function with just one argument?

Using: 339a686228cc29ac9a219460114b8c20d3ee988c

**Comment by DarthTon** [comment]
Try 85080b3f13d5247e9c21bf00da403acce1b895ff

**Comment by 0blu** [comment]
Wow, that was quick.
Thanks its working now.
