### ISSUE TITLE
memory read SYSTEM_INFORMATION_CLASS returns negative value

### ISSUE THREAD

**Issue by pushqrdx** [DarthTon/Blackbone#173]
First, i'd like to give a huge thumbs up to the dev(s), i am new to C++ but not to programming (been coding c# for ~13 years). 

I decided to move to cpp as i love hacking and i am using your project to learn both cpp and memory manipulation. 

long story short i am trying to hook NtQuerySystemInformation and hook seems to be placed correctly but when i try to read arg(0) of type `SYSTEM_INFORMATION_CLASS ` i get a negative value.

code
```
SYSTEM_INFORMATION_CLASS inf;
if (proc.memory().Read(context.getArg(0), sizeof(SYSTEM_INFORMATION_CLASS), &inf))
{
	std::wcout << inf << std::endl;
}
```

**Comment by DarthTon** [comment]
context.getArg(0) should already return SYSTEM_INFORMATION_CLASS value.

**Comment by pushqrdx** [comment]
Can you confirm this please because i just get what seems to be trash (some negative value)

**Comment by DarthTon** [comment]
Tested it with x86 and x64 taskmgr, everything works fine. Make sure process architectures are the same.
