### ISSUE TITLE
Having trouble building it

### ISSUE THREAD

**Issue by Kanga11** [DarthTon/Blackbone#174]
I'm getting tons of errors and I don't know what to do. What have I done wrong? Please help.

Using Visual Studio 2015, 10.0.15063.0, and the latest WDK is installed.

https://i.imgur.com/WjpvDV4.png

**Comment by DarthTon** [comment]
VS2017 is required. For VS2015 there is a corresponding branch available. It's frozen though.

**Comment by Kanga11** [comment]
Really, wow that's um.. Sigh. I just uninstalled VS2017 because I read somewhere VS2015 is good for driver development or something. God dammit. Thank you though, but knowing my retarded ass you'll see another thread from me in no time. I'll report back with the results. <3

**Comment by DarthTon** [comment]
VS2015 is required for blackbone driver, indeed :). I'll update driver to 2017 as soon as proper WDK comes out.

**Comment by Kanga11** [comment]
Ahem, sorry about it taking so long to re-download but that's Australian internet for you, hey. ;3
Anyways! I managed to compile Xenos and that library thing aswell with it, I'm going to pop the driver in VS2015 by itself now. Attempt #2, stand by.

**Comment by Kanga11** [comment]
HOLY SON OF A... Alrighty, wew.. it compiled. As planned of course. That was supposed to happen, mate. Thank you for the help, but as I said before, I can confirm, this will not be the last time you hear of my dumbass.
