### ISSUE TITLE
Failed to manual map driver, status: 0xC00000C0

### ISSUE THREAD

**Issue by jussihi** [DarthTon/Blackbone#176]
Injecting with DSEFix (DSE turned off) works, but why is blackbone giving me this?

**Comment by jussihi** [comment]
Seems like the program is not finding my driver at all. Do I have to do some other calls prior to 
`Driver().MMapDriver(L"mydrivername.sys");` 
to successfully load the driver?

**Comment by DarthTon** [comment]
You should provide full-qualified path.

**Comment by jussihi** [comment]
Seems like the BlackBone's own driver is not loading at all.  I have copied the BlackBoneDrv10.sys to the same dir as where my exe is. Then I use
 `Driver().EnsureLoaded(L"BlackBoneDrv10.sys");`
 but this just returns me ` 0xC0000034`

It can't find the driver? or what??

**Comment by jussihi** [comment]
oh okay, I will try and report back.

**Comment by jussihi** [comment]
`Driver().EnsureLoaded(L"C:\BlackBoneDrv10.sys");`
returns still the same `0xC0000034`

**Comment by DarthTon** [comment]
Driver().EnsureLoaded(L"C:\\BlackBoneDrv10.sys");

**Comment by jussihi** [comment]
Oh it needed to escape the \. Now it gives `0xC0000428`. Well getting there I gues...

**Comment by boris768** [comment]
see NTSTATUS values pls
https://msdn.microsoft.com/en-us/library/cc704588.aspx

**Comment by DarthTon** [comment]
Something is wrong with your driver file.

**Comment by jussihi** [comment]
No, it's the problem with the Driver file given in /src/BlackBoneDrv/bin/ ... 

It's not loading at the moment, it is giving me this error

**Comment by jussihi** [comment]
`auto status = Driver().EnsureLoaded(L"C:\\BlackBoneDrv10.sys");
	if (status == STATUS_SUCCESS)
	{
		printf("Driver handle acquired successfully, status: 0x%X \n", status);
		Sleep(10000);
	}
	else
	{
		printf("Failed to grab device handle: 0x%X \n", status);
		Sleep(30000);
		return NULL;
	}
	
	std::cout << "got past loading blackbone driver" << std::endl;`

I never get to the "got past loading.... " stuff

**Comment by jussihi** [comment]
Oh, I need to sign my blackbone driver here or enable testmode. well I guess I'll find something else!
