### ISSUE TITLE
mmap().MapImage(...) with flag HideVAD alway error VAD entry not found

### ISSUE THREAD

**Issue by ollydbgz** [DarthTon/Blackbone#178]
I'm try to use mmap().MapImage(...) with flag HideVAD but it alway show error in debug view
`BBFindVAD: VAD entry for address 0x00007FFE80580000 not found`
It's just show error but everything work

I'm try to use Driver().MmapDll(...) with flag HideVAD, It's no any error, What's wrong?
I'm working on Windows 10 x64 15063 build

**Comment by DarthTon** [comment]
Either UM part is broken or KM part is lying. I'll look into it.

**Comment by DarthTon** [comment]
fixed in f39a06ebe16560725229a8eaefc68173d4602286
