### ISSUE TITLE
Assertion Failed on Module Unlink

### ISSUE THREAD

**Issue by MaxColaPlus** [DarthTon/Blackbone#179]
Hi.

Apologies if I am missing anything really simple here but every time I try and unlink a module I get the following error:
![Error](http://i.imgur.com/k0l3Q2Q.png)

The process is open as I already hooked some other functions.

**Comment by MaxColaPlus** [comment]
Actually, this isn't fixed. I still get this issue, for reference, my dll isn't ManuallyMapped.

**Comment by DarthTon** [comment]
Ok. Please post full code that fails.

**Comment by MaxColaPlus** [comment]
Hi.

This is what we used:

	for (auto m : thisProc.modules().GetAllModules())
	{
		wstring s(m.second->name);
		wstring s2(name);

		transform(s.begin(), s.end(), s.begin(), towlower);
		transform(s2.begin(), s2.end(), s2.begin(), towlower);

		if (s.compare(s2) == 0)
		{
			thisProc.modules().Unlink(m.second);
			
			anythingChanged = true;
		}
	}

**Comment by DarthTon** [comment]
Should be fixed after 1171b5becc90dd3bfccd519c0577c5dcd0d1a4a2
