### ISSUE TITLE
Can't attach process when I use last blackbone source

### ISSUE THREAD

**Issue by ollydbgz** [DarthTon/Blackbone#181]
I'm writing injector using blackbone library. It's perfect work without problem.
But when I update blackbone library to lasted source I found some problem.
This problem break my injector It can't attach to process. **But No problem with old blackbone source.**
My target process has permission protect i know but it load and fully work after a minute, so I can fast attach when start process,

I'm trying to find line of problem and i found this, it breaking my code
```
NTSTATUS RemoteExec::CreateRPCEnvironment( WorkerThreadMode mode /*= Worker_None*/, bool bEvent /*= false*/ )
{
    DWORD thdID = GetTickCount();       // randomize thread id
    NTSTATUS status = STATUS_SUCCESS;

    //
    // Allocate environment codecave
    //
    if (!_workerCode.valid())
    {
        auto mem = _memory.Allocate( 0x1000 );
        if (!mem)
            return mem.status; // <<< return permission denied code

        _workerCode = std::move( mem.result() );
    }
```
My old blackbone source
```
NTSTATUS RemoteExec::CreateRPCEnvironment( bool bThread /*= true*/, bool bEvent /*= true*/ )
{
    DWORD thdID = GetTickCount();       // randomize thread id
    NTSTATUS status = STATUS_SUCCESS;

    //
    // Allocate environment codecave
    //
    if (!_workerCode.valid())
        _workerCode = _memory.Allocate( 0x1000 );
```
Now I move back to old blackbone source, and it work again.
I want to know what's the difference. why my old source works.
Where how can i check what different between last source and my old source.

**Comment by DarthTon** [comment]
How do attach? And where does it fail?

**Comment by ollydbgz** [comment]
```
	blackbone::Process TargetProcess;

	NTSTATUS Status = STATUS_SUCCESS;
	Status = TargetProcess.Attach(ProcessId);

	if (!NT_SUCCESS(Status)) // here fail
	{
		std::wstring Error = blackbone::Utils().GetErrorDescription(Status);
		return MessageBoxW(0, Error.c_str(), 0, 0);
	}

	blackbone::call_result_t<blackbone::ModuleDataPtr> Module = TargetProcess.mmap().MapImage(ModuleName, Flags);
	if (!Module.success())
```
I alway got error 0xc0000022 permission denied. I try to find what function return this status and i found in CreateRPCEnvironment at `auto mem = _memory.Allocate( 0x1000 );`
As I said no problem when I use old blackbone source.

**Comment by DarthTon** [comment]
Maybe old version just silently failed but the error remained there?

**Comment by ollydbgz** [comment]
Did you mean old version CreateRPCEnvironment silently succeeded but process attach() can still success, right? If so, I'll try to trace that code part again to fix my problem. Thank you.
