### ISSUE TITLE
BBApcInject not working on Windows 7 x64

### ISSUE THREAD

**Issue by CaptainBigSmoke** [DarthTon/Blackbone#182]
When injecting a dummy dll that displays some messagebox on injection (or does nothing, I know that waiting too long will make the driver run into a timeout) with BBApcInject into calc.exe on Windows 7 x64 (6.1.7601) the process immediately dies and I get the error:
BlackBone: BBApcInject: APC injection abnormal termination, status 0xC000010A
(aka STATUS_PROCESS_IS_TERMINATING).

Let me know if you need some further information.

BTW: Great job on Blackbone, if there is some bitcoin wallet or so where we can tip you some coffee let me know.

**Comment by CaptainBigSmoke** [comment]
Thanks for the quick fix, just wanted to confirm that this fixes my problem!

On a side-note unfortunately all 3 threads that calc has in my installation are gui threads but every reasonable target should have at least one thread you can hijack.

This behavior is really weird I confirmed that indeed GetMessageW returning WM_QUIT is the problem here. JD96@uc mentioned he had similar issues when he didn't properly save and restore register flags and contents do you think this could be related?

**Comment by DarthTon** [comment]
Duuno. I could be, but APC should capture and restore context by itself.
