### ISSUE TITLE
AsmVariant::Init failed

### ISSUE THREAD

**Issue by TheAifam5** [DarthTon/Blackbone#183]
**INFO**
First try throws exception. After app (Loader.exe) restart, the code belowe in section `mono_image_open_from_data` is executed but looks like the parameters are not provided. The function `mono_image_open_from_data` returns `MONO_IMAGE_IMAGE_INVALID` from the last parameter of the function.
The size and data provided as a parameters to the function `mono_image_open_from_data` are checked and are valid. Need also check if the game receiving valid parameters.

**USING COMMIT** f39a06ebe16560725229a8eaefc68173d4602286

**EXCEPTION CODE**
```cpp
// char*, const char*, char[], etc.
template<typename T>
std::enable_if_t<std::is_pointer_v<T> && std::is_same_v<cleanup_t<T>, char>>
  Init( T arg )
{
  set( dataPtr, strlen( arg ) + 1, reinterpret_cast<uint64_t>(arg) ); //exactly here
}
```

**EXCEPTION**:
`Exception thrown at 0x0F5DF1C0 (ucrtbased.dll) in UnityInjector.exe: 0xC0000005: Access violation reading location 0x14520000`

**AUTOS**: 
![autos](https://user-images.githubusercontent.com/2192274/29788492-1b39784e-8c33-11e7-8ce3-0c5ad8a4cc6d.png)

**CALLSTACK**:
![callstack](https://user-images.githubusercontent.com/2192274/29788501-21bfff1c-8c33-11e7-8cc4-f2818c9c07c6.png)

**CODE**
Example .NET DLL (all references removed, like System.Core, System etc):
```c#
namespace SCPMod
{
    public class Bootloader
    {
        public static void Load()
        {
            System.Console.WriteLine("Test");
        }

        public static void Unload()
        {

        }
    }
}
```

Loading file like:
```cpp
std::vector<char> dll_data;
{
  std::ifstream stream { dll_path, std::ios::in | std::ios::binary };
  if (stream.is_open ()) {
    std::size_t dll_size = 0;
    stream.seekg (0, std::ios_base::end);
    dll_size = stream.tellg ();
    stream.seekg (0, std::ios_base::beg);
    dll_data.reserve (dll_size);
    std::copy (std::istream_iterator<char> (stream), std::istream_iterator<char> (), std::back_inserter (dll_data));
    stream.close ();
  }
}
```

Executing `mono_image_open_from_data` function like:
```cpp
using mono_image_open_from_data_t = mono_image * (__cdecl* ) (char*, std::size_t, mono_bool, mono_image_open_status *);

auto memblock = process.memory ().Allocate (data_len, PAGE_READWRITE);
if (!memblock.success ())
  throw mono_exception (L"Call exception in 'mono_" __FUNCTIONW__"'");

if (memblock->Write (0, data_len, data) != STATUS_SUCCESS) {
  memblock->Free ();
  throw mono_exception (L"Call exception in 'mono_" __FUNCTIONW__"'");
}

mono_image_open_status open_status;
blackbone::RemoteFunction<mono_image_open_from_data_t> rpc (process, get_export ("mono_image_open_from_data")->procAddress);
auto call_result = rpc.Call (memblock->ptr<char*>(), data_len, TRUE, &open_status, process.threads ().getMain ());
if (!call_result.success () || open_status != MONO_IMAGE_OK) {
  memblock->Free ();
  throw mono_exception (L"Call exception in 'mono_" __FUNCTIONW__"'");
}

memblock->Free ();
return call_result.result ();
```

**Comment by DarthTon** [comment]
rpc expects a local string in a first argument, but you provide remote pointer. Obviously it fails to copy string for call. 

In your case this is the most suitable solution I think:
```C++
using ng mono_image_open_from_data_t = mono_image * (__cdecl* ) (uintptr_t, std::size_t, mono_bool, mono_image_open_status *);

rpc.Call (memblock->ptr<uintptr_t>(), data_len, ...
```

Also it's not required to explicitly call memblock->Free(), memblock dtor will take care of that.

**Comment by TheAifam5** [comment]
Yea but still returns the `MONO_IMAGE_IMAGE_INVALID`` error code from mono.
I seen that the first parameters points to the random place (checked with debugger).

From the stack:
![points](https://user-images.githubusercontent.com/2192274/29789993-5033dca6-8c38-11e7-996d-ea9c1e9966ca.png)

**Comment by DarthTon** [comment]
Does that value match the one you get from ptr() ?

**Comment by TheAifam5** [comment]
Yes, now after changing to `uintptr_t` is getting the valid address. So i think must be problem on my side now. :/
