### ISSUE TITLE
PsInvertedFunctionTable PatchGuard

### ISSUE THREAD

**Issue by ZhuHuiBeiShaDiao** [DarthTon/Blackbone#184]
I want to enabl SEH，but use RtlInsertInvertedFunctionTable Trigger patchguard on win10, Whether or not there is a problem?

**Comment by DarthTon** [comment]
There is. Adding entry to RtlInsertInvertedFunctionTable will tagger PG. You should find another way .

**Comment by boris768** [comment]
Use

**Comment by DarthTon** [comment]
That's x86, usermode only.

**Comment by boris768** [comment]
Does he need something else? For x64 it can be done too, but another way.

**Comment by DarthTon** [comment]
He needs it for KM in the first place.
