### ISSUE TITLE
Cannot unmap dll with thread_local variables.

### ISSUE THREAD

**Issue by mrgreywater** [DarthTon/Blackbone#188]
To reproduce:
Create a new dll project, I use x86, msvc2015 and debug build with /MTd on Windows 10 x64 Version 1703 (Build 15063.540).

Insert the following code in the main.cpp

```cpp
#include <iostream>
#include <string>
BOOL WINAPI DllMain(HINSTANCE hInstance, DWORD fdwReason, LPVOID lpReserved) {
    if (fdwReason == DLL_PROCESS_ATTACH) {
        thread_local std::string test = "Hello from dll";
        std::cout << test << std::endl;
    } else if (fdwReason == DLL_PROCESS_DETACH) {
    }
    return TRUE;
}
```

Load the dll with the MMapTest.cpp:TestMMapFromMem like so:
```cpp
auto image = thisProc.mmap().MapImage( size, buf, false, CreateLdrRef | RebaseProcess | NoDelayLoad );
//...
thisProc.mmap().UnmapAllModules();
```
It injects fine, prints the text. While unmapping the last tls callback crashes with a stackoverflow exception.

**Comment by quiret** [comment]
Isn't the TLS stuff in Blackbone a big hack anyway?

**Comment by mrgreywater** [comment]
@quiret to clarify: i'm not talking about the driver manual mapping, I'm talking about the normal usermode manual mapping.

**Comment by DarthTon** [comment]
Thread static string destructor crashes because internal lock is corrupted. Probably because it wasn't properly initialized in the first place because of makeshift static TLS init. 
Not sure I'm going to dig deeper to fix this.

**Comment by mrgreywater** [comment]
This is still not properly fixed. It still crashes but sometime later. In the TestApp you can only see the crash if you add some sleep in the main thread.

**Comment by mrgreywater** [comment]
Also notice: The dll will print
```
tls init
process attach
tls init
tls exit
process detach
```
with LoadLibrary/FreeLibrary
and print
```
tls init
process attach
tls exit
process detach
```
with blackbone

**Comment by mrgreywater** [comment]
update: the crash even occurs without thread_local after unmapping.

**Comment by luciouskami** [comment]
Try to create a new thread,then do your mmap operation.I don't know what did you do in your DLLMAIN,some opreate will lock the main thread.

**Comment by mrgreywater** [comment]
@luciouskami read the comments, i'm not doing anything in DllMain, even an empty dllmain will crash on unmap right now.

**Comment by DarthTon** [comment]
I couldn't reproduce your case. Maybe some combination of dlls with static TLS on your machine leads to this behavior.

**Comment by mrgreywater** [comment]
@DarthTon Have you tried the dll's I uploaded above (the sample project, pdb supplied if you want to check the contents)
Else I can give you remote access if you want to check out the issue on my machine.

**Comment by DarthTon** [comment]
Your binary did the the trick.
It crashes because module isn't properly removed from TLS module list and loader OS tries to copy TLS data from released module memory
```
RtlCopyMemory(TlsVector[TlsData->TlsDirectory.Characteristics],
                       (PVOID)TlsData->TlsDirectory.StartAddressOfRawData,
                       TlsDataSize);
```
I can't seem to find a way to properly uninitialize it. And I don't think it's worth all the effort.

**Comment by mrgreywater** [comment]
Well, as is, I'm not able to compile a dll with /MT /MTd with vs2015 that won't crash after unmap. I would really appreciate if this could be fixed.
