### ISSUE TITLE
Crash on manualmap right after CreateProcessW .. bad timing ?

### ISSUE THREAD

**Issue by fxfire** [DarthTon/Blackbone#19]
Hi, although we spent several days trying to debug the problem, we are not 100% sure it comes from the lib itself, but since we are out of options, I'm just asking :)
It is very hard to reproduce, on several computers everything works fine, just on specific ones (fast ones?) it caused a crash. It seems to happen only on win 8.1 x64 bit, at least we haven't seen it on any other OS.
We load the to-be-injected-dll into memory and use manual mapping to inject it into the process which was created (CreateProcessW) just a few lines before the injection takes place. We use Process.Attach() and check for Process.valid. 
- If the process.mmap().MapImage(..) injection uses the NoExceptions-Flag, everything runs fine, without that flag it crashes shortly after the dll was injected.
- Injecting "a bit later" / when the process is already fully started, also works fine (also without the noexception flag).

So to us this looks like some problem with the target process not yet being fully initialized and registering the exception handler makes it go boom.

Here is some blackbone debug output, but everything looks ok:
http://pastebin.com/8vmgH8vm

The dll's ATTACH_PROCESS gets called everytime fine, but it crashes shortly after (the dll itself does nothing, we also tried different dlls and at least 2 other programs we injected into)

Sorry for the long post, love your work & maybe you have an idea :)

**Comment by DarthTon** [comment]
Try invoking Process::EnsureInit() just before injection.

**Comment by fxfire** [comment]
I tried that already, forgot to mention it :/

**Comment by DarthTon** [comment]
Is there any chance you can provide any crash dumps of a failing process? The more the better.

**Comment by fxfire** [comment]
Thanks for the fast response, I can make some dumps + binary used, but sadly no pdb from the binary. 
datafilehost.com/d/dd0a9f4e

**Comment by fxfire** [comment]
are these dumps any help to you ? do you need more / different ones ?

**Comment by DarthTon** [comment]
This will suffice I think. Just need some time to investigate.

**Comment by DarthTon** [comment]
It turned out ntdll was ninja-patched to win10 version so all patterns went obsolete. Looks like I fixed it in 99f31a86c784b62db1a4b40b66908c1d081f64c7

**Comment by fxfire** [comment]
Sneaky MS is sneaky!
We'll test your latest commit and report back...this may take a few days though. 
Anyway big thanks for taking the time to look into it!
If there is a way (outside of git) to contact you, we would gladly donate some candy for the time you invested.

**Comment by JoshNeal68** [comment]
I'm somewhat new to using Github so I don't know what the most appropriate method of contacting you about this same issue is lol. But I see that you've modified most of the manual mapping code to fix the Windows 8.1 issue, as the ntdll.dll pretty much updated to the Windows 10 version (correct me if I'm wrong). Anyways, I'm not too sure if you've completed fixing it but what you have now has given me no luck at all with Windows 8.1. So I'm between the crossroads of thinking that the Windows 8.1 computer that I'm testing on hasn't had the super-stealth-ninja-patch, or the code just isn't complete. Don't take this the wrong way as if I'm rushing you to resolve this. I don't mean to offend you and I'm greatful that you've provided a learning experience for all in your own spare time, I would just like to better understand the issue considering I'm pretty much a scrub when it comes to Windows 8 and newer. I've used Windows 7 and older all of my life lol. Thanks in advance

**Comment by DarthTon** [comment]
Can you upload your x86 ntdll somewhere?
Also I can be contacted using this e-mail or google hangouts - DarthTon@gmail.com.

**Comment by fxfire** [comment]
I can also confirm this, it is not working for everyone running win8. I'll try to get you a ntdll and/or another crash dumb. 

Thanks again for taking the time to look into this.

**Comment by JoshNeal68** [comment]
My time zone is -6:00 and I just got home from church, so apologies for the later response. My friend is the one who uses Windows 8.1 so I will try to get him to send me the ntdll.dll

**Comment by DarthTon** [comment]
Should support both ntdll version after 251bdf0e5908f473169c32d504cac0eea917722f.

**Comment by JoshNeal68** [comment]
My friend is still saying it isn't working. But here are his files:
ntdll(system 32) - http://www.filedropper.com/ntdll

ntdll(syswow64) - http://www.filedropper.com/ntdll_1

**Comment by DarthTon** [comment]
Can you then post a few dumps after 9a3441157b1ded2c89d42c5c714409099e8ae206 commit? I'm also interested in NtLdr::ScanPatterns() tracing info.

**Comment by fxfire** [comment]
http://www.filedropper.com/ntdllsystem32
http://www.filedropper.com/ntdllsyswow64

here are two files from a system where it also didnt work (before your 251bdf0 that is).

**Comment by fxfire** [comment]
I may need a little time to test your latest commit on a computer where it crashed before, will report back once that happened.

Thanks for the help, much appreciated!

**Comment by JoshNeal68** [comment]
With the latest commit, I haven't had any issues with Windows 8.1. Thank you for the help and I will be sure to let you know of any other issues that occur

**Comment by DarthTon** [comment]
Ok. I'm closing this for now. Reopen it if you face new problems.
