### ISSUE TITLE
pattern data windows10 cu x86

### ISSUE THREAD

**Issue by residentkms** [DarthTon/Blackbone#194]
Hello.
Win10 15063.413 x86

BlackBone: PatternData: LdrpHandleTlsData32 not found
BlackBone: PatternData: LdrpInvertedFunctionTable32 not found
BlackBone: PatternData: RtlInsertInvertedFunctionTable32 not found

for  LdrpHandleTlsData working pattern is "\x50\x6a\x09\x6a\x01\x8b\xc1" (from win8.1+), but i dont know about other.

**Comment by luciouskami** [comment]
The problem may be fixed

**Comment by DarthTon** [comment]
Should be fixed as a side effect of 777281a9da59047df956b1fef5a8c562b1bd7ba3
