### ISSUE TITLE
Blackbone tutorials

### ISSUE THREAD

**Issue by 1234filip** [DarthTon/Blackbone#202]
Hello!
I want to use blackbone for a project but I don't know how to start. I want to use manual map so I can read from memory. You see I want to decrypt the dll first. Anyways is there any good tutorials on that? I know there is a test app and the xenos injector but it's really confusing to look at source code that's not commented that well. I don't get why are you mapping and exe??? Also why are you unmapping it also? Am i suposed to do that for my injector? Any help is appreciated.

**Comment by staticinvocation** [comment]
Your post is kind of ambiguous, but if you just want to read memory from kernel, all you need to do is call `MmCopyVirtualMemory` or `KeStackAttachProcess` and memcpy.  You can see an example of this in `BBCopyMemory` (https://github.com/DarthTon/Blackbone/blob/master/src/BlackBoneDrv/Routines.c#L315) .

The test app is really just a demo of all of the features of Blackbone.

**Comment by 1234filip** [comment]
I want to decrypt an encrypted file and then inject the dll from a byte array. Also why is the demo app mapping the exe file? Can you send me a simple example of how to map a dll from memory onto a process? Thanks for the response btw but I have no idea what you are talking about

**Comment by staticinvocation** [comment]
You can pass a [byte array into MapImage](https://github.com/DarthTon/Blackbone/blob/master/src/TestApp/MMapTest.cpp#L86).  Nobody here is going to do your project for you.  Just read the code & documentation.

**Comment by DarthTon** [comment]
TestMMapFromMem. Dll and exe are both PE, it doens't matter in the end.

**Comment by 1234filip** [comment]
Ok so if I understand correctly you make a Process class and attach the pid to it. You then get your byte array and map the image to the process. I just don't get why unmap the modules. Also does deleting the PE header make the injection and more stealthy?

**Comment by 1234filip** [comment]
Nvm I think you can't erase the pe header when using manual map

**Comment by 1234filip** [comment]
Ok thanks guys I'm going to close this issue now.
