### ISSUE TITLE
Windows version

### ISSUE THREAD

**Issue by FlamestoN** [DarthTon/Blackbone#204]
Hello :)

I compiled the library, and I use the manual map injection method.
In windows 10 everything works fine, but on windows 7 and 8 my program does not work, error "Failed to create activation context".

I tried xenos, and it works fine on windows 7, 8 and 10
How do I make compatibility with other versions of Windows?

OS: Windows 10
SDK: 10.0.15063.0
Visual Studio 2017 (v141)

Code:
```
void inject(DWORD pID, std::wstring dll) {
	NTSTATUS status = ERROR_SUCCESS;
	Process myProcess;

	status = myProcess.Attach(pID);
	if (!NT_SUCCESS(status))
	{
		std::cout << "Failed process access" << std::endl;
	}

	blackbone::call_result_t<blackbone::ModuleDataPtr> mod = nullptr;
	
	mod = myProcess.mmap().MapImage(dll);
	if (!mod)
	{
		std::cout << "Failed to Inject" << std::endl;
		myProcess.Detach();
		return;
	}
	myProcess.Detach();

	std::cout << "SUCCESS INJECT" << std::endl;
}
```
![1](https://user-images.githubusercontent.com/13480411/32413592-8091f4be-c225-11e7-89df-10148ded9cf2.png)
![2](https://user-images.githubusercontent.com/13480411/32413593-80b2266c-c225-11e7-94c6-1f1e95d69330.png)

**Comment by DarthTon** [comment]
What is your win7 version? Is that x86 or x64 TestApp and dll?

**Comment by FlamestoN** [comment]
My windows 7, 8 and 10 is 64 bit
TestApp, dll and injection process is 32 bit
