### ISSUE TITLE
Error 0xc000007b

### ISSUE THREAD

**Issue by RonaldHerringrrrr** [DarthTon/Blackbone#209]
I am getting an error...

{Bad Image}
%hs is either not designed to run on Windows or it contains an error. Try installing the program again using the original installation media or contact your system administrator or the software vendor for support. Error status 0x

**Comment by DarthTon** [comment]
So I guess it's indeed not a PE

**Comment by RonaldHerringrrrr** [comment]
It's a weird behavior. Sometimes it occurs and sometimes it doesn't...

**Comment by RonaldHerringrrrr** [comment]
Problem is in fact not with BlackBone, sorry...
