### ISSUE TITLE
Unresolved external symbol SHDeleteKeyW

### ISSUE THREAD

**Issue by xMuratY** [DarthTon/Blackbone#213]
VS2017 15.4.2 SDK: 10.0.16299.0

2>BlackBone.lib(DriverControl.obj) : error LNK2001: unresolved external symbol __imp__SHDeleteKeyW@8

**Comment by leftspace89** [comment]
Shlwapi.lib

**Comment by xMuratY** [comment]
i dont using driver, just i want tell. my solution is : 

SHDeleteKeyW( HKEY_LOCAL_MACHINE, (L"SYSTEM\\CurrentControlSet\\Services\\" + svcName).c_str() );

to 

//SHDeleteKeyW( HKEY_LOCAL_MACHINE, (L"SYSTEM\\CurrentControlSet\\Services\\" + svcName).c_str() );
