### ISSUE TITLE
_LdrHeapBase Sometimes NULL

### ISSUE THREAD

**Issue by leftspace89** [DarthTon/Blackbone#214]
hi, I am using blackbone 2015 version _Ldrheapbase sometimes null and inject failed.
I increased retries value 10 > 50 like new blackbone version.
I can't use blackbone 2017 because my projects too old not compatible std-latest , VC141 16299 Toolset,
my SDK version 10.0.15063.0 not support std::byte 
Any idea ? I updated Ldr Patterns for Win 10 1709 16299
 
`bool NtLdr::FindLdrHeap()
{
	
    int32_t retries = 50;
    PEB_T Peb = { 0 };
    MEMORY_BASIC_INFORMATION64 mbi = { 0 };

    _process.core().peb( &Peb );
    for (; Peb.Ldr == 0 && retries > 0; retries--, Sleep( 10 ))
        _process.core().peb( &Peb );

    if (Peb.Ldr)
    {
        auto Ldr = _process.memory().Read<PEB_LDR_DATA_T>( Peb.Ldr );
        auto NtdllEntry = CONTAINING_RECORD( Ldr.InMemoryOrderModuleList.Flink, LDR_DATA_TABLE_ENTRY_BASE_T, InMemoryOrderLinks );
        if (_process.core().native()->VirtualQueryExT( reinterpret_cast<ptr_t>(NtdllEntry), &mbi ) == STATUS_SUCCESS)
        {
            _LdrHeapBase = static_cast<uintptr_t>(mbi.AllocationBase);
            return true;
        }
    }
	
    return false;
}`

**Comment by DarthTon** [comment]
Blackbone should fall back to VirtualAllocEx if it fails to find heap. Perhaps injections fails because of something else.
