### ISSUE TITLE
Loading Driver in Windows 10 v1703

### ISSUE THREAD

**Issue by DKingCN** [DarthTon/Blackbone#218]
Before asking the question, I want to thank darthton for the sharing all these techniques. And your c++17 style is quite impressive... Tho it took me a little time...

Here cames my question:

When I tried to load drive in my Win10.v1703, it threw an error code 0xC0000428 STATUS_INVALID_IMAGE_HASH. 

I tried to solve this in some given methods, none works:
 * bcdedit.exe /set nointegritycheck on ( reboot also tried )
 * Add default WDK cert as Trusted Root
 * Re-sign by my own cert and trust
 * Remove cert on it.

WDK for 1703 is not provided in my VS2017, its only in VS2015, so I cant recompile it and see if I can fix that.

I found an announcement from MS here [Driver Signing changes in Windows 10, version 1607](https://blogs.msdn.microsoft.com/windows_hardware_certification/2016/07/26/driver-signing-changes-in-windows-10-version-1607/). 
Will it be the reason causing the error? If it is , What's the Command Name of the desired cert so I can sign one and try again.

Thanks for your time.

**Comment by DarthTon** [comment]
You can either use a test cert and enable testing mode or get yourself EV cert and do a production sign. For the latter case you don't need nointegritycheck or test mode.
Test cert can be generated from Visual Studio itself and I believe driver can be still compiled using VS 2015 and 1607 WDK.

**Comment by DKingCN** [comment]
Thank you. It's Solved.

Solution:
* Add cert as Trusted Root CA
* bcdedit.exe  /set  testsigning on
* reboot

**Comment by DKingCN** [comment]
Working beautiful. Issue closed.
