### ISSUE TITLE
compile problem

### ISSUE THREAD

**Issue by jackqk** [DarthTon/Blackbone#221]
![image](https://user-images.githubusercontent.com/7713318/34252542-0d24c190-e67f-11e7-8273-8d849dd2e9e0.png)

**Comment by DarthTon** [comment]
Obviously you have to define it now in one of the *.cpp files and replace inline with extern.

**Comment by jackqk** [comment]
老哥我是这样做的
1.把**inline** SymbolData g_symbols;改成 **extern** SymbolData g_symbols;
2.在TestApp.cpp里的开头，这样定义了：SymbolData g_symbols
结果不行，是哪里做错了吗
