### ISSUE TITLE
I moving blackbone to my project.Asmjit.h not found.

### ISSUE THREAD

**Issue by the7shfun** [DarthTon/Blackbone#222]
Here is some issues.I tried to move Blackbone to my project.First has some problem about the ../../contrib cant found. I fixed it. And today i using Blackbone function to do something. And my project missing Asmjit/Core all files.
![image](https://user-images.githubusercontent.com/13346022/34342852-90cf7a0e-e9f8-11e7-90bc-b1bd4a784b25.png)
And then try to manual to add in. But it doesnt work.Nothing show up .
I m newbie about the c++.

**Comment by the7shfun** [comment]
Solve.

**Comment by diegodp** [comment]
Could you help me with this hack?  A have no ideia how to start, just want some light
