### ISSUE TITLE
Memory write cant write 1 byte.

### ISSUE THREAD

**Issue by the7shfun** [DarthTon/Blackbone#224]
Just a little issue.Hoping blackbone more complete.
Like this
 `gameProc.memory().Write(gameModuleBase + ADRESS_PASS_WALL, 0x4C`
In the game actual memory it will write 4 byte. Like 0x4C000000 .
Hoping fix it with next version.

**Comment by DarthTon** [comment]
0x4C is and int. Cast to unsigned char explicitly.
