### ISSUE TITLE
File 'cor.h' is not found

### ISSUE THREAD

**Issue by Acidic9** [DarthTon/Blackbone#227]
I'm trying to get a basic HelloWorld Blackbone application to run. I've downloaded the Blackbone ZIP from github and extracted it into a folder in my documents.

In a new C++ windows console application in Visual Studio 2017, I have the following main document:

```cpp
#include "BlackBone/Process/Process.h"

using namespace blackbone;

int main() {
	return 0;
}
```

I added the Blackbone header files by going to `Properties -> VC++ Directories -> Include Directories` and adding `C:\Users\xxx\Documents\Blackbone-master\src` as a new path.

When I try to compile my project, I receive the following error:

> Cannot open include file: 'cor.h': No such file or directory exists.            imagenet.h

**Comment by DarthTon** [comment]
You also need to add Blackbone-master\contrib to your includes

**Comment by Acidic9** [comment]
I've added contrib to my includes as shown here:

[![Screenshot from Gyazo](https://gyazo.com/33eef10f5a09ab0f0e2831f7c215a943/raw)](https://gyazo.com/33eef10f5a09ab0f0e2831f7c215a943)

And when I run my program, I get the following 2 errors:

[![Screenshot from Gyazo](https://gyazo.com/c3bd11625d900a559d53dea7bc315e44/raw)](https://gyazo.com/c3bd11625d900a559d53dea7bc315e44)

**Comment by DarthTon** [comment]
Something went wrong with linking

**Comment by Acidic9** [comment]
Still not working... To reproduce exact what I did:

1. Download and extract the Blackbone ZIP from Github.
2. Create a new empty visual C++ project in Visual Studio 2017.
3. Create a main.cpp file in your project.
4. Go to `project properties -> VC++ Directories -> Include Directories` and add the two paths to
        `C:\Users\Arise\Documents\Programming\C++\Blackbone-master\src`
        `C:\Users\Arise\Documents\Programming\C++\Blackbone-master\contrib`
    Next go to `C/C++ -> Language -> C++ Language Standard ` and change this to `ISO C++17 Standard (/std:c++17)`.
    Hit apply and ok.
5. In your `main.cpp` file, fill it with the following code:
```cpp
#include <BlackBone/Process/Process.h>
using namespace blackbone;

int main() { return 0; }
```
6. Attempt to build, and it should show the two following errors:
````
unresolved external symbol "struct asmjit::X86RegData const asmjit::x86RegData" (?x86RegData@asmjit@@3UX86RegData@1@B)	
1 unresolved externals
````

**Comment by DarthTon** [comment]
You need to link blackbone as a lib or dll. It's not a header-only project.

**Comment by Acidic9** [comment]
Where is the lib file located?

**Comment by Acidic9** [comment]
I tried pasting every .dll file that came with the Blackbone zip into my project and still no luck.

**Comment by DarthTon** [comment]
You need to compile it.

**Comment by Acidic9** [comment]
After compiling the Visual Studio project found in Blackbone-master\src\BlackBoneDrv\BlackBoneDrv.sln for Windows 10 Debug, I am left with a .sys file. This doesn't seem right is it?

**Comment by DarthTon** [comment]
Just open BlackBone.sln and go from there...

**Comment by Acidic9** [comment]
Yep, it worked now, thank you!

**Comment by Xenotic10** [comment]
Hi, i have error with the build of blackbone
