### ISSUE TITLE
Does notify routines allowed for mapped driver ?

### ISSUE THREAD

**Issue by residentkms** [DarthTon/Blackbone#229]
Hello, does this callbacks (PsSet...NotifyRoutine) allowed for mapped driver ? Patch guard triggers with "CRITICAL_STRUCTURE_CORRUPTION", i cant understand reason.

**Comment by CaptainBigSmoke** [comment]
I experienced this problem too, what works though is changing a callback already in place to your own routine (aka hijack). Most likely there is some kind of routine that fails for manual mapped drivers invoked in these functions.

Thus you could, as a workaround, call these routines on an already existing driver and manipulate memory.

**Comment by DarthTon** [comment]
I think there are indeed some module validation checks in these callbacks routines. Related issue: https://github.com/DarthTon/Blackbone/issues/167

**Comment by residentkms** [comment]
thx
