### ISSUE TITLE
How could i build BlackBoneDrv for x86?

### ISSUE THREAD

**Issue by ganado** [DarthTon/Blackbone#23]
Hi.

In Configuration Manager, there is no option for x86 platform. 

Does BlackBoneDrv supports x86? (In the code, seems only for x64)

![image](https://cloud.githubusercontent.com/assets/1280325/7063607/15260756-dee3-11e4-9e6f-13d4f35d6b20.png)

**Comment by DarthTon** [comment]
No, it doesn't support x86.

**Comment by ganado** [comment]
Ok. Thank You.
