### ISSUE TITLE
can't load MATLAB standalone .exe file into memory and run

### ISSUE THREAD

**Issue by sampad1370** [DarthTon/Blackbone#230]
Hi to all
I want to load a MATLAB Standalone .exe file into memory and then run it.
but don't work...program is x64 and Matlab is 2016b
please help me.
thanks.

**Comment by DarthTon** [comment]
Any logs? And why on Earth would you want to run matlab from memory?

**Comment by sampad1370** [comment]
No any especial error but in your code say no relocate part and this is x64 type...
Can I have your whats app id for mor details and help?
My contact sampad.abbas1370 A t gmail.com

**Comment by sampad1370** [comment]
what does details that you needed for help me?
