### ISSUE TITLE
Any way to change folder where activation context for image is creating?

### ISSUE THREAD

**Issue by SLIpros** [DarthTon/Blackbone#234]
Hey, sorry for dumb question, but maybe there is some simple way to do that?

**Comment by DarthTon** [comment]
What do you mean by that?

**Comment by SLIpros** [comment]
On some pc, that don't have enough access rights i get such error
`Failed to create activation context for image 'C:\Users\Home\AppData\Local\Temp\Ima4DF2.tmp'. Status: 0xc0000022`
So i thought that if i can change folder where this image is create, like to local one, where exe in stored, that can fix my problem.
But adding flag NoSxS fixed all my problems.

**Comment by DarthTon** [comment]
https://github.com/DarthTon/Blackbone/blob/master/src/BlackBone/PE/PEImage.cpp#L494-L511.
It weird what you don't have access to tmp folder though

**Comment by SLIpros** [comment]
Yeah
