### ISSUE TITLE
MMap crashes on Win7 when compiled as /MT and std::mutex is used

### ISSUE THREAD

**Issue by MINIONBOTS** [DarthTon/Blackbone#235]
After 'investing' a whole day into finding out why the injection crashes the program only on W7, it turns out that using a std::mutex and compiling the dll as static ( /MT ), the ManualMap injection instantly crashes the target program. It works fine on W10. Compiling it with /MD works fine. Not using std::mutex works fine. 

Tested on W7 SP1, injecting into even notepad.exe crashes it.
Completely empty Testproject (incl compiled dll): 
[ConsoleApplication.zip](https://github.com/DarthTon/Blackbone/files/1660372/ConsoleApplication.zip)

Test Code:
`#include "stdafx.h"
#include <Windows.h>
#include <mutex>

DWORD WINAPI InitDLL(LPVOID param)
{
	std::mutex test;
	test.lock();
	test.unlock();
	MessageBox(0, L"I WORK", L"Error", MB_ICONEXCLAMATION);
	getchar();
	return 0;
}

// DLL Entry Point
int __stdcall DllMain(HMODULE hModule, size_t  ul_reason_for_call, LPVOID lpReserved) {
	switch (ul_reason_for_call)
	{
	case DLL_PROCESS_ATTACH:
		DWORD InitDLLThreadID;
		CreateThread(0, 255, InitDLL, hModule, 0, &InitDLLThreadID);
		break;
	}
	return true;
}

`
Injection details: 
Just use Xenos for injection, default MMap settings will do the job:
![acrash](https://user-images.githubusercontent.com/2842405/35340455-778e9dbc-0123-11e8-9fd3-a3248e2c98ce.png)

Thanks for checking it out <3

**Comment by MINIONBOTS** [comment]
Is there anything I can provide, logs or w/e that would help ?

**Comment by DarthTon** [comment]
Does it crash using latest blackbone directly?

**Comment by MINIONBOTS** [comment]
What do you mean with "directly" ? 
I used the most recent blackbone for the xenos injector, if that is what you asked.

**Comment by MINIONBOTS** [comment]
Btw. I did some more tests, this bug happens also when I use std::thread or std::future, so I'd say it is a bug related to threading. No pressure though, I can work around this, using Poco or boost for the thread/mutex/future etc. works completely fine in W7. I know W7 is kinda outdated and if you don't have the time or opportunity to check it out, please feel free to close the issue. But just in case others experience the same bug :)

**Comment by DarthTon** [comment]
> What do you mean with "directly" ?
I mean call mmap directly from standalone app, without Xenos.

**Comment by MINIONBOTS** [comment]
Yes, I have my own inject code, which loads the dll into memory and injects that with mmap of blackbone. This is where I originally experienced that bug, then I moved to Xenos and it had the same problem.

I do the same as Xenos though... 

`blackbone::eLoadFlags flags = NoDelayLoad | WipeHeader;
		if (img.isExe())
			flags |= blackbone::RebaseProcess;
			auto image = _process.mmap().MapImage(DLLSize, (void*)ostreamDll.str().c_str(), false, flags);`

**Comment by MINIONBOTS** [comment]
Thanks for the answer :)
