### ISSUE TITLE
Compile problem

### ISSUE THREAD

**Issue by koji1212** [DarthTon/Blackbone#236]
I'm getting this error while I'm trying to compile the driver

```
syntax error: 'type' (compiling source file Asm\AsmHelper64.cpp)
syntax error: missing ';' before '{' (compiling source file Asm\AsmHelper64.cpp)
```

Tried too look for solution with no success
Any idea?

**Comment by DarthTon** [comment]
Those files aren't even in the driver project. But anyway I don't even know what lines are those.
