### ISSUE TITLE
baypass STATUS_PARTIAL_COPY write to memory dll

### ISSUE THREAD

**Issue by DELAKEY** [DarthTon/Blackbone#237]
i need Write data to dll
 
		auto _module = proc.modules().GetModule(L"Engine.dll");
		std::wcout << L"Engine.dll" << std::endl;
		std::wcout << _module->baseAddress << std::endl;

		auto _EntitiesMP = proc.modules().GetModule(L"EntitiesMP.dll");
		auto _Engine = proc.modules().GetModule(L"Engine.dll");
		/*
		std::wcout << L"pet buf" << std::endl;
		std::wcout << adr << std::endl;*/

		ProcessMemory& mem = proc.memory();
		ptr_t base1_adr = (ptr_t)_EntitiesMP->baseAddress;

		int baseMP = 0;
		proc.memory().Read(base1_adr, baseMP);

		ptr_t autobuf_adr = (ptr_t)base1_adr + 0x1EEB80;
		std::wcout << L"Pet autobuf" << std::endl;
		std::wcout << autobuf_adr << std::endl;

		uint8_t patch[] = { 0x74};
		NTSTATUS status = proc.memory().Write(autobuf_adr, patch);
		CHECK(status == STATUS_SUCCESS);

but have error 

 FAILED:
  CHECK( status == 0 )
with expansion:
   0x8000000D == 0

0x8000000D is STATUS_PARTIAL_COPY
(Because of protection conflicts, not all the requested bytes could be copied.)

Please answer to me how to bypass memory protection?

**Comment by DarthTon** [comment]
Call mem.Protect and make memory writable

**Comment by Bonjour123** [comment]
Hi DarthTon :) Tell me, I have the same problem, and trying to call

         process.memory().Protect(address, size, PAGE_READONLY, &flOld) 

returns STATUS_NOT_COMMITTED (running as admin to be sure it's not from this).
Any idea why ?
Thanks in advance

**Comment by DarthTon** [comment]
I guess memory region is not committed, only reserved, just as error says.
