### ISSUE TITLE
So what do I do?

### ISSUE THREAD

**Issue by Vaarelsauce** [DarthTon/Blackbone#238]
Do I just download the file, extract it, open Visual Studio (Blend), select the folder, and "compile" it? Or am I missing something here? Where do I even **begin?**

Sorry, I'm new to coding, and all these jitbits are really confusing me. I'll be glad to get clarifications and helpful guidance!

**Comment by DarthTon** [comment]
Pretty much it. You clone/download as zip -> open BlackBone.sln -> build solution.
I'll add some wiki articles about getting started in the near future.
