### ISSUE TITLE
MapImage() crashes when passing a byte array

### ISSUE THREAD

**Issue by EternityX** [DarthTon/Blackbone#240]
My issue only occurs when converting a DLL into a byte array and passing that into MapImage().
Mapping a DLL by file or reading it into memory(in your example) works with no issues.

TRACE
> BlackBone: PDB: blackbone::PDBHelper::Init: (_source->loadDataForExe( file.c_str(), _sympath.empty() ? 
> nullptr : _sympath.c_str(), nullptr )) failed with HRESULT 0x806d0005
> 0000004D
> 0143A010
> BlackBone: Allocate: Allocating at address 0x1ABD0000 (0x1000 bytes)
> BlackBone: Allocate: Allocating at address 0x1ABE0000 (0x1000 bytes)
> BlackBone: Allocate: Allocating at address 0x1ABF0000 (0x4000 bytes)
> BlackBone: ManualMap: Mapping image 'MemoryImage_0x0143A010' with flags 0x0
> BlackBone: ManualMap: Loading new image 'MemoryImage_0x0143A010'
> BlackBone: ManualMap: Image base allocated at 0x0000000020e70000
> BlackBone: Allocate: Allocating at address 0x1AC20000 (0x200 bytes)
> BlackBone: ManualMap: Performing image copy
> BlackBone: ManualMap: Relocating image 'memoryimage_0x0143a010'
> BlackBone: ManualMap: Enabling exception support for image 'memoryimage_0x0143a010'
> BlackBone: ManualMap: Performing security cookie initializtion for image 'memoryimage_0x0143a010'
> BlackBone: ManualMap: Performing static TLS initialization for image 'memoryimage_0x0143a010'
> BlackBone: Allocate: Allocating at address 0x1AC30000 (0x50 bytes)

While debugging VS2017 throws 
> 0xC00001A5: An invalid exception handler routine has been detected (parameters: 0x00000003).

I call MapImage() with
>  process.mmap( ).MapImage( sizeof( hex_array ), hex_array, false, NoFlags )

I've tried multiple different DLLs and the issue still occurs.
Any help is greatly appreciated.

**Comment by pNigger** [comment]
Hey,

You've probably already found the solution to this issue but I've also encountered this issue. I found an _annoying/stupid_ fix but it works:

> char * buffer = new char[sizeof(byteArray)];
> memcpy(buffer, byteArray, sizeof(byteArray));
>auto image = process.mmap().MapImage(sizeof(byteArray), buffer, false, NoFlags);

**Comment by arcneex** [comment]
u a shtinky eternity

**Comment by EternityX** [comment]
Yep, that's how I fixed it as well.
I completely forgot about this, otherwise I would've posted my fix, sorry!

**Comment by EternityX** [comment]
A previous user who posted their fix deleted their message.
Here's how I fixed it for anyone coming across this.

```c++
void *buffer = VirtualAlloc( nullptr, dll_size, MEM_COMMIT, PAGE_READWRITE );
std::memcpy( buffer, buf, dll_size );
```
