### ISSUE TITLE
Can you send me some ntoskrnl.exe files?

### ISSUE THREAD

**Issue by isdebug** [DarthTon/Blackbone#242]
Well, I'm also doing some related projects recently, but there are too many versions of windows system. I want to collect some offset of every system version, so I would like to ask you for help. If you can, thank you. Ha ha, my email address is isdebug@qq.com

**Comment by WasserEsser** [comment]
What has this to do in an issue tracker of Blackbone?

**Comment by isdebug** [comment]
@WasserEsser emmm...It really doesn't work...
