### ISSUE TITLE
Issue with finding LdrpHandleTlsData64 in some builds of Windows 7 Professional

### ISSUE THREAD

**Issue by MrArting** [DarthTon/Blackbone#245]
Hello. I am using your library for injecting my DLL with ManualMap, and in some builds of Windows 7 Professional I have faced a crash problem. When I analyzed ExceptionAddress in the debugger, I noticed that offset of the beginning LdrpHandleTlsData64 is not -0x27, but -0x23.
![photo_2018-04-03_02-09-16](https://user-images.githubusercontent.com/19289745/38772849-083480f2-4049-11e8-80b3-00841858cf57.jpg)

So, this is my quality fix of this problem in NtLdr::AddStaticTLSEntry xD
![devenv_2018-04-15_01-44-40](https://user-images.githubusercontent.com/19289745/38773126-98ad2fee-404e-11e8-8e9d-20474ee097cf.png)

**Comment by DarthTon** [comment]
Fixed in #f654f75f2309858b9fc331f3571a57045c
