### ISSUE TITLE
Manual Map CustomArgs

### ISSUE THREAD

**Issue by vasiliyph** [DarthTon/Blackbone#252]
Hello. Problems with CustomArgs for manual map.
My code in injector:
![screenshot_1](https://user-images.githubusercontent.com/22670109/39922701-4eb36f3c-5531-11e8-9303-2af87db65578.png)

In injected dll this code:
```
std::string info;
struct ArgsBase
{
	long long size;
};

struct CustomArgs : ArgsBase
{
	std::string data;
};

BOOL APIENTRY DllMain( HMODULE hModule,
                       DWORD  ul_reason_for_call,
                       LPVOID lpReserved
					 )
{
	auto pArgs = (CustomArgs*)lpReserved;
	info = pArgs->data;
	switch (ul_reason_for_call)
	{
	case DLL_PROCESS_ATTACH:
		//hThread = CreateThread(0, 0, (LPTHREAD_START_ROUTINE)Thread, NULL, 0, 0);
	case DLL_THREAD_ATTACH:
	case DLL_THREAD_DETACH:
	case DLL_PROCESS_DETACH:
		break;
	}
	return TRUE;
}
```

But after inject dll process crash..where problem?

**Comment by L3D451R7** [comment]
Don't use std::
Use char* or char[size].

**Comment by vasiliyph** [comment]
change, but not work.
![screenshot_1](https://user-images.githubusercontent.com/22670109/40127728-2292cab0-5941-11e8-9008-67d0747242ce.png)
![screenshot_2](https://user-images.githubusercontent.com/22670109/40127729-22b43aa6-5941-11e8-938a-1715dcc5db96.png)

**Comment by DarthTon** [comment]
You still pass a raw pointer.
```
struct CustomArgs : ArgsBase
{
    char data[256];
};
```
