### ISSUE TITLE
Unlink Assembly in BlackBone VS2015

### ISSUE THREAD

**Issue by tomasekCZE** [DarthTon/Blackbone#257]
Hello, 
how to unlink assembly in BlackBone VS2015?

**Comment by DarthTon** [comment]
`ProcessModules::Unlink`

**Comment by tomasekCZE** [comment]
How to call it?
Still getting errors with getting MainModule.
![image](https://user-images.githubusercontent.com/9989670/40382362-83dcb85a-5dfe-11e8-9362-38154b5a7075.png)

**Comment by WasserEsser** [comment]
It's not a static function, you need a class object instance to call these functions.

**Comment by tomasekCZE** [comment]
How to create ClassObject Instance?


I tried create instance like this: (No work =( )
 /* 1 */ blackbone::ProcessModules* foo1 = new blackbone::ProcessModules();
  /* 2 */ blackbone::ProcessModules* foo2 = new blackbone::ProcessModules;
  /* 3 */ blackbone::ProcessModules foo3;
  /* 4 */ blackbone::ProcessModules foo4 = blackbone::ProcessModules::ProcessModules();

"no instance of constructor "blackbone::ProcessModules::ProcessModules" matches the argument list"
"no default constructor exists for class "blackbone::ProcessModules"
