### ISSUE TITLE
Can't compile project when Blackbone is included

### ISSUE THREAD

**Issue by SLIpros** [DarthTon/Blackbone#260]
Hey, it gives me bunch of errors when i include blackbone and compile my project. 
What i do wrong? Thank you for any reply.

### Errors
![2018-05-26_20-50-18](https://user-images.githubusercontent.com/6332783/40579018-7e19d732-6127-11e8-8075-29e19f88c4cd.png)

### Included Dirs:
Blackbone\src
Blackbone\contrib

### Included Libs:
Blackbone\Release

Instruments v141, SDK 10.0.16299

### My Code
```
#include "Injector.h"
#include "BlackBone/Process/Process.h"

using namespace blackbone;

void InjectorClass::Inject(MemoryStruct data)
{
	Process thisProc;
	std::vector<DWORD> dwFoundProc = thisProc.EnumByName(L"blob.exe");
	if (dwFoundProc.empty())
		return;

	thisProc.Attach(dwFoundProc[0]);
	const auto image = thisProc.mmap().MapImage(data.size, static_cast<void*>(data.memory), false, RebaseProcess | NoDelayLoad);
}
```

**Comment by DarthTon** [comment]
VS 17.7 is required to compile it starting from commit 5b8d077939355089d5c07e662b6e36dfb28aa6fa

**Comment by SLIpros** [comment]
@DarthTon switched to 17.7, same issue

**Comment by DarthTon** [comment]
Looks like you don't link with blackbone lib. Either specify it in Linker project options or add a bllackbone project to your solution and add it as a reference.

**Comment by SLIpros** [comment]
@DarthTon tryed all, same issues. This happens only when i include "BlackBone/Process/Process.h"
![2018-05-26_22-21-43](https://user-images.githubusercontent.com/6332783/40579582-8a533b9a-6133-11e8-8363-93548da9946f.png)
![2018-05-26_22-21-13](https://user-images.githubusercontent.com/6332783/40579583-8afd84c4-6133-11e8-9c3e-ce7ae5c94806.png)

**Comment by DarthTon** [comment]
No, that's just a dependency. You need this 
![image](https://user-images.githubusercontent.com/2190385/40579615-7804d218-6134-11e8-9d77-3e7873932611.png)
![image](https://user-images.githubusercontent.com/2190385/40579621-8b60ae36-6134-11e8-9730-84556dc80558.png)

**Comment by SLIpros** [comment]
@DarthTon Thanks, now all fine.
