### ISSUE TITLE
PromoteHandle no work

### ISSUE THREAD

**Issue by cancoder** [DarthTon/Blackbone#263]
bool TestAccess(DWORD pid)
{
HANDLE handle = OpenProcess(PROCESS_QUERY_LIMITED_INFORMATION, 0, pid);
add_log("handle=%x", handle);
bool res = PromoteHandle(pid, handle, PROCESS_VM_READ);
add_log("Pres=%x",res);
void * add = (void*)0x400000;
byte buf[MAX_PATH];
res = ReadProcessMemory(handle, add, buf, 8, 0);
add_log("ReadProcessMemory res=%x", res);
LogCode((byte*)buf);
return 1;
}
ReadProcessMemory res=0

**Comment by DarthTon** [comment]
For god sake
`NTSTATUS res = Driver().PromoteHandle( GetCurrentProcessId(), handle, PROCESS_VM_READ );`
