### ISSUE TITLE
tls loader implementation

### ISSUE THREAD

**Issue by adevelopcr** [DarthTon/Blackbone#269]
There is an implementation of LdrpHandleTlsData here : 
http://www.nynaeve.net/Code/VistaImplicitTls.cpp
he said that he got it from reversing ntdll tls loader

It depends on some kernel routines but I don't have any knowledge in kernel programming

can you make a user mode copy of this code to be easy to use

**Comment by DarthTon** [comment]
No. There is already minimalistic alternative to `LdrpHandleTlsData` and I'm not going to rewrite 1400 LOC.

**Comment by adevelopcr** [comment]
What do you mean with minimalistic  alternative ?
do you mean using LdrpHandleTlsData with its rva offest in ntdll ?

**Comment by DarthTon** [comment]
I mean this https://github.com/DarthTon/Blackbone/blob/master/src/BlackBone/ManualMap/Native/NtLoader.cpp#L183-L206

**Comment by adevelopcr** [comment]
simpler and works in user mode !!

I have another question 
someone said me that static tls doesn't initialize tls callbacks and I saw that blackbone supports tls callbacks with PROCESS_ATTACH/DETACH only
if this is true then my idea is to hook CreateThread and use THREAD_ATTACH reason on creating threads then wait for them and use THREAD_DETACH reason in thread termination

I know tls callbacks aren't so important but it's an idea

**Comment by DarthTon** [comment]
Yes that should work

**Comment by adevelopcr** [comment]
now I'm trying to use this alternative , as I read it works only for DllMain and I'm responsible for the other threads so I had two ideas to make it work for all threads
the problem now is it doesn't work even for the DllMain
this is what I wrote : 

`// tlsdir points to a valid IMAGE_TLS_DIRECTORY
		uintptr_t sizeOfTlData = tlsdir->EndAddressOfRawData - tlsdir->StartAddressOfRawData;
		unsigned char *tls_buffer = new unsigned char[sizeOfTlData];
		memcpy(tls_buffer,&tlsdir->StartAddressOfRawData, sizeOfTlData);
		cout << "copied tls buffer with size : 0x" << hex << sizeOfTlData << endl; // I get 0x8 , this is ok

		tlsdir->AddressOfIndex = 0; // in blackbone it's 0 so the data will be written in the start of  ThreadLocalStoragePointer however I can create and use another index which seems to be better
		
		_THREAD_BASIC_INFORMATION_T<DWORD64> tbi;
		NtQueryInformationThread(GetCurrentThread(), (THREADINFOCLASS)0, &tbi, sizeof(tbi), 0);
		uintptr_t offest = tbi.TebBaseAddress + 0x58; // ThreadLocalStoragePointer offest
		BOOL ress = WriteProcessMemory(GetCurrentProcess(), &offest, tls_buffer, sizeOfTlData, 0); // write the tls data into index 0 of ThreadLocalStoragePointer (start of it)
		if (!ress) cout << "failed with " << GetLastError() << endl;

		// executing tls callbacks , currently no callbacks

		PIMAGE_TLS_CALLBACK* callbacks = (PIMAGE_TLS_CALLBACK*)tlsdir->AddressOfCallBacks;
		if (*callbacks) {
			while (*callbacks)
			{
				(*callbacks)((void*)image, DLL_PROCESS_ATTACH, 0);
				callbacks++;
			}
		}` 

this is the tls info from dumpbin : 

Section contains the following TLS directory:

    000000018004F000 Start of raw data
    000000018004F008 End of raw data
    0000000180049250 Address of index
    0000000180033400 Address of callbacks
                   0 Size of zero fill
            00300000 Characteristics
                       4 byte align

    TLS Callbacks

          Address
          ----------------
          0000000000000000

**Comment by adevelopcr** [comment]
my first idea is to use TlsAlloc to create an index and TlsSetValue to set value (tls raw data) for the index
the assign IMAGE_TLS_DIRECTORY.AddressOfIndex to the address of new index
thus the module will receive the data was set in the index
