### ISSUE TITLE
where is the support for c++ exceptions

### ISSUE THREAD

**Issue by adevelopcr** [DarthTon/Blackbone#270]
I got seh exceptions work with RtlAddFunctionTable
but c++ exceptions doesn't work with this so I went to balckbone src and saw c++ exceptions handler resolve but it used the same function and another unexported function for 32 bit

**Comment by DarthTon** [comment]
https://github.com/DarthTon/Blackbone/blob/master/src/BlackBone/ManualMap/Native/NtLoader.cpp#L236-L342

**Comment by adevelopcr** [comment]
on 64 systems isn't RtlAddFunctionTable an alternative for RtlInsertInvertedFunctionTable ?
and why you get the address of LdrpInvertedFunctionTable structure from ntdll when you have the structure in Win8Specific.h ?
