### ISSUE TITLE
is LdrpHandleTlsData convention thiscall or stdcall on windows 8 ?

### ISSUE THREAD

**Issue by adevelopcr** [DarthTon/Blackbone#271]
I was making a unique signature for windows-es 10 , 8.1 , 8 ,7
I thought windows 10 and 8.1 use __thiscall so  I needed only one signature for both and this was true and I've already used one signature for both
then I came to ntdll <=  6.1 which is on windows 7 and used __stdcall so the signature was different so I did a signature for it
now I have two signatures , then I tested ntdll 6.2.9200.16384  which someone uploaded to me as I didn't find 64 version of it on the internet
this is ntdll on windows 8
the confusing thing is that its signature is similar to that on windows 10 , 8.1 not windows 7 so I ended with two signatures : one for windows 10 , 8.1 , 8 and one for windows 7
but in blackbone windows 8 uses __stdcall not __thiscall so is there anything wrong here ?

I read about different versions of ntdll here : 
http://www.geoffchappell.com/studies/windows/win32/ntdll/history/index.htm

and I tested ntdll x64 files from here : 
http://www.dlldownloader.com/ntdll-dll/
and https://www.dll-files.com/ntdll.dll.html 

I asked here as I couldn't try the LdrpHandleTlsData  function from custom loaded ntdll as it uses some kernel routines so ntdll loaded by the system in boot time will only work however I made sure the addresses I got are correct with the pdb files I downloaded for each dll

**Comment by adevelopcr** [comment]
this is the asm for first 200 bytes of each function :  

` ndisasm.exe -b 64 LdrpHandleTlsData10x64
00000000  48895C2410        mov [rsp+0x10],rbx
00000005  4889742418        mov [rsp+0x18],rsi
0000000A  57                push rdi
0000000B  4154              push r12
0000000D  4155              push r13
0000000F  4156              push r14
00000011  4157              push r15
00000013  4881ECD0000000    sub rsp,0xd0
0000001A  488B05837A1100    mov rax,[rel 0x117aa4]
00000021  4833C4            xor rax,rsp
00000024  48898424C8000000  mov [rsp+0xc8],rax
0000002C  48894C2448        mov [rsp+0x48],rcx
00000031  48898C2498000000  mov [rsp+0x98],rcx
00000039  33DB              xor ebx,ebx
0000003B  391D9B471000      cmp [rel 0x1047dc],ebx
00000041  741C              jz 0x5f
00000043  448D4309          lea r8d,[rbx+0x9]
00000047  4C8D4C2438        lea r9,[rsp+0x38]
0000004C  B201              mov dl,0x1
0000004E  488B4930          mov rcx,[rcx+0x30]
00000052  E84516FFFF        call 0xffffffffffff169c
00000057  4C8BF0            mov r14,rax
0000005A  4885C0            test rax,rax
0000005D  752F              jnz 0x8e
0000005F  33C0              xor eax,eax
00000061  488B8C24C8000000  mov rcx,[rsp+0xc8]
00000069  4833CC            xor rcx,rsp
0000006C  E86B4E0500        call 0x54edc
00000071  4C8D9C24D0000000  lea r11,[rsp+0xd0]
00000079  498B5B38          mov rbx,[r11+0x38]
0000007D  498B7340          mov rsi,[r11+0x40]
00000081  498BE3            mov rsp,r11
00000084  415F              pop r15
00000086  415E              pop r14
00000088  415D              pop r13
0000008A  415C              pop r12
0000008C  5F                pop rdi
0000008D  C3                ret
0000008E  65488B0425600000  mov rax,[gs:0x60]
         -00
00000097  4C8B7830          mov r15,[rax+0x30]
0000009B  4C89BC2490000000  mov [rsp+0x90],r15
000000A3  895C243C          mov [rsp+0x3c],ebx
000000A7  48899C2480000000  mov [rsp+0x80],rbx
000000AF  488BFB            mov rdi,rbx
000000B2  48895C2460        mov [rsp+0x60],rbx
000000B7  488D0D86561000    lea rcx,[rel 0x105744]
000000BE  E839D0FEFF        call 0xfffffffffffed0fc
000000C3  8B                db 0x8b
000000C4  05                db 0x05
000000C5  134710            adc eax,[rdi+0x10]`


`ndisasm.exe -b 64 LdrpHandleTlsData7x64
00000000  48894C2408        mov [rsp+0x8],rcx
00000005  53                push rbx
00000006  56                push rsi
00000007  57                push rdi
00000008  4154              push r12
0000000A  4155              push r13
0000000C  4156              push r14
0000000E  4157              push r15
00000010  4881ECA0000000    sub rsp,0xa0
00000017  488BD9            mov rbx,rcx
0000001A  833D17640F0000    cmp dword [rel 0xf6438],byte +0x0
00000021  0F84E71E0100      jz near 0x11f0e
00000027  41B809000000      mov r8d,0x9
0000002D  488D442438        lea rax,[rsp+0x38]
00000032  4889442420        mov [rsp+0x20],rax
00000037  4C8D8C24F8000000  lea r9,[rsp+0xf8]
0000003F  B201              mov dl,0x1
00000041  488B4930          mov rcx,[rcx+0x30]
00000045  E8F6CDFEFF        call 0xfffffffffffece40
0000004A  85C0              test eax,eax
0000004C  0F898DA20300      jns near 0x3a2df
00000052  33C0              xor eax,eax
00000054  4881C4A0000000    add rsp,0xa0
0000005B  415F              pop r15
0000005D  415E              pop r14
0000005F  415D              pop r13
00000061  415C              pop r12
00000063  5F                pop rdi
00000064  5E                pop rsi
00000065  5B                pop rbx
00000066  C3                ret
00000067  90                nop
00000068  90                nop
00000069  90                nop
0000006A  90                nop
0000006B  90                nop
0000006C  90                nop
0000006D  90                nop
0000006E  90                nop
0000006F  90                nop
00000070  48895C2418        mov [rsp+0x18],rbx
00000075  55                push rbp
00000076  56                push rsi
00000077  57                push rdi
00000078  4883EC30          sub rsp,byte +0x30
0000007C  33F6              xor esi,esi
0000007E  488BE9            mov rbp,rcx
00000081  488B4930          mov rcx,[rcx+0x30]
00000085  498BD8            mov rbx,r8
00000088  488D442458        lea rax,[rsp+0x58]
0000008D  488BFA            mov rdi,rdx
00000090  4C8D4C2450        lea r9,[rsp+0x50]
00000095  448D460C          lea r8d,[rsi+0xc]
00000099  B201              mov dl,0x1
0000009B  89742450          mov [rsp+0x50],esi
0000009F  4889442420        mov [rsp+0x20],rax
000000A4  E897CDFEFF        call 0xfffffffffffece40
000000A9  85C0              test eax,eax
000000AB  0F888383FCFF      js near 0xfffffffffffc8434
000000B1  488B442458        mov rax,[rsp+0x58]
000000B6  488907            mov [rdi],rax
000000B9  4885C0            test rax,rax
000000BC  0F847A83FCFF      jz near 0xfffffffffffc843c
000000C2  8B442450          mov eax,[rsp+0x50]
000000C6  48                rex.w
000000C7  89                db 0x89`


`ndisasm.exe -b 64 LdrpHandleTlsData8x64
00000000  48895C2410        mov [rsp+0x10],rbx
00000005  4889742418        mov [rsp+0x18],rsi
0000000A  57                push rdi
0000000B  4154              push r12
0000000D  4155              push r13
0000000F  4156              push r14
00000011  4157              push r15
00000013  4881ECD0000000    sub rsp,0xd0
0000001A  488B0557271100    mov rax,[rel 0x112778]
00000021  4833C4            xor rax,rsp
00000024  48898424C0000000  mov [rsp+0xc0],rax
0000002C  4C8BE9            mov r13,rcx
0000002F  48894C2450        mov [rsp+0x50],rcx
00000034  48894C2470        mov [rsp+0x70],rcx
00000039  4533F6            xor r14d,r14d
0000003C  44393541D71000    cmp [rel 0x10d784],r14d
00000043  0F8492000000      jz near 0xdb
00000049  488B7930          mov rdi,[rcx+0x30]
0000004D  458D6601          lea r12d,[r14+0x1]
00000051  418AF4            mov sil,r12b
00000054  4C89742448        mov [rsp+0x48],r14
00000059  418BDE            mov ebx,r14d
0000005C  48895C2440        mov [rsp+0x40],rbx
00000061  40F6C702          test dil,0x2
00000065  0F8585480D00      jnz near 0xd48f0
0000006B  4184FC            test r12b,dil
0000006E  0F857C480D00      jnz near 0xd48f0
00000074  4C8D4C2448        lea r9,[rsp+0x48]
00000079  4533C0            xor r8d,r8d
0000007C  488BD7            mov rdx,rdi
0000007F  418BCC            mov ecx,r12d
00000082  E8C148FEFF        call 0xfffffffffffe4948
00000087  488B4C2448        mov rcx,[rsp+0x48]
0000008C  4885C9            test rcx,rcx
0000008F  0F84A5720200      jz near 0x2733a
00000095  B80B010000        mov eax,0x10b
0000009A  66394118          cmp [rcx+0x18],ax
0000009E  0F8460480D00      jz near 0xd4904
000000A4  B80B020000        mov eax,0x20b
000000A9  66394118          cmp [rcx+0x18],ax
000000AD  0F85DC1E0700      jnz near 0x71f8f
000000B3  83B98400000009    cmp dword [rcx+0x84],byte +0x9
000000BA  760E              jna 0xca
000000BC  8B91D0000000      mov edx,[rcx+0xd0]
000000C2  85D2              test edx,edx
000000C4  0F                db 0x0f
000000C5  855172            test [rcx+0x72],edx`


I saw that the start of function on windows 8 is almost equal to it on windows 10 not 7 so I thought it's thiscall

I am not experienced in asm

**Comment by DarthTon** [comment]
As I said it doesn't matter for x64
