### ISSUE TITLE
dynData.Protection on win10 14393

### ISSUE THREAD

**Issue by thegfw** [DarthTon/Blackbone#276]
Protection offset is 0x6CA
like 15063

**Comment by jxzhxch** [comment]
on win10 x64 14393 the Protection offset is 0x6C2
![default](https://user-images.githubusercontent.com/5178662/43441710-4f165bba-94ce-11e8-8d3f-6cd48407cae9.png)

**Comment by sylingyy** [comment]
this Protect's Offset is 0x6c2 in 14393.447,after MS patch the kernel,it becomes to 0x6ca, but the mj version is also 14393.
