### ISSUE TITLE
how RunPe works without resolving imports ?

### ISSUE THREAD

**Issue by adevelopcr** [DarthTon/Blackbone#277]
how RunPe works without resolving imports ?!!

**Comment by DarthTon** [comment]
What?

**Comment by adevelopcr** [comment]
when I started running executables from memory I was using runpe and never had to resolve the imports manually
and the injection occurs after the target process is initialized and its main thread prepared  to execute so where is imports resolving
are they imported upon main thread execution ?

**Comment by DarthTon** [comment]
RunPE patches `PEB::ImageBaseAddress` before `LdrpInitializeProcess` gets to run upon resuming main thread. That function is responsible for initializing main executable module pointed to by  `PEB::ImageBaseAddress`

**Comment by adevelopcr** [comment]
then the imported modules are initialized upon main thread start , right ?

**Comment by DarthTon** [comment]
yes

**Comment by adevelopcr** [comment]
thanks
