### ISSUE TITLE
How can i get blackbone::ModuleData* from mmap().MapImage?

### ISSUE THREAD

**Issue by SLIpros** [DarthTon/Blackbone#278]
How can i get blackbone::ModuleData* from mmap().MapImage? I need it's baseAddress, size properties.
`auto image = thisProc.mmap().MapImage( size, buf, false, CreateLdrRef | RebaseProcess | NoDelayLoad );`

**Comment by DarthTon** [comment]
`image` is basically a const ModuleData*
