### ISSUE TITLE
linker warnings/errors since update? [question]

### ISSUE THREAD

**Issue by konrad1990** [DarthTon/Blackbone#28]
hello, im following your project for months now. today i tried to move to your newest version, including the last fixes/updates. i tried to compile the lastet version under MS-VS2013 update 4, including WDK, etc (as like always). im getting a huge amount of linking errors (C2011, C2027, C2039, C2059, C2065, ... up to C4430) ~ over 1300.  double checked everything, linker settings, the files, compiler settings, and so on. do i need the LLVM compiler since you added the clang support?

thanks alot!

**Comment by DarthTon** [comment]
Something is wrong with static/dynamic linking. Make sure you have BLACKBONE_STATIC define for static library (for library itself and any other project that uses it) and BLACKBONE_IMPORTS/BLACKBONE_EXPORTS for dynamic dll.

**Comment by konrad1990** [comment]
finally got it today, i messed something up in RemoteMemory, ProcessMemory. thanks for that information, anyway i think you can close that issue :+1:
