### ISSUE TITLE
why some 32 bit programs require adding their base address to the peb

### ISSUE THREAD

**Issue by adevelopcr** [DarthTon/Blackbone#280]
I noticed that some 32 bit programs need to be added to the peb in order to work correctly after manual mapping

I found that most 32 bit programs are easier to manual map and inject than 64
the don't require RtlPcToFileHeader  for the standard library to work correctly but some of them (written in delphi) require to do this : 

    _PPEB peb = (_PPEB)__readfsdword(0x30);
    peb->lpImageBaseAddress = (LPVOID)imageBase;

what is the reason of this ?
I'm testing on 64 bit windows 8.1

**Comment by DarthTon** [comment]
That is required for `GetModuleHandle(NULL)` to work

**Comment by adevelopcr** [comment]
yes I tried this was the reason !
