### ISSUE TITLE
~Thread() crashes.

### ISSUE THREAD

**Issue by LightTab2** [DarthTon/Blackbone#285]
![obraz](https://user-images.githubusercontent.com/22819912/43802962-b07d22de-9a97-11e8-91eb-7feda47d7ea5.png)
![obraz](https://user-images.githubusercontent.com/22819912/43803062-0392d5cc-9a98-11e8-9a92-59ef102c866d.png)
![obraz](https://user-images.githubusercontent.com/22819912/43803452-2c34ddda-9a99-11e8-9633-a8b758ed963c.png)

**Comment by LightTab2** [comment]
Thread: blackbone::RemoteHook::EventThreadWrap
(I was unable to do anything with remotes due that so far)

**Comment by DarthTon** [comment]
Not an actual crash, it's just VS debug helper, you can disable handling that exception in VS exception settings.

**Comment by LightTab2** [comment]
Thank you I am about to do this, however calling RemoteFunctions crashes without even signalizing the debugger (so I though it was related).

A piece of code I use:
`using namespace blackbone;

typedef void(* FnF) (DWORD, DWORD, DWORD);
RemoteFunction<FnF> rem;

void hkFunction2(RemoteContext& ctx)
{
	auto& th = ctx.getThread();
	if (th.id() != GetWindowThreadProcessId(GetForegroundWindow(), NULL)) return; //prevent looping, the function is hooked in the process where I will call it the same way.
	rem.Call(std::move(rem.MakeArguments(ctx.getArg(0), ctx.getArg(1), 0)));
}

int main()
{
auto ids = Process::EnumByName(L"notepad.exe");
	Process proc;
		proc.Attach(ids.front());
		proc.remote().CreateRPCEnvironment(Worker_None, true);
		auto address = proc.modules().GetExport(L"user32.dll", "GetMessageA")->procAddress;
		rem = MakeRemoteFunction<FnF>(proc, address);
		proc.hooks().Apply(RemoteHook::hwbp, address, &hkFunction2);

        for(;;) Sleep(200);
}
`

Am I doing something wrong?
