### ISSUE TITLE
RemoteContex::lastError() returns 183 sometimes

### ISSUE THREAD

**Issue by LightTab2** [DarthTon/Blackbone#287]
I am hooking a function remotely like this:

```cpp
using namespace blackbone;
RemoteFunction<FnF> *rem;

typedef void(* FnF) (DWORD, DWORD, DWORD);
void hkFunction(RemoteContext& ctx)
{
	rem->Call({ctx.getArg(0), ctx.getArg(1), ctx.getArg(2)});
	auto ctxerr = ctx.lastError();
	if (ctxerr != 0) throw ctxerr;
}

int main()
{
	Process proc, proc2;
	proc.Attach(Process::EnumByName(L"programme.exe").front());
	proc2.Attach(Process::EnumByName(L"programme.exe")[1]);
	proc.remote().CreateRPCEnvironment(Worker_None, true);
	rem = new RemoteFunction<FnF>(MakeRemoteFunction<FnF>(proc2, 0x4197B0)));
	proc.hooks().Apply(RemoteHook::hwbp, 0x4197B0, &hkFunction, proc.threads().getMain());
	return 0;
}
```

It calls the same function in an another process. It it called very often and I wonder if it interrupts thread or something.

So I tried to store arguments for calls in a vector, then hook in proc2 to a GetMessageA function from user32.dll and iterate through vector to call the function. Surprisingly error still persists. No harm done. What kind of error is it?

**Comment by DarthTon** [comment]
That error stands for `Cannot create a file when that file already exists.`. Probably some internal win32 function sets it for that thread.

**Comment by LightTab2** [comment]
I've should look into it and see it's an WinAPI function, then its relevant error-code before concerning you. Thanks again.
