### ISSUE TITLE
ProcessModules::GetExport fails when RemoteExec::PrepareCallAssembly is called

### ISSUE THREAD

**Issue by LightTab2** [DarthTon/Blackbone#289]
Finally my long journey to find the weird crashing bug and spamming with unrelevant issues is over (I hope). 
ProcessModule::GetNtdllExport throws access violation when calling GetExport with second parameter set to "NtSetEvent". It is very hard to reproduce since this crash happens rarely and often isn't picked up by the debugger that's why i'll post some images:

![obraz](https://user-images.githubusercontent.com/22819912/43905695-e144cef2-9bf1-11e8-8c91-0051341eb9c7.png)
![obraz](https://user-images.githubusercontent.com/22819912/43903514-e96531ee-9bec-11e8-9bac-0a1a4a56cdc5.png)
![obraz](https://user-images.githubusercontent.com/22819912/43901390-a159aee8-9be7-11e8-96a4-69aa79b787bf.png)
![obraz](https://user-images.githubusercontent.com/22819912/43910461-2928ac06-9bfd-11e8-9873-f01e9f09349f.png)
![obraz](https://user-images.githubusercontent.com/22819912/43910692-cfd6faa8-9bfd-11e8-88db-f5b9d6e6b87c.png)
![obraz](https://user-images.githubusercontent.com/22819912/43910726-e5b73842-9bfd-11e8-90ed-b9f7958ed757.png)
![obraz](https://user-images.githubusercontent.com/22819912/43910750-f9019fbe-9bfd-11e8-83fa-ad4eeb46f5da.png)
![obraz](https://user-images.githubusercontent.com/22819912/43910770-03bdbfd2-9bfe-11e8-9deb-f5aa1cf705a6.png)

**Comment by DarthTon** [comment]
Can you please generate a memory dump in VS when this happens again and attach it with debug symbols for your executable.

**Comment by LightTab2** [comment]
Here you go :)
[Uploading Dump.zip…]()

**Comment by LightTab2** [comment]
Here you go!
[Dump.zip](https://github.com/DarthTon/Blackbone/files/2275137/Dump.zip)

**Comment by DarthTon** [comment]
Try this 53bb882d7bfc8b741f8eb69cac696aa59e811d49

**Comment by LightTab2** [comment]
It always took me by surprise, so I'll need more time testing and I will tell you tomorrow if everything's okay.

**Comment by LightTab2** [comment]
You've made a typo in last commit.
hMod.baseAddress should be hMod->baseAddress

**Comment by LightTab2** [comment]
Unfortunately this doesn't solve the crashes. It is possible I am facing another issue (debugger doesn't pick it up so farr).

**Comment by LightTab2** [comment]
It is the same error. Seems like exiting function when MemBlock::Read was unsucessful is unsafe. Do you have an idea why it is detected so rarely?
[Dump.zip](https://github.com/DarthTon/Blackbone/files/2276258/Dump.zip)

**Comment by LightTab2** [comment]
Technically not a crash, however the thread's been terminated. Here's crash log from the aplication I hook into, it says exception occured on Single Step instruction at the address of function that's being hooked.
[Gist](https://gist.github.com/LightTab2/7de31d412a57f46fd6e09b7e1a161710)

**Comment by LightTab2** [comment]
I think issue #283 might be related to this one (memory corruption), the one I call `_assembler.push( 0 )` bug.

**Comment by DarthTon** [comment]
Yep, I think that could be an issue.
