### ISSUE TITLE
can not inject 64bit dll to explorer.exe (64bit)

### ISSUE THREAD

**Issue by yesme2000** [DarthTon/Blackbone#29]

**Comment by yesme2000** [comment]
64bitexe

**Comment by DarthTon** [comment]
Any logs, trace messages, error codes?

**Comment by yesme2000** [comment]
when i pull the new source, the result is ok

when i map dll twice to explorer.exe, it will restart

**Comment by DarthTon** [comment]
Why would you want to map dll twice? No wonder it crashes.
