### ISSUE TITLE
ManualMap crashes the process after 2nd injection.

### ISSUE THREAD

**Issue by jackson4800** [DarthTon/Blackbone#291]
First injection is always ok,but second injection always crashing in the begining of
`BLACKBONE_API call_result_t<exportData> ProcessModules::GetExport( const ModuleData& hMod, const char* name_ord, const wchar_t* baseModule /*= L"0"*/ )` .

**Comment by DarthTon** [comment]
I'll need at least stack trace or better crash dump + symbols for crashed exe.
