### ISSUE TITLE
Unable to write to or set memory protection via driver

### ISSUE THREAD

**Issue by mkui21** [DarthTon/Blackbone#297]
Hi,

Awesome project you got here, well done!

I downloaded and compiled it, as I wanted to see if Blackbone can write to a game process which was recently strengthened security-wise in a recent patch, now preventing any use WriteProcessMemory (used to work before patch)

So first I attempted using VirtualProtectEx to set new protection to 0x40 (read, write, execute) but that simply fails.

I then tried using the driver with the following code:

`DriverControl control;
	control.Instance();
	if(NT_SUCCESS(control.EnsureLoaded()))
		cout << "Driver loaded successfully\n";
	
	auto result1 = control.ProtectMem(processId, 0x7FF71A7E4EB7, 4, 0x40);
	if (NT_SUCCESS(result1))
		cout << "Memory protection disabled successfully\n";
	else
		cout << "Disabling memory protection failed\n";

//needed bytes to override game-memory asm with: xor eax, eax 
unsigned char buffer[4];
	buffer[0] = 49;
	buffer[1] = 192;
	buffer[2] = 144;
	buffer[3] = 144;

	auto result2 = control.WriteMem(processId, 0x7FF71A7E4EB7, 4, buffer);
	if (NT_SUCCESS(result2))
		cout << "Cheat enabled successfully\n";
	else
		cout << "Write mem failed\n";

	if (NT_SUCCESS(control.Unload()))
		cout << "Driver unloaded\n";`

But it always fails at setting the ProtectMem when I use 0x40 (it works if I pass in permission 0x20 which is what the address is already set to by default, so the call succeeds, but fails if I try to set any other permissions than the current default one).

Due to this (I assume?) the next step, actually writing to memory fails as well.

Any ideas on how to write these 4 bytes to the memory address, bypassing whatever security measure currently seeming to stop the driver from working?

Any help is very much appreciated, and thanks again for your work on this project!

Ps. The hardcoded memory address was just for testing, I wrote a different application which locates the memory address by scanning the asm for known patterns, since Cheat Engine no longer works on the game, so cant easily find the new pointers, but thats not the issue, the address was easy to find, the problem is actually writing to the address.

**Comment by mkui21** [comment]
If anyone can point me in the right direction Id be happy to PayPal 100 USD to the first person to provide me with any kind of information which ends up partly or fully helping me writing to a memory address which initially has protection: Execute|Read.

Regardless of how and using what tools.

**Comment by DarthTon** [comment]
Try IoAllocateMdl -> MmProbeAndLockPages  -> MmMapLockedPagesSpecifyCache(AccessMode=KernelMode). Don't forget to unmap and release after you done modifying it.

**Comment by mkui21** [comment]
Thank you very much for your reply.

I will try it out and see if I can get it working - if I can I will PayPal you the 100 USD as promised in my last comment.

Ill get testing.

**Comment by mkui21** [comment]
My apologizes if this is a stupid question, but I am having difficulties getting the driver to compile (I assume the API's you recommended have to be called from within a driver to be accessible?)

I have never done any driver development myself, but I have now tried both visual studio 2015 and 2017 + I have installed what I think is the correct WDK first for 2015, and when that didn't do the trick, I tried installing the WDK for VS2017.

Can anyone cast some light on exactly which frameworks/WDK including specific versions, that are needed in order to compile the driver?

I am opening the BlackBoneDrv solution containing the single project BlackBoneDrv inside it.

And when I attempt to compile it, I get the following error:
"Cannot open include file: 'ntifs.h': No such file or directory	BlackBoneDrv"


Any help is very much appreciated, thank you very much.

**Comment by mkui21** [comment]
Thank you, I got it working now and the driver compiling!

Moving on to figuring out how to use the IoAllocateMdl -> MmProbeAndLockPages -> MmMapLockedPagesSpecifyCache API's now.

**Comment by mkui21** [comment]
I have tried modifying the BBCopyMemory method now, so the write-portion of it now looks like this:
(Sorry for the terrible code and probably huge misunderstandings...)

`
// Write
        if (pCopy->write != FALSE)
        {
            pSourceProc = PsGetCurrentProcess();
            pTargetProc = pProcess;
            pSource = (PVOID)pCopy->localbuf;
            pTarget = (PVOID)pCopy->targetPtr;
			
			//MDL experiment

			PMDL allocatedMdl = IoAllocateMdl(pTarget /* Incorrect? not considering the process*/, pCopy->size, FALSE, FALSE, NULL);
			MmProbeAndLockPages(allocatedMdl, KernelMode, IoWriteAccess);
			PVOID mapped = MmMapLockedPagesSpecifyCache(allocatedMdl, KernelMode, MmCached, NULL, FALSE, NormalPagePriority);

			//Copy to target process
			memcpy(mapped, pSource, pCopy->size);
			status = STATUS_SUCCESS;

			//Cleanup
			MmUnmapLockedPages(mapped, allocatedMdl);
			IoFreeMdl(allocatedMdl);
        }
`
  
Is this somewhat the right direction?
I seem to never actually include the target process id in the mdl-stuff as I couldnt find a way to do so, thats incorrect I assume? 

Any help, suggestions or pointed out errors are very much appreciated!

Thank you.

**Comment by DarthTon** [comment]
You need to be in the context of the target process before doing MDL stuff - `KeStackAttachProcess(pTargetProc, ...)`. Wrap `MmProbeAndLockPages` in `try/catch` block and pass `UserMode` there instead of `KernelMode`. Call `MmUnlockPages` after `MmUnmapLockedPages`.

**Comment by mkui21** [comment]
Thank you very much for your corrections.

I have attempted to implement all of them now, and the complete method now looks like this:
Do you have any additional advice to complete the new write-function?

Thank you for your time.


```
  // Write
        if (pCopy->write != FALSE)
        {
            pSourceProc = PsGetCurrentProcess();
            pTargetProc = pProcess;
            pSource = (PVOID)pCopy->localbuf;
            pTarget = (PVOID)pCopy->targetPtr;
		

			// Copy pSource buffer to system space.
			
			PVOID systemBuffer = NULL;
			__try
			{
				ProbeForRead(pSource, pCopy->size, 1);
				systemBuffer = ExAllocatePoolWithTag(PagedPool, pCopy->size, BB_POOL_TAG);
				memcpy(systemBuffer, pSource, pCopy->size);
			}
			__except (EXCEPTION_EXECUTE_HANDLER)
			{
				DPRINT("BlackBone: Unable to copy to system space");

				/*if (pProcess)
					ObDereferenceObject(pProcess); 
					
					Is this Necessary? */

				return STATUS_INVALID_USER_BUFFER;
			}
						
			PRKAPC_STATE pkapcState;
			KeStackAttachProcess(pTargetProc, &pkapcState);
			PMDL allocatedMdl = IoAllocateMdl(pTarget, pCopy->size, FALSE, FALSE, NULL);
			
			__try
			{
				MmProbeAndLockPages(allocatedMdl, UserMode, IoWriteAccess);
			}
			__except (EXCEPTION_EXECUTE_HANDLER)
			{
				DPRINT("BlackBone: Unable to lock pages");
				IoFreeMdl(allocatedMdl);
				return STATUS_INTERNAL_ERROR;
			}
			
			PVOID mapped = MmMapLockedPagesSpecifyCache(allocatedMdl, KernelMode, MmCached, NULL, FALSE, NormalPagePriority);

			//Copy to target process
			memcpy(mapped, systemBuffer, pCopy->size);
			status = STATUS_SUCCESS;

			//Cleanup
			MmUnmapLockedPages(mapped, allocatedMdl);
			IoFreeMdl(allocatedMdl);
			KeUnstackDetachProcess(&pkapcState);
        }
```

**Comment by DarthTon** [comment]
You should call `ObDereferenceObject(pProcess)`  before leaving function.
Call `MmUnlockPages` after `MmUnmapLockedPages` in Cleanup section.

**Comment by mkui21** [comment]
Alright thanks again
I appreciate your patience, quite an iterative process here :)

The final "Write" method now looks like below.

By the way, is there a downside to this technique, or any other reason its not already in the driver as its main way of writing to memory, if the existing way in the driver is blocked in some games?

```
// Write
        if (pCopy->write != FALSE)
        {
            pSourceProc = PsGetCurrentProcess();
            pTargetProc = pProcess;
            pSource = (PVOID)pCopy->localbuf;
            pTarget = (PVOID)pCopy->targetPtr;
		

			// Copy pSource buffer to system space.
			
			PVOID systemBuffer = NULL;
			__try
			{
				ProbeForRead(pSource, pCopy->size, 1);
				systemBuffer = ExAllocatePoolWithTag(PagedPool, pCopy->size, BB_POOL_TAG);
				memcpy(systemBuffer, pSource, pCopy->size);
			}
			__except (EXCEPTION_EXECUTE_HANDLER)
			{
				DPRINT("BlackBone: Unable to copy to system space");

				ObDereferenceObject(pProcess);

				return STATUS_INVALID_USER_BUFFER;
			}
						
			PRKAPC_STATE pkapcState;
			KeStackAttachProcess(pTargetProc, &pkapcState);			
			PMDL allocatedMdl = IoAllocateMdl(pTarget, pCopy->size, FALSE, FALSE, NULL);
			
			__try
			{
				MmProbeAndLockPages(allocatedMdl, UserMode, IoWriteAccess);
			}
			__except (EXCEPTION_EXECUTE_HANDLER)
			{
				DPRINT("BlackBone: Unable to lock pages");
				IoFreeMdl(allocatedMdl);
				KeUnstackDetachProcess(&pkapcState);
				ObDereferenceObject(pProcess);
				return STATUS_INTERNAL_ERROR;
			}
			
			PVOID mapped = MmMapLockedPagesSpecifyCache(allocatedMdl, KernelMode, MmCached, NULL, FALSE, NormalPagePriority);

			//Copy to target process
			memcpy(mapped, systemBuffer, pCopy->size);
			status = STATUS_SUCCESS;

			//Cleanup
			MmUnmapLockedPages(mapped, allocatedMdl);
			MmUnlockPages(allocatedMdl);
			IoFreeMdl(allocatedMdl);
			KeUnstackDetachProcess(&pkapcState);
			ObDereferenceObject(pProcess);
        }
```

**Comment by DarthTon** [comment]
Looks good. The main downside is speed I guess. If that works for you I can integrate it as backup method.

**Comment by mkui21** [comment]
I tried the write-method on notepad, and it works fine there.

However when I try to use the same code on the protected game, it fails at:
MmProbeAndLockPages(allocatedMdl, UserMode, IoWriteAccess);

Unsure what the actual problem is, as I cant enable kernel mode debugging while the game is running or my computer completely freezes - but as soon as the driver calls:

MmProbeAndLockPages(allocatedMdl, UserMode, IoWriteAccess);

It throws, and ends up in the catch-block returning the error code I specified (STATUS_INTERNAL_ERROR;)

**Comment by mkui21** [comment]
Anyone know if there is a way not to use MmProbeAndLockPages or use it in a different way that may not be blocked?

**Comment by Mattiwatti** [comment]
Is it possible that the process is using AWE pages (`VadType` == `VadAwe` as a result of `MEM_PHYSICAL`)? That would certainly explain `NtProtectMemory` failing in the original attempt (if is indeed being called), since AWE pages may only be `MM_NOACCESS`, `MM_READONLY` or `MM_READWRITE`. Furthermore calling `MmProbeAndLockPages` on nonpageable memory such as AWE pages [is not allowed](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/wdm/nf-wdm-mmprobeandlockpages):
> A routine such as MmBuildMdlForNonPagedPool or IoBuildPartialMdl updates an MDL to describe pages that are either nonpageable or already locked. A call to MmProbeAndLockPages or MmUnlockPages to lock or unlock such an MDL is not allowed.

I'd advise to go back to the original code (`BBProtectMemory` to be precise) and to step through this function with a debugger. It's possible that `BBGetVadType` fails to find the VAD, because at least in older versions of Windows, there was a separate VAD root for physical allocations. I don't know if that's still the case. If `BBGetVadType` fails, I would guess that it is. If it succeeds, note the `VadType` obtained because it's important. In this case my guess is that the VAD type is somehow incompatible with RWX in `NtProtectVirtualMemory`. AWE is one possibility, but there are other more obscure ones as well.

If you are indeed dealing with AWE or other nonpaged memory, you can try this function which I wrote specifically for this purpose and uses `MmBuildMdlForNonPagedPool` as per the MSDN remark above. Note that it actually seems to work fine on regular user allocated memory as well (actually I've never encountered a target this function could not copy to), but I would at the very least `ProbeForWrite` first in that case.
```C++
NTSTATUS
RtlFuckingCopyMemory(
    _In_ PVOID Destination,
    _In_ CONST VOID* Source,
    _In_ SIZE_T Length
    )
{
    NTSTATUS Status;
    CSHORT OriginalMdlFlags = 0;
    PVOID Mapped = nullptr;

    // Allocate for the pages spanned by the MDL from nonpaged pool. MmInitializeMdl
    // is used instead of IoAllocateMdl, because the latter may return paged MDLs
    // for VAs that are not allocated from pool memory (paged or not).
    const SIZE_T MdlSize = sizeof(MDL) + sizeof(PFN_NUMBER) * ADDRESS_AND_SIZE_TO_SPAN_PAGES(Destination, Length);
    PMDL Mdl = static_cast<PMDL>(ExAllocatePoolWithTag(NonPagedPoolNx, MdlSize, ' ldM'));
    if (Mdl == nullptr)
    {
        Status = STATUS_NO_MEMORY;
        goto Exit;
    }
    RtlZeroMemory(Mdl, MdlSize);
    MmInitializeMdl(Mdl, Destination, Length);

    MmBuildMdlForNonPagedPool(Mdl);

    // Evil hack to satisfy Driver Verifier and possibly future Windows versions
    OriginalMdlFlags = Mdl->MdlFlags;
    Mdl->MdlFlags |= MDL_PAGES_LOCKED;
    Mdl->MdlFlags &= ~MDL_SOURCE_IS_NONPAGED_POOL;

    Mapped = MmMapLockedPagesSpecifyCache(Mdl,
                                        KernelMode,
                                        MmCached,
                                        nullptr,
                                        FALSE,
                                        HighPagePriority | MdlMappingNoExecute);
    if (Mapped == nullptr)
    {
        Status = STATUS_NONE_MAPPED;
        goto Exit;
    }

    RtlCopyMemory(Mapped, Source, Length);
    Status = STATUS_SUCCESS;

Exit:
    if (Mapped != nullptr)
        MmUnmapLockedPages(Mapped, Mdl);
    if (Mdl != nullptr)
    {
        Mdl->MdlFlags = OriginalMdlFlags;
        IoFreeMdl(Mdl); // Note: this will call ExFreePool
    }

    return Status;
}
```
One last note about `NtProtectVirtualMemory` is that I've seen it refuse to set pages to RWX for processes that use the 'disable dynamic code execution' mitigation policy. So check if you are dealing with that just in case - it's simply a bitflag you can toggle in the `EPROCESS`. Though disallowing dynamic code execution alone would not explain `MmProbeAndLockPages` failing, which is why I'm suspecting nonpageable memory.

**Comment by Mecanik** [comment]
If they are using callbacks, virtualprotect is useless. And you don't need to do anything with virtualprotect anyway, you can simply write to the process from kernel... and there is nothing they can do. ( or anyone in fact, thanks Microsoft )
