### ISSUE TITLE
how to manual map early after NtCreateUserProcess

### ISSUE THREAD

**Issue by adevelopcr** [DarthTon/Blackbone#304]
I'm trying to manual map my hooks after NtCreateUserProcess so that my I can prevent any attempts to detect my injector or disable remote threads or protecting the target
so I hooked the function in explorer.exe to be notified when I launch the target and inject my dll into it

so far this is my detour

`NTSTATUS HookCore::HookedNtCreateUserProcess(PHANDLE ProcessHandle, PHANDLE ThreadHandle, ACCESS_MASK ProcessDesiredAccess, ACCESS_MASK ThreadDesiredAccess, POBJECT_ATTRIBUTES ProcessObjectAttributes, POBJECT_ATTRIBUTES ThreadObjectAttributes, ULONG ProcessFlags, ULONG ThreadFlags, PRTL_USER_PROCESS_PARAMETERS ProcessParameters, void * CreateInfo, void * AttributeList)
{
	if (ProcessParameters->ImagePathName.Buffer) {
		std::wstring wms = L"launching ";
		wms += std::wstring(ProcessParameters->ImagePathName.Buffer, ProcessParameters->ImagePathName.Length / sizeof(wchar_t));
		MessageBoxW(0, wms.c_str(), L"info", 0);
	}
	NTSTATUS result = fntCreateUserProcess(ProcessHandle, ThreadHandle, ProcessDesiredAccess, ThreadDesiredAccess, ProcessObjectAttributes, ThreadObjectAttributes, ProcessFlags, ThreadFlags, ProcessParameters, CreateInfo, AttributeList);
	if (*ProcessHandle && *ThreadHandle) {
		//MessageBoxA(0, "creating injector instance", 0, 0);
		Injector injector;
		//MessageBoxA(0, "opening the dll", 0, 0);
		HANDLE hFile = CreateFileA(R"(E:\fx\Projects\idll\x64\Release\idll2.dll)", FILE_READ_ACCESS, 0, 0, OPEN_EXISTING, FILE_ATTRIBUTE_NORMAL, 0);
		if (!hFile) {
			MessageBoxA(0, "failed to open the dll", 0, 0);
			return result;
		}
		DWORD fsize = GetFileSize(hFile, 0);
		std::string size = std::string("file size : ") + std::to_string(fsize);
	//	MessageBoxA(0, size.c_str(), 0, 0);
		void *dll = HeapAlloc(GetProcessHeap(), HEAP_ZERO_MEMORY, fsize);
	//	MessageBoxA(0, "allocated the dll", 0, 0);
		ReadFile(hFile, dll, fsize, &fsize, 0);
	//	MessageBoxA(0, "read the dll", 0, 0);
		CloseHandle(hFile);
	//	MessageBoxA(0, "closed the dll", 0, 0);
		injector.setPe(dll, fsize);
		injector.attach(*ProcessHandle, 0);
	//	MessageBoxA(0, "injecting", 0, 0);
		injector.Inject();
	//	MessageBoxA(0, "injected", 0, 0);
		HeapFree(GetProcessHeap(), 0, dll);
	}
	return result;
}`

but I got some messages when executing any process saying that some entries weren't found in the module ****.exe which is the program itself so I think that there is something to initialize before manual mapping maybe the imports aren't resolved

but I tried to hook from CreateProcessW WINAPI in kernel32.dll and it worked well
this is my detour for it : 

`BOOL HookCore::HookedCreateProcess(LPCWSTR lpApplicationName, LPWSTR lpCommandLine, LPSECURITY_ATTRIBUTES lpProcessAttributes, LPSECURITY_ATTRIBUTES lpThreadAttributes, BOOL bInheritHandles, DWORD dwCreationFlags, LPVOID lpEnvironment, LPCWSTR lpCurrentDirectory, LPSTARTUPINFOW lpStartupInfo, LPPROCESS_INFORMATION lpProcessInformation)
{

	//std::wstring wms = L"launching ";
	//if (lpApplicationName) wms += std::wstring(lpApplicationName);
	//MessageBoxW(0, wms.c_str(), L"info", 0);

	bool suspended = true;
	if (!(dwCreationFlags & CREATE_SUSPENDED)) {
		suspended = false;
		dwCreationFlags |= CREATE_SUSPENDED;
	}
	BOOL result = fcreateProcessW(lpApplicationName, lpCommandLine, lpProcessAttributes, lpThreadAttributes, bInheritHandles, dwCreationFlags, lpEnvironment, lpCurrentDirectory, lpStartupInfo, lpProcessInformation);
	if (result || lpProcessInformation->dwProcessId) {
		Injector injector;
		//MessageBoxA(0, "opening the dll", 0, 0);
		HANDLE hFile = CreateFileA(R"(E:\fx\Projects\idll\x64\Release\idll2.dll)", FILE_READ_ACCESS, 0, 0, OPEN_EXISTING, FILE_ATTRIBUTE_NORMAL, 0);
		if (!hFile) {
			MessageBoxA(0, "failed to open the dll", 0, 0);
			return result;
		}
		DWORD fsize = GetFileSize(hFile, 0);
		//std::string size = std::string("file size : ") + std::to_string(fsize);
		//MessageBoxA(0, size.c_str(), 0, 0);
		void *dll = HeapAlloc(GetProcessHeap(), HEAP_ZERO_MEMORY, fsize);
		//MessageBoxA(0, "allocated the dll", 0, 0);
		ReadFile(hFile, dll, fsize, &fsize, 0);
		//MessageBoxA(0, "read the dll", 0, 0);
		CloseHandle(hFile);
		//MessageBoxA(0, "closed the dll", 0, 0);
		injector.setPe(dll, fsize);
		injector.attach(lpProcessInformation->dwProcessId);
		//MessageBoxA(0, "injecting", 0, 0);
		injector.Inject();
		//MessageBoxA(0, "injected", 0, 0);
		HeapFree(GetProcessHeap(), 0, dll);
		if (!suspended) ResumeThread(lpProcessInformation->hThread);
	}
	return result;
}`

however I don't want to be notified when CreateProcessW is used only as it can be bypassed easily by using NtCreateUserProcess

do you have any ideas about this problem ?

**Comment by DarthTon** [comment]
Most likely process doesn't get enough time to initialize. So there will be no `LDR` data and you won't be able to resolve imports.
Try executing some code in the new thread just after you call original function. BlackBone has special routine for this
https://github.com/DarthTon/Blackbone/blob/master/src/BlackBone/Process/Process.cpp#L143

**Comment by adevelopcr** [comment]
the cause of the problem was the two threads (main and new created) were running together that I had to wait until the new created thread returns before resuming the main thread
it didn't happen in all programs but only for the heavy programs that have heavy gui components
