### ISSUE TITLE
Processor Mode Switching from x86 to x64

### ISSUE THREAD

**Issue by 3LAU** [DarthTon/Blackbone#31]
This isn't really an issue more of a suggestion, but I think it is something that should be added. It would allow you to manage every process from a 32 bit process on a 64 bit os, whether the target process is  64 bit or not.

**Comment by DarthTon** [comment]
But there is such feature already: Wow64Local class.

**Comment by 3LAU** [comment]
Ah okay I see it now. I  just assumed it didn't, because it won't allow remote hooking or calling functions  from a x86 to a x64 process. Is it possible with this, because the test app says it isn't and and says "Can't execute call through WOW64 barrier, aborting".

**Comment by DarthTon** [comment]
It is a remote assembler issue. Current implementation can't generate cross-architecture code.

**Comment by 3LAU** [comment]
Ah okay I understand now. Thanks and great library!
