### ISSUE TITLE
Remove a process'es handle table

### ISSUE THREAD

**Issue by Arush-Agarampur** [DarthTon/Blackbone#312]
I'm just wondering, what happens when you remove/unlink a process's handle table? I tried it and nothing at all happened.

**Comment by DarthTon** [comment]
It should make handles opened by the target process invisible to system-wide handle enumeration functions. But AFAIK handle table is protected by KPP now and will cause BSOD if you do it.

**Comment by Arush-Agarampur** [comment]
Lol I figured that out by now 😁.

Thank you for replying anyways.
