### ISSUE TITLE
How to inject into chrome renderer

### ISSUE THREAD

**Issue by skxprive** [DarthTon/Blackbone#314]
Hi,

Does anyone know how to get into chrome's renderer process?

I've been trying for probably a week or more now to get into chrome's renderer process. 
The main process is easy, and doesn't require anything specific.

I hooked the CreateProcess to suspend the process and manually map directly after a renderer process is opened. 

It simply freezes. I tried all combinations of Flags. NoSxS NoTLS etc.

The image exception MessageBox(0, Utils::GetErrorDescription(image.status).c_str(), L"", 0);
shows things like:
"Trying to inject in a terminating process" 

So now I'm keeping just these flags and the rest is the same as the example
blackbone::eLoadFlags flags = ManualImports | CreateLdrRef | RebaseProcess;

It is Chrome version 71 btw.

**Comment by MoofMonkey** [comment]
Enable tracing, post logs here

**Comment by MoofMonkey** [comment]
And if you're using DLL - you shouldn't use RebaseProcess flag, it must be used only to mmap any exe into process (like windows native loader).

**Comment by skxprive** [comment]
I tried without that flag. It is not as easy as some might think. Chrome 70/71's new protection is serious. 

If anyone knows how to do this, please post here or mail me. I can pay for it.

**Comment by CaptainBigSmoke** [comment]
Chrome uses ControlFlowGuard to protect against arbitrary code execution. You need to remove the CFG flag from the process to run your code or the process will be automatically terminated.

**Comment by skxprive** [comment]
CaptainBigSmoke has a point there. 

But how can x64dbg for example then still debug and hook into the renderer process of chrome without disabling the ControlFlowGuard? They don't disable it systemwide and neither for the process as it seems.
