### ISSUE TITLE
How to include asmjit into a project?

### ISSUE THREAD

**Issue by 4773n0x** [DarthTon/Blackbone#318]
error LNK2001: unresolved external symbol "struct asmjit::X86RegData  const asmjit::x86RegData"

I looked here: https://github.com/DarthTon/Blackbone/issues/82
But, I'm not sure where to define ASMJIT_STATIC for it to work.

**Comment by DarthTon** [comment]
It should work without it, Just link against resulting Blakcbone.lib or make the whole project a reference.

**Comment by chenbowen9706** [comment]
u need to define BLACKBONE_IMPORTS
