### ISSUE TITLE
ProtectProcess -> STATUS_DEVICE DOES_NOT_EXIST

### ISSUE THREAD

**Issue by AHXR** [DarthTon/Blackbone#321]
Hello,

The ProtectProcess function is strangely returning **C00000C0**. According to [csdn](https://blog.csdn.net/qq1841370452/article/details/81807700), that NTSTATUS code refers to **STATUS_DEVICE DOES_NOT_EXIST**.

Everything else seems to be functional with the driver. I am allowed to write, read, manual map memory, and so forth. however the moment I arrive at this, it does not seem to work. This code is almost-literally copy+pasted from the example:

```
Process thisProc;
thisProc.Attach(GetCurrentProcessId());

auto result = Driver().ProtectProcess(GetCurrentProcessId(), Policy_Enable);
printf("%X\n", result); /// STATUS_DEVICE_DOES_NOT_EXIST 
```

Obviously, when I use isProtected after, it returns false. I tried to check the status of the driver itself for debug purposes and it returns **STATUS_NOT_FOUND**. Perhaps I'm doing something wrong?

```
printf("%X\n", Driver().status()); /// STATUS_NOT_FOUND
printf("%X\n", Driver().EnsureLoaded()); /// STATUS_OBJECT_NAME_NOT_FOUND
printf("%i\n", Driver().loaded()); /// 0
```

I would appreciate any help, love the library btw.

**Comment by DarthTon** [comment]
Your app can't load driver. Provide full path to the driver .sys to `EnsureLoaded` or put it in working directory.

**Comment by AHXR** [comment]
Perfect. Thank you so much. 

One more issue I'm having if you don't mind. I can open another issue ticket if needed. The **PromoteHandle** function doesn't seem to be working on my end, despite it returning 0.

Simple example: 
I'm using Process Hacker to retrieve the handles and process IDs. In the first attached image, we have chrome.exe, handle 0x32c and pid 8272. The handle information shows limited access (as seen in the second attached image). Changing the access level to PROCESS_ALL_ACCESS or anything else doesn't seem to work on any processes. The example provided in TestDriver isn't functional as well.

Below is the snippet from the example:
```Driver().PromoteHandle(8272, (HANDLE)0x32c, PROCESS_ALL_ACCESS);```

![processhacker_2019-01-29_10-00-35](https://user-images.githubusercontent.com/27564220/51917333-54c4aa80-23ad-11e9-8244-2e405010cb4f.png)

![processhacker_2019-01-29_10-02-07](https://user-images.githubusercontent.com/27564220/51917355-6017d600-23ad-11e9-8a40-0766afbf953e.png)

**Comment by AHXR** [comment]
Perfect. Thank you!
