### ISSUE TITLE
Does blackbone support injecting exe files

### ISSUE THREAD

**Issue by adevelopcr** [DarthTon/Blackbone#322]
I'm asking because I had problems injecting exe files linket to c++ runtime because as soon as the main function returns it terminates the target process entirely

I know that main is supposed to do this and ot does always

But isn't there any method to prevent this and save the process

I still can't compile blackbone because it doesn't support vs 2015

For more details

https://www.unknowncheats.me/forum/general-programming-and-reversing/318822-injected-exe-kills-main-process-exit.html#post2352471

**Comment by kujo2019** [comment]
"never return from main"  so in an executable I have source for I should add a forever sleep or a wait for the parent process to terminal before exiting, correct?  Any suggestions for an executable that I don't have source code for besides hex editing the binary to change the code so it never exits.   I also am assuming that cleaning up the memory and loaded modules is not possible either.
