### ISSUE TITLE
NtLoader.cpp typo lead to failure for InsertInvertedFunctionTable

### ISSUE THREAD

**Issue by hzqst** [DarthTon/Blackbone#324]
https://github.com/DarthTon/Blackbone/blob/d7713774bf90b190149cbf8fa9716bbc06651a13/src/BlackBone/ManualMap/Native/NtLoader.cpp#L283

supposed to be
```
            // If Image has SAFESEH, RtlInsertInvertedFunctionTable is enough
            if (table.Entries[i].SizeOfTable != 0 && mod.safeSEH)
                return true;
```

**Comment by DarthTon** [comment]
It's not a typo. This way module it determined to have SafeSEH which is checked in `MMap::EnableExceptions`. If `mod.safeSEH` is true, additional VEH doesn't get injected.

**Comment by hzqst** [comment]
got it
