### ISSUE TITLE
_NT_SYMBOL_PATH not work

### ISSUE THREAD

**Issue by bstaint** [DarthTon/Blackbone#325]
https://github.com/DarthTon/Blackbone/blob/8dee223515bc9777c738530f6cb0960af66bf59f/src/BlackBone/Symbols/PDBHelper.cpp#L26

MSDN：
> If the function fails, the return value is zero.

**Comment by DarthTon** [comment]
Yes, that's the purpose of that code, i.e. if there is no `NT_SYMBOL_PATH` var, store symbols in tmp location.

**Comment by bstaint** [comment]
But if set `NT_SYMBOL_PATH` var _sympath will empty.

**Comment by DarthTon** [comment]
It's fine, `NT_SYMBOL_PATH` will be used as a cache dir.

**Comment by bstaint** [comment]
OK，tks answer.
