### ISSUE TITLE
CMake Update

### ISSUE THREAD

**Issue by Rietty** [DarthTon/Blackbone#326]
In reference to #317, is there any ETA on the update of the CMake file, I don't and can't install Visual Studio on this system and am using MinGW and would like to generate and build the project for it, however CMake has multiple errors that I'm not familiar enough with to fix at the moment.

Would appreciate an update to this so I can try and play around with this.

Thanks,
Juliette

**Comment by DarthTon** [comment]
I can update CMake, but I'm not sure it'll work with MinGW without modifications. It was compatible with MinGW long ago and there were many changes since then.

**Comment by Rietty** [comment]
If you can try that would be great. I'm fairly certain I can figure out MinGW changes if there are any.

**Comment by DarthTon** [comment]
Updated in 2dafce97c0d9f47a08b927488b6a25fb0dd1de9d

**Comment by Rietty** [comment]
Thanks for the update. Configuring and generating process goes fine however when running `make`, I get quite a bit of errors including: 

1. `DriverControl.cpp: '_hDriver' not declared in this scope` in multiple locations.
2. `DriverControl.cpp: error: 'FileHandle' does not name a type; did you mean 'FileMapHandle'?`
3. `HandleGuard.h` A few errors in here.

I'm unsure if this is related to MinGW specifically? I don't think it is but any advice would be appreciated.

**Comment by DarthTon** [comment]
Those are mingw specific. I ran full CMake cycle using Visual Studio toolchain and it built flawlessly.
GCC is more strict or closer to standard than VS. 
1. It wants it to be `this-> _hDriver` I think.
2. Probably some missing `typename` specifiers.

**Comment by Rietty** [comment]
I'll take a look at it and try and figure it out. Thanks for the insight.
