### ISSUE TITLE
Using Blackbone as static library

### ISSUE THREAD

**Issue by johnwatsonoklahoma** [DarthTon/Blackbone#327]
Is there an easy way to use Blackbone as static library? I've made a copy of DLL configuration making Blackbone to compile as lib, but Samples can't be built because of `__declspec(dllimport)`. Looks like I have to use ifdef to select correct import method.

**Comment by Unc3nZureD** [comment]
According to my knowledge BlackBone is by default compiled as a static library. I can use it perfectly as a lib. Just include the corresponding header and link the lib with your exe/dll.

**Comment by DarthTon** [comment]
Default configurations (Debug/Release) are static lib.
