### ISSUE TITLE
Force manual mapping of library

### ISSUE THREAD

**Issue by Unc3nZureD** [DarthTon/Blackbone#328]
I can't find any method/flag to force manual mapping even if it's already loaded normally. _(For example if I want to manual map ntdll because the original one is already hooked heavily)_
Is it possible or source needs modification?

I tried to add an extra flag in source, but I'm still struggling, because "ProcessModules::AddManualModule" is relying on a map with the key of the filename (which is in this case not unique).

Maybe we could just skip it adding it to the _modules list, but since yet I can't have a good overview of the project I'm not sure what backdraws it is going to have. What is it affecting? What features are actively using that list?

Thanks a lot!

**Comment by DarthTon** [comment]
You need to comment out this check https://github.com/DarthTon/Blackbone/blob/master/src/BlackBone/ManualMap/MMap.cpp#L297 or add a flag to ignore it.

**Comment by Unc3nZureD** [comment]
And even this one:
https://github.com/DarthTon/Blackbone/blob/master/src/BlackBone/ManualMap/MMap.cpp#L96

If i'm right :) As soon as I'll have some time I'll compile and check if any further modifications are needed.
