### ISSUE TITLE
kernel manuelmapping issue because of blackbone::Driver().Unload(); ?

### ISSUE THREAD

**Issue by konrad1990** [DarthTon/Blackbone#33]
~~hello, sorry for thats me again, but i cant find a solution on my own with the following problem.~~

~~for some reasons i get an "APC_INDEX_MISMATCH" bluescreen (stopping at ntoskrnl.exe+xxx) if i disable the "hiding modul from the VAD list" feature while im (kernel) manualmapping inside a (x86) usermode process (on win8.1 b9600). besides that for another reason my usermode application i want to inject my image via. kernel-mm crashes if i close the GUI (injector), it reacts like a SetWindowsHookEx injection, it cant stand without the "parent process" (the injector, properly caused by the driver unload?).~~

~~the results are the same with the usermode manualmapping injection. its the frist time since i updated to the newest version of bb-library that i experienced that "issue".~~

~~you as creator of this beauty properly know whats about it - may you can give a look at it.~~

~~thanks alot!~~

my kernel manuelmapping "issue" is caused by bb-driverunloading. but since i dont get a dea why ? 
beginning at this comment:
https://github.com/DarthTon/Xenos/commit/f44474c94322141244db7952169479793bcc1992

**Comment by DarthTon** [comment]
Caused by #35
