### ISSUE TITLE
ForceRemap not working as intended

### ISSUE THREAD

**Issue by Unc3nZureD** [DarthTon/Blackbone#330]
Hello :)
I'm trying to figure out what is the exact problem, but since you have bigger experience, you might be able to find the bug easier. Given the following simplified code:

```
Process thisProc;
thisProc.Attach(GetCurrentProcessId());

auto callback = [](CallbackType /*type*/, void* /*context*/, Process& /*process*/, const ModuleData& /*modInfo*/)
{
	// Always use manual mapping
	return LoadData(MT_Manual, Ldr_None);
};

auto image = thisProc.mmap().MapImage(L"C:\\windows\\SysWOW64\\ntdll.dll", ManualImports | ForceRemap, callback);
HMODULE ntmodule = reinterpret_cast<HMODULE>(image.result()->baseAddress);

LPVOID fn_NtClose = GetProcAddress(ntmodule, "NtClose");
```

The GetProcAddress can't find anything. All I see mapped is a single page with RW protection, where only the partial exe is copied.

Thanks for any help :)

**Comment by DarthTon** [comment]
Native `GetProcAddress` won't find anything because module is not in any loader list. Use `ProcessModules::GetExport` instead

**Comment by Unc3nZureD** [comment]
Wow, interesting, I've always thought that GetProcAddress does always iterate the IAT, which would work on any mapped PE.
