### ISSUE TITLE
MmCopyVirtualMemory - KPROCESSOR_MODE ?

### ISSUE THREAD

**Issue by Mecanik** [DarthTon/Blackbone#333]
Stupid question here... but I cannot find any documentation on MmCopyVirtualMemory. Inside BlackBone the MmCopyVirtualMemory  is set to use KernelMode.

From my testing, writing to a user process with MmCopyVirtualMemory and KernelMode/UserMode result in the same thing.

What is the difference if I were to use KernelMode or UserMode as "previous" mode ?

Appreciate any explanation, thanks.

**Comment by DarthTon** [comment]
In `UserMode` function does additional validation of UM addresses.

**Comment by Mecanik** [comment]
Interesting, thanks. So that would be all ?

The main reason I'm asking is because I'm writing in another process memory, and I don't want to have any "leaks" that can be detected.

**Comment by DarthTon** [comment]
That's all
