### ISSUE TITLE
Driver Initialization fault with 10.0.17134.0.590

### ISSUE THREAD

**Issue by DavidHausler** [DarthTon/Blackbone#336]
It seems that offset for PTE table is off for me. As a result, driver won't start. I was considering disabling the check, to at least get it to start, however that is not the right solution. 

BlackBone: OS version 10.0.17134.0.590 - 0xa00
BlackBone: PDE_BASE: 8B4900000001BAFF, PTE_BASE: 0000000000000000
BlackBone: Invalid PDE/PTE base, aborting

Would you kindly share the secret of finding the values for these offsets? In case they change again in the future.. I already have IDA, however, i'm failing to find the correct values.

Thank you very much.

**Comment by DarthTon** [comment]
I plan to rewrite that part without relying on pattern matching, it's getting out of hand.

**Comment by DKingCN** [comment]
Failed on my 10.0.17134.0.648 as the same reason.

After a quick search on PDE/PTE dependencies, I think most mmap functions will not work without it.

Bro I am counting on this fix/rewrite. ♥u

**Comment by DarthTon** [comment]
It should already work since e66dde8bd668be2acdbdde5cc11c31da8ba1933b

**Comment by DKingCN** [comment]
Oh i missed the latest commits. thank you.
