### ISSUE TITLE
Noobish question

### ISSUE THREAD

**Issue by Zeta314** [DarthTon/Blackbone#338]
Hey man I can't figure out how to include your library in my project. That's a pretty noobish question but if you could help me, it would be appreciated!

**Comment by Mecanik** [comment]
With all the respect, I don't think this library is for you if you can't include it.

Don't get me wrong...

**Comment by Zeta314** [comment]
Alright, then. Keep your secrets.

**Comment by Mecanik** [comment]
What secrets ? There's no secret, just the fact that this library is above your league.

Let me guess... you want to make a "cheetah", to cheat in a game.

To make it clear for you, this library is not spoon feeding anything and it wont magically bypass anticheat engines so you can cheat...

Only condoning in this conversation is a waste of my time so I will give you one final advice: learn and gain experience.

**Comment by Zeta314** [comment]
I'm sorry I bothered you with this. I hope you'll enjoy your time.
Bye
