### ISSUE TITLE
[question] how to setup properly this lib?

### ISSUE THREAD

**Issue by encoree1337** [DarthTon/Blackbone#34]
hi, I tried to use blackbone in my project - but I cannot compile any projects with it - I keep receiving errors as I include files - first, I'm receiving error that let's say enum x is undefined - fine, I include one more file, and then... 1940 (that's real number) errors show up, that x is undefined, y is wrong size, bla bla bla, I can't even compile test app, I don't know what's wrong, I'm using visual studio 2013 ultimate. Can you help me in any way?

**Comment by DarthTon** [comment]
Try including only "Process.h" and make sure you have lib file referenced. Also for static linking BLACKBONE_STATIC must be defined for preprocessor.

**Comment by spinninglock** [comment]
I usually have to disable security checks as well - then usually works fine

**Comment by DarthTon** [comment]
So have you managed to build it?

**Comment by encoree1337** [comment]
Sorry for not responding, but I simply gave up and forgot about this lib & thread xD
I switched to windows 10 and downloaded vs 2015, and it works fine, just perfectly :dancer: 
Although test app included in github doesnt work in win10, but it's ok - it's nothing new, that win7/8 code crashes on win10, had same issue with hack. Anyways, I managed to build it properly just via opening solution, I think something was wrong with my vs configuration.
