### ISSUE TITLE
which size to copy of section VirtualSize or SizeOfRawData

### ISSUE THREAD

**Issue by cppdev-123** [DarthTon/Blackbone#340]
I faced a strange problem while mapping a debug build of a dll
the problem was coming from VirtualProtect with error INVALID_PARAMETER_3 while protecting the section .textbss with PAGE_EXECUTE_READWRITE protection
after some time I knew that the size of the section SizeOfRawData is 0 !
after reading on microsoft pe specification they said that this means that the section had no initialized data and in this state only the VirtualSize holds the size
also they said that VirtualSize always holds a size equal to SizeOfRawData or bigger because the latter is rounded

so I made VirtualProtect use VirsualSize instead

but while copying the sections if I find a section with SizeOfRawData = 0 should I ignore the section or copy it with the VirtualSize

and does SizeOfImage in the optional header includes the uninitialized data ?

this is currently what I'm doing : 

    NTSTATUS nt_result;
	image = (uint8_t*)allocate_memory(nt->OptionalHeader.SizeOfImage, PAGE_READWRITE, MEM_COMMIT | MEM_RESERVE, nt_result);
	if (!image)
	{
        #ifdef _DEBUG
		cout << "[!] failed to allocate memory for '" << libpath << "' with error : " << hex << nt_result << dec << endl;
        #endif // _DEBUG
		return nullptr;
	}
	// copy the headers
	memcpy(image, lib_buffer, nt->OptionalHeader.SizeOfHeaders);
        
	// copy the sections and store proper protection flags
	PIMAGE_SECTION_HEADER sections = IMAGE_FIRST_SECTION(nt);
	for (int i = 0; i < nt->FileHeader.NumberOfSections; i++) {
		memcpy((void*)(image + sections[i].VirtualAddress),
			(const void*)((uintptr_t)lib_buffer + sections[i].PointerToRawData),
			sections[i].SizeOfRawData ? sections[i].SizeOfRawData : sections[i].Misc.VirtualSize);

		DWORD chr = sections[i].Characteristics;
		if (chr & IMAGE_SCN_CNT_CODE || chr & IMAGE_SCN_MEM_EXECUTE) {
			old[i] = PAGE_EXECUTE;
			if (chr & IMAGE_SCN_MEM_WRITE) old[i] = PAGE_EXECUTE_READWRITE;
			else if (chr & IMAGE_SCN_MEM_READ) old[i] = PAGE_EXECUTE_READ;
		}
		else if (chr & IMAGE_SCN_MEM_WRITE) old[i] = PAGE_READWRITE;
		else if (chr & IMAGE_SCN_MEM_READ) old[i] = PAGE_READONLY;
		else old[i] = PAGE_READWRITE;
	}
        
	// restore dos and nt to point to the new image
	dos = (PIMAGE_DOS_HEADER)image;
	nt = (PIMAGE_NT_HEADERS)(image + dos->e_lfanew);
	sections = IMAGE_FIRST_SECTION(nt);
        
then later : 
        
        // restore the protections of sections
	for (int i = 0; i < nt->FileHeader.NumberOfSections; ++i) {
		if (sections[i].Characteristics & IMAGE_SCN_MEM_DISCARDABLE)
		{
			RtlSecureZeroMemory((void*)(image + sections[i].VirtualAddress), sections[i].SizeOfRawData);
			VirtualFree(image + sections[i].VirtualAddress, sections[i].Misc.VirtualSize, MEM_DECOMMIT);
		}

		NTSTATUS res = protect_memory((image + sections[i].VirtualAddress), sections[i].SizeOfRawData ? sections[i].SizeOfRawData : sections[i].Misc.VirtualSize old[i]);
		if (!NT_SUCCESS(res))
		{
        #ifdef _DEBUG
			cout << "[!] failed to apply the proper protection (" << prot_flag_to_str(old[i]) << ") for " << get_section_name((char*)sections[i].Name) << " with size " << sections[i].SizeOfRawData << " , error " << hex << res << dec << endl;
        #endif // _DEBUG
			VirtualFree(image, 0, MEM_RELEASE);
			return nullptr;
		}
	}

**Comment by DarthTon** [comment]
Don't copy anything if `SizeOfRawData` is 0. You can have 2 sections with same `PointerToRawData` and if you copy any data, you risk having invalid initial state for the first of those 2 sections.
`SizeOfImage` includes `VirtualSize` each section, even if `SizeOfRawData` is 0.

**Comment by cppdev-123** [comment]
So I should use 'SizeOfRawData' in memcpy and 'VirtualSize' in Virtual Memory functions ?
I looked at blackbone source code and found that it's doing so in MMap.cpp MMap::CopyImage , MMap::ProtectImageMemory and in wipeMemory lambda

**Comment by DarthTon** [comment]
Yes
