### ISSUE TITLE
HandleGuard is better to check if > 0

### ISSUE THREAD

**Issue by cppdev-123** [DarthTon/Blackbone#341]
Valid windows handles shouldn't be zero or INVALID_HANDLE_VALUE except the pseudo handle -1 for the current process and thread
so why not only checking in the HandleGuard if the member handle is greater than 0 ?
also this would allow using the Handle with GetCurrentProcess and GetCurrentThread without trying to clean it instead of using FileHandle which makes some confusion

**Comment by DarthTon** [comment]
Makes sense

**Comment by DarthTon** [comment]
Can't close yet, need to handle handle validation.
