### ISSUE TITLE
SetProtection not working on Win7

### ISSUE THREAD

**Issue by 1478450488** [DarthTon/Blackbone#344]
The Setprotection Function is working on win10 (Test on 17134)
but when i test it on win7 
i can simply use taskmanager to close 
It's not working..

**Comment by 1478450488** [comment]
tring to find offset myself
can you pls share how to find those offset？
for the protection and eprocessflag2
i tried to find it on windbg but it shows me that the offset of protection in eprocess is 0x406 
（win10 17134）

**Comment by DarthTon** [comment]
It works. But for some reason protection doesn't block PROCESS_TERMINATE access any more.
