### ISSUE TITLE
Compile errors in HandleGuard

### ISSUE THREAD

**Issue by Scui1** [DarthTon/Blackbone#346]
Hello,
I just discovered this project and it seems pretty nice. I downloaded it and opened the project. I only adjusted the windows sdk version and that's it. I wasn't able to compile:
![cantcompileblackbone](https://user-images.githubusercontent.com/47137823/57093720-ef1aee00-6d0e-11e9-9c75-6d46d9ed149f.png)
: http://prntscr.com/njlhk1

**Comment by DarthTon** [comment]
Make sure you have Visual Studio 2017 15.7 or higher

**Comment by Scui1** [comment]
> 
> 
> Make sure you have Visual Studio 2017 15.7 or higher

Oh sry didn't know that could cause a problem. I will update and report here if it worked, which I guess it will. Thanks for the reply.

**Comment by Scui1** [comment]
Worked as intended, thanks for your help.
