### ISSUE TITLE
How to remove the blackbone driver 

### ISSUE THREAD

**Issue by kirztknew22** [DarthTon/Blackbone#348]
How to remove the blackbone driver after kernel manual map ?

**Comment by DarthTon** [comment]
Driver().Unload()

**Comment by kirztknew22** [comment]
Can you explain it more explicitly ?

**Comment by kirztknew22** [comment]
And does this driver appear in driverquery ?

**Comment by kirztknew22** [comment]
And what if i remove the injector ? Will the driver be unloaded ?

**Comment by DarthTon** [comment]
Either unload it programmatically via user-mode API I mentioned or do it manually. It's a generic driver service, you can stop and delete windows service `BlackBone` - `HKEY_LOCAL_MACHINE\System\CurrentControlSet\Services\BlackBone`. Xenos should unload drive upon exit according to this https://github.com/DarthTon/Xenos/blob/master/src/InjectionCore.cpp#L23, but I remember there were some issue with automatic unloading, it's better to double check.

**Comment by kirztknew22** [comment]
sc.exe delete <blackbone service> ?

**Comment by kirztknew22** [comment]
So if there is no blackbone is current control set , the driver is removed right ?

**Comment by DarthTon** [comment]
Yes
