### ISSUE TITLE
BBUnlinkHandleTable Question 

### ISSUE THREAD

**Issue by kitty8904** [DarthTon/Blackbone#351]
Is the BBUnlinkHandleTable function not detected by the patch guard

Do you have patchguard generated code during Black bone function?

Can I generate 109 patchguards somewhere in the Blackboard kernel function
(1HR~3HR BSOD)

**Comment by DarthTon** [comment]
BBUnlinkHandleTable  should be triggering PG since RS2/RS3 Win10 update I think.

**Comment by kitty8904** [comment]
> BBUnlinkHandleTable should be triggering PG since RS2/RS3 Win10 update I think.

Should I get a patch guard bypass?

Are there any sources that you should reference separately without bypassing the patchguard?

============================================================

Or is it unusable on a regular OS since Redstone 3?
