### ISSUE TITLE
compile error on vs 2019

### ISSUE THREAD

**Issue by luciouskami** [DarthTon/Blackbone#352]
on file MMap.cpp
line:1414
std::remove_reference<decltype(OriginalName)>::type DllName1 = { 0 };
should be
typename std::remove_reference<decltype(OriginalName)>::type DllName1 = { 0 };
see
https://docs.microsoft.com/en-us/cpp/overview/cpp-conformance-improvements?view=vs-2019

**Comment by denizdeni** [comment]
change c++ language standard to c++17

**Comment by luciouskami** [comment]
> change c++ language standard to c++17

the "C++" ISO does not care.it  should be improved

**Comment by qY5qL7eNkM** [comment]
same issue. how to fix this?

**Comment by luciouskami** [comment]
> same issue. I have 87 errors. how to fix this?

Read the first post i 've post，it would be fixed
