### ISSUE TITLE
Can't build the project

### ISSUE THREAD

**Issue by karliky** [DarthTon/Blackbone#36]
Hi All

I downloaded the entire repo and used Visual Studio 2013 to build the project, but I can't because of this error:

`Error	3	error C1083: Cannot open include file: 'atlbase.h': No such file or directory`

Are there any build instructions out there?

Thanks in advance

**Comment by Maktm** [comment]
Get the header file and include it?

**Comment by DarthTon** [comment]
It seems something is wrong with your VS installation or include directories. 'atlbase.h' is a core ATL  include file.

**Comment by karliky** [comment]
Which version are you using of VS? I'm using Visual Studio 2013 Express.

**Comment by DarthTon** [comment]
VS 2013 pro with WDK 8.1.

**Comment by karliky** [comment]
Well, the project can be build perfectly using VS 2013 pro, so it doesn't work with VS 2013 Express....


Thank you so much! I'm going to close this.
