### ISSUE TITLE
Bypass ProcessDynamicCodePolicy mitigation policy flagged processes.

### ISSUE THREAD

**Issue by iradization** [DarthTon/Blackbone#361]
Unprotected processes may set the ProcessDynamicCodePolicy flag on, what prevents even driver permission code from allocate new executable memory on their virtual memory space.

I guess that the intention was that no user-space program may alter this settings, but there must be a way from driver to avoid this bit, since it has more privileges.

I know that there are methods to detect mitigation policy flags such as `NtQueryInformationProcess` and set them using `SetProcessMitigationPolicy()` as I saw in processHacker and this project, but they all uses undocumented structures that may change between windows versions.

So I wonder if there's an alternative way to disable this mitigation from driver...
Is there any alternative robust way to avert this bit from driver once process has started, or allocate the memory for injected code before this policy is being enforced assuming the driver gets process notification using `PsSetCreateProcessNotifyRoutine`?

thanks

**Comment by Mecanik** [comment]
You need to search and read... https://m.habr.com/ru/post/358650/

**Comment by DarthTon** [comment]
All `SetProcessMitigationPolicy` does is it flips corresponding bits in EProcess structure. It doesn't even use any locks IIRC.
You can try your approach with process startup. But I don't know when exactly policy is applied. And you may have troubles allocating memory in `PsSetCreateProcessNotifyRoutine` notification.
