### ISSUE TITLE
BSOD KERNEL_SECURITY_CHECK_FAILURE

### ISSUE THREAD

**Issue by alxbrn** [DarthTon/Blackbone#364]
I saw a few other issues talking about this issue, but I wasn't able to come to a conclusion.

Whenever I load the blackbone driver with something like kdmapper or drvloader I get a BSOD with status: KERNEL_SECURITY_CHECK_FAILURE, but it works fine when using sc start.

WinDbg log:
```
*** Fatal System Error: 0x00000139
                       (0x0000000000000006,0xFFFFEB0189F8F8B0,0xFFFFEB0189F8F808,0x0000000000000000)

Break instruction exception - code 80000003 (first chance)
nt_fffff8070e0b4000!DbgBreakPointWithStatus:
fffff807`0e27bb50 cc              int     3

```

Is this a common issue, and if so what is the solution?

**Comment by appleman1232** [comment]
pg?

**Comment by DarthTon** [comment]
It's caused by call to `PsSetCreateProcessNotifyRoutine`. That functions checks whether calling memory is inside kernel module and if it's not, it bugchecks.
