### ISSUE TITLE
ForceRemap issue with ntdll

### ISSUE THREAD

**Issue by Unc3nZureD** [DarthTon/Blackbone#366]
I'm trying to remap ntdll in my process. The issue is specific to x86 process on an x64 host and specific to ntdll _(you'll see why)_.

Trying to call any Nt* func. Example here: (left on a real ntdll, right is the mapped one)
![cheatengine-x86_64_2019-09-13_19-34-14](https://user-images.githubusercontent.com/8837736/64882929-70d83c00-d65e-11e9-9e05-804e935a44a2.png)

Following the pointer in the edx here:
![cheatengine-x86_64_2019-09-13_19-36-56](https://user-images.githubusercontent.com/8837736/64882931-7170d280-d65e-11e9-8096-1e5bfb739db4.png)

Now you can see what's the issue, the pointer to the wow64cpu.dll is not relocated properly, however I've got no idea what should relocate it at all. Is it the job of the loader to relocate it at all? I know I could manually just overwrite and "hack" it, but I'm curious what should do it and if it's possible to fix it without specifying that "IF ntdll THEN patch THAT". Or is it something very custom for ntdll?

My mapping code if it helps:

```
	Process thisProc;
	thisProc.Attach(GetCurrentProcessId());

	auto callback = [](CallbackType, void*, Process&, const ModuleData&)
	{
		return LoadData(MT_Manual, Ldr_None);
	};

	auto image = thisProc.mmap().MapImage(L"C:\\Windows\\SysWOW64\\ntdll.dll", ForceRemap, callback);
	if (!image)
	{
		std::wcout << L"Mapping failed with error 0x" << std::hex << image.status
			<< L". " << Utils::GetErrorDescription(image.status) << std::endl << std::endl;
	}
	else
		std::wcout << L"Successfully mapped, unmapping\n";

	// Now just find the export you need and call it.
```

**Comment by Unc3nZureD** [comment]
@DarthTon Do you have any idea what should be the responsible for this?

**Comment by DarthTon** [comment]
`Wow64Transition` is initialized once by `wow64.dll!CpupResolveReverseImports` during process initialization. So I'm afraid you need to update the address manually and a special case for ntdll mapping.

**Comment by Unc3nZureD** [comment]
Ahh, so that's what resolves it. Thank you! I'm still amazed by your knowledge on PE internals :D
