### ISSUE TITLE
failed to build 

### ISSUE THREAD

**Issue by ZhouZiY** [DarthTon/Blackbone#369]
I builded the project in release x64 mode and get this error: 

> Error	C2338	Test writer must define specialization of ToString<const Q& q> for your class class std::basic_string<wchar_t,struct std::char_traits<wchar_t>,class std::allocator<wchar_t> > __cdecl Microsoft::VisualStudio::CppUnitTestFramework::ToString<__int64>(const __int64 &).	BlackboneTest	c:\program files (x86)\microsoft visual studio\2017\professional\vc\auxiliary\vs\unittest\include\cppunittestassert.h	66	

It works well in x32 mode. Could you please help to slove this?
Thanks.

**Comment by DarthTon** [comment]
You either need latest VS 2019 or revert this change https://github.com/DarthTon/Blackbone/commit/25d5d490ac563690f6cdc19517ceed0bb9a2dd9d#diff-6f8671678b7ff7595aee96465841e4f3L3-L6
