### ISSUE TITLE
std::mutex alternative CriticalSection

### ISSUE THREAD

**Issue by Maktm** [DarthTon/Blackbone#37]
Hey,

I was looking over this and I was wondering

https://github.com/DarthTon/Blackbone/blob/master/src/BlackBone/Misc/Utils.h

Shouldn't you be using LeaveCriticalSection inside of the destructor? Or else won't it still be "locked"? Just like how std::unique_lock/std::lock_guard seem to destroy the mutex when out of scope.

**Comment by DarthTon** [comment]
Yes, my mistake.

**Comment by DarthTon** [comment]
Actually it works as intended. CriticalSection behaves like std::mutex which has undefined behavior if destroyed while locked. And CSLock works as std::lock_guard - it leaves critical section in destructor. Moreover if LeaveCriticalSection is called on non-locked object, it may cause other threads to deadlock.

**Comment by Maktm** [comment]
Oh, alright. Nice implementation then :)
