### ISSUE TITLE
Does mmap work at 1903?

### ISSUE THREAD

**Issue by cuteboy42** [DarthTon/Blackbone#372]
Besides Windows 1903, I worked very well when I tried manualmapping using xenos and blackbone.
However, mmap does not work after Windows 1903.
xenos printed out error code 0xC0000138.
Please share the information you know about this problem.

**Comment by boris768** [comment]
0xC0000138
STATUS_ORDINAL_NOT_FOUND 
{Ordinal Not Found} The ordinal %ld could not be located in the dynamic link library %hs.

Compile in debug mode and check backtrace

**Comment by bugproof** [comment]
it stopped working for some reason. I was using xenos with mmap just fine before 1903

**Comment by bugproof** [comment]
ok it looks like in xenos when you check "Ignore TLS" it works

"Ignore TLS - Don't process image static TLS data and call TLS callbacks."

not sure if it's windows version anymore

**Comment by atiZZZ** [comment]
Manual map working on 1903. All okey
