### ISSUE TITLE
access error with "GetCurrentProcess()"

### ISSUE THREAD

**Issue by nblog** [DarthTon/Blackbone#379]
OS: Win10 x64
Compile: x86
samlpe code
```
blackbone::Process _process;
_ASSERT(NT_SUCCESS(_process.Attach(GetCurrentProcess())));
auto m = _process.modules().GetMainModule();
```
m = empty

First error:
[if (_proc.barrier().x86OS)](https://github.com/DarthTon/Blackbone/blob/master/src/BlackBone/Process/ProcessModules.cpp#L138)

Maybe it should be "_proc.barrier (). TargetWow64"

Second error:
The cause of the error is because "NativeWow64::ReadProcessMemoryT"
_hProcess = GetCurrentProcess() return STATUS_INVALID_HANDLE

Maybe when "true == targetWow64" or "&& GetCurrentProcess() == _hProcess"
"call ReadProcessMemory" is better.

associate:
ReadProcessMemoryT
WriteProcessMemoryT
QueryProcessInfoT

**Comment by DarthTon** [comment]
It fails because Win10 wow64 routines don't work with pseudo handle. `ProcessCore::Open( HANDLE handle )` should have this check as well https://github.com/DarthTon/Blackbone/blob/master/src/BlackBone/Process/ProcessCore.cpp#L36-L37.
