### ISSUE TITLE
Is it possible to hook without injection?

### ISSUE THREAD

**Issue by Xstasy** [DarthTon/Blackbone#38]
I have my own injection method which does what it's supposed to do, and I was going to use your library within my dll, but it seems that it's not possible to Hook into the local memory space.

Program loads my DLL into it, I just need to be able to run hooks and patternsearch.

**Comment by DarthTon** [comment]
Include just  "Localhook.hpp" and PatternScan into your dll.

**Comment by Xstasy** [comment]
So how do I run a wildcard search from the dll? All methods I see is requiring you to use a attached process.

**Comment by spinninglock** [comment]
Once you're in: 
```
Process localProc;
localProc.Attach(GetCurrentProcess());
```

Then do your stuff on that Process object.

**Comment by DarthTon** [comment]
"PatternSearch::Search" is designed to search in the local process.
