### ISSUE TITLE
memory protection and CastProtection

### ISSUE THREAD

**Issue by siilky** [DarthTon/Blackbone#393]
A quite surprising behavior of memory allocation/protection is that protection flags depends from process DEP status. Besides of fact that this behavior breaks 'memblock' object logical encapsulation by involving unexpected side effect, I guess that also leads to inability by using memory api to allocate/protect memory with executable flag at all while dep is turned off. 
In addition, I am completely missing logic requiring for that solution, and propose to isolate X flag cleanup into code that actually requires that.

**Comment by DarthTon** [comment]
Logic behind this is to not use executable pages when possible (DEP off). The caller should not care much about this because to him memory allocated with X flag is still executable despite not having an actual X flag.

**Comment by siilky** [comment]
I had a real case behind it (without much details) when a process on DEP-enabled system did not have (or could not be obtained) DEP state at early stage of creation. So dep assumed to be off (I guess somewhere at Process class level) with some regions allocated without X. When DEP is established later this whole thing gets messed.

In practice I suppose days when DEP-disabled systems were used are gone, and I believe this option should be at least configurable somehow with default state off.

**Comment by DarthTon** [comment]
That's odd. Default DEP flag state is `true`. And even if you create a process in a suspended state, meaning it's not yet initialized properly, DEP flag can already be obtained.
I can make this behavior configurable tho.
