### ISSUE TITLE
Cannot get inline hook to work. 

### ISSUE THREAD

**Issue by aeo24** [DarthTon/Blackbone#41]
typedef void(__fastcall *t_InvalidPtrCheck)(ptr_t *address);

ptr_t protectionAddress = (DWORD_PTR)GetModuleHandle(NULL) +(FrameScript_InvalidPtrCheckAddr - 0x140000000);

void __fastcall hookInvalidPtrCheck(ptr_t* &address)
{
	Log("Hooked::InvalidPtrCheck");
}

Detour<t_InvalidPtrCheck> det2;
t_InvalidPtrCheck t = (t_InvalidPtrCheck)protectionAddress;
if (det2.Hook(t, &hookInvalidPtrCheck, HookType::Inline))
{
	Log("Detour applied");
}

I've tried a few different approaches here and cannot get this code to work. My Detour is applied as the method returns true but from what I can tell in cheat engine the bytes are not written. I looked at some older issues created and made sure I have the latest copy of the lib. I just added the TestApp project so I'm confident in my project set up. This is my last ditch effort to have it solved. I really like this lib :) Great work.

**Comment by DarthTon** [comment]
I've done a few bug fixes for x64 hooking in last commit a4af3859c7119ffa5f1124655a25d95c45363d0b. Try it and if it still fails can you please trace the actual place where it fails to overwrite original bytes?

**Comment by aeo24** [comment]
Just wanted to update this is now working. 

typedef bool (__fastcall *t_GetGUIDFromToken)(const char *a1, WOWGUID  &a2, bool a3, bool  a4);
Detour<t_GetGUIDFromToken> det2;
ptr_t getGUIDByKeyword = (DWORD_PTR)GetModuleHandle(NULL) + (GetGUIDByKeywordAddr - 0x140000000);
t_GetGUIDFromToken t = (t_GetGUIDFromToken)getGUIDByKeyword;
if (det2.Hook(t, &hookGetGUIDFromToken, HookType::Inline, CallOrder::HookLast, ReturnMethod::UseOriginal))
	{
		Log("Detour applied");
	}
