### ISSUE TITLE
[Question] Is it possible for EnumModulesT to crash in a few cases?

### ISSUE THREAD

**Issue by SpriteOvO** [DarthTon/Blackbone#412]
I'm not sure if I'm understanding this correctly.

EnumModulesT traverses InLoadOrderLinks without using locks (some members in EPROCESS).

If a process loads or frees a module while we are traversing InLoadOrderLinks, is it possible that the Flink pointer we are about to access is corrupted?

I have the same question with the VAD traversal.

Am I missing some knowledge points? Or does that possibility actually exist?

Thank you!

**Comment by DarthTon** [comment]
Technically it's possible to get invalid pointer during InLoadOrderLinks traversal, but EnumModulesT should just return an error in this case, KM counterpart is protected by __try/__except so unless it gets KM pointer it should be also fine. Adding `ProbeForRead` should solve this problem.

**Comment by SpriteOvO** [comment]
I understand, thank you!
