### ISSUE TITLE
error load driver

### ISSUE THREAD

**Issue by AcroniS1337** [DarthTon/Blackbone#413]
https://prnt.sc/t3u304
Here is such a problem with loading the driver, this problem on different OC.
How can this be fixed?

**Comment by AcroniS1337** [comment]
error code 0xC000009A

**Comment by AcroniS1337** [comment]
@DarthTon  help pls

**Comment by DarthTon** [comment]
Well, some initialization API failed. Can you post DbgView logs of driver loading?

**Comment by AcroniS1337** [comment]
You can close, I solved the problem
