### ISSUE TITLE
Unfinished code in RemoteLocalHook

### ISSUE THREAD

**Issue by alemariusnexus** [DarthTon/Blackbone#417]
I'm trying to use BlackBone to hook into a remote function (not at the function start but somewhere in the middle, but that's another story) to inject some simple ASM. I was looking at RemoteLocalHook to do that, but it seems like that was implemented half way and then abandoned 3 years ago. There's the obvious missing 64-bit support, but even 32-bit isn't working: When testing, it didn't jump back to the original code properly but to some random location causing a segfault.

Looking at the code a bit more, the return address (_ctx.hook32.jmp_code) for the jmp is never actually written, and there's a commented-out line at the end of CopyOldCode() that would supposedly do it.

Is there a reason this code was abandoned? I actually don't have much experience with anything assembly-related, but it looks relatively easy to fill in the missing parts, and even to add some 64-bit support (the initial jmp here seems to be a problem), so I think I'll have a go at doing that myself. Unless someone tells me it was abandoned because it turned out to be much more complicated than it seems.

**Comment by DarthTon** [comment]
No strong reason, I'm to lazy to finish it. I didn't think it was a really useful feature.

**Comment by alemariusnexus** [comment]
I finished the code and got it working on x86 and x86_64 in my pull request: https://github.com/DarthTon/Blackbone/pull/420
