### ISSUE TITLE
X64Call Crash Windows 10 (CreateRemoteThread)

### ISSUE THREAD

**Issue by JoshNeal68** [DarthTon/Blackbone#42]
When attempting to manually map in Windows 10, I get a crash when attempting to restore the esp register. Am I the only one? Or has anybody else experienced this?

Edit: As a side note, it traces back to either Process::Attach or NativeWow64::CreateRemoteThreadT

Edit 2: This issue only seems to happen when trying to manually map a 32bit application into a 32bit process. But going from 64bit to 64bit has no issues. Could it be an issue with loading the 64bit CreateRemoteThread from the system32/ntdll.dll instead of the 32bit version from SysWOW64/ntdll.dll?

Edit 3: Managed to narrow it down to CreateRemoteThread. It appears to not like Windows 10, whether it be a lack of rights between my process and the target process or I'm just not able to grab a valid handle to CreateRemoteThread

**Comment by JoshNeal68** [comment]
As a side note, it traces back to either Process::Attach or NativeWow64::CreateRemoteThreadT

**Comment by DarthTon** [comment]
Ok, thank you. I'll take a look.

**Comment by Timboy67678** [comment]
Narowed this down to NativeWow64::CreateRemoteThreadT, x64Call has access violation at             X64_End(), temporary fix is to uncomment the if(_wowBarrier.targetWow64) line in the function and to add a check for targetwow64 in VirtualAllocExT to revert to using Native::VirtualAllocExT

**Comment by JoshNeal68** [comment]
Doing what @Timboy67678 said corrected the issue with CreateRemoteThreadT temporarily like he said, along with fixing VirtualAllocExT, but the same issue appears to occur with VirtualQueryExT and VirtualFreeExT.

**Comment by DarthTon** [comment]
@Timboy67678 I am aware of the change to WOW64 calls, but it's not the issue. I do direct code segment switch, so it's unaffected by those changes. 
Sadly I can't reproduce the issue on my Win10 test VM, but I think it has something to do with the stack.

**Comment by Timboy67678** [comment]
@DarthTon My apologies, i briefly glanced over the article. No idea whats causing the stack corruption, so i have reverted to using some of the native functions in wow64subsystem. Works for me at the moment, as i said above, just a temp fix for others having this problem.

And yer, the x86 debugger had problems with processing x64 exception, i might try using windbg to isolate the problem

**Comment by TheDeadCode** [comment]
Ohhhh, timboy is here. How... special

**Comment by iOutSide** [comment]
Hi, any news on it?

**Comment by neoz** [comment]
Rewolf has a fix for AMD CPU at
https://github.com/rwfpl/rewolf-wow64ext

**Comment by rwfpl** [comment]
It seems that you guys benefit even from the fixes for my library, yet 0 credits given for the X64Call which is just modified version of my code...
