### ISSUE TITLE
Unresolved External Symbol asmjit

### ISSUE THREAD

**Issue by rablidad** [DarthTon/Blackbone#423]
hey, whatsup, I tried using blackbone in my project today, and after setting it up and trying to build it, i get this error message:

`1>------ Build started: Project: rs2clientHooking, Configuration: Release x64 ------
1>pch.cpp
1>main.cpp
1>main.obj : error LNK2001: unresolved external symbol "struct asmjit::X86RegData const asmjit::x86RegData" (?x86RegData@asmjit@@3UX86RegData@1@B)
1>C:\Users\Raiqu\source\repos\rs2clientHooking\x64\Release\rs2clientHooking.dll : fatal error LNK1120: 1 unresolved externals
1>Done building project "rs2clientHooking.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
`

would appreciate help,  thanks!

**Comment by rablidad** [comment]
Solved

**Comment by chenbowen9706** [comment]
u need to define BLACKBONE_IMPORTS
