### ISSUE TITLE
WordSize: Macro Clash with Qt

### ISSUE THREAD

**Issue by alemariusnexus** [DarthTon/Blackbone#427]
In BlackBone/Include/Macro.h, there is the following:

```c++
// Architecture-dependent pointer size
#define WordSize sizeof(void*)
```

This clashes with [an enum definition in Qt](https://doc.qt.io/qt-5/qsysinfo.html#Sizes-enum). I'm writing a project that uses both BlackBone and Qt, and because of this, I had to add a hack that always includes BlackBone/Include/Macro.h before any Qt headers, and then #undefs it right after. This works (for now), but is very ugly and inconvenient.

BlackBone's WordSize macro is only ever used once in the entire project: a few lines below in the same header. I would suggest simply removing this macro and replacing the single occurence of it with `sizeof(void*)`. It's possible that this would break other projects that rely on this specific macro (the fix would be trivial), but I think keeping a macro with such a common name in BlackBone is a very bad idea anyway, especially if it's not even a function-like macro.

**Comment by huyi51462** [comment]
I also encountered this frustrating problem, can you talk about the specific solution?

**Comment by huyi51462** [comment]
> In BlackBone/Include/Macro.h, there is the following:
> 
> ```c++
> // Architecture-dependent pointer size
> #define WordSize sizeof(void*)
> ```
> 
> This clashes with [an enum definition in Qt](https://doc.qt.io/qt-5/qsysinfo.html#Sizes-enum). I'm writing a project that uses both BlackBone and Qt, and because of this, I had to add a hack that always includes BlackBone/Include/Macro.h before any Qt headers, and then #undefs it right after. This works (for now), but is very ugly and inconvenient.
> 
> BlackBone's WordSize macro is only ever used once in the entire project: a few lines below in the same header. I would suggest simply removing this macro and replacing the single occurence of it with `sizeof(void*)`. It's possible that this would break other projects that rely on this specific macro (the fix would be trivial), but I think keeping a macro with such a common name in BlackBone is a very bad idea anyway, especially if it's not even a function-like macro.

I also encountered this frustrating problem, can you talk about the specific solution?

**Comment by alemariusnexus** [comment]
> I also encountered this frustrating problem, can you talk about the specific solution?

Sure. My workaround is to have a single header file that is included by every other file before anything else. In my case, it's config.h, but I believe most Visual Studio projects already have something like stdafx.h. In this file, I have the following:

```c++
// Macro.h uses some of it, so this means we have to include it in EVERY SINGLE FILE *sigh*
#include <windows.h>

#ifdef WordSize
#error Looks like you included a BlackBone header before including config.h. This won't work because of incompatibilities with Qt.
#endif

#include <BlackBone/Include/Macro.h>

#undef WordSize
```

The last two lines are the important ones: It includes Macro.h and then removes the offending macro with #undef afterwards. Since Macro.h uses `#pragma once`, the macro will not be defined again when BlackBone headers are included later on, and Qt is happy. It's currently not a problem because no other BlackBone headers actually need to use the macro. Having to `#include <windows.h>` in every file probably doesn't even slow down compilation because of MSVC's precompiled headers feature, and you might want to do that anyway, depending on your project.


The other option - if you don't mind modifying BlackBone itself - is to just remove the `#define WordSize` line from Macro.h, and then change the following line in the same file:

```c++
#define LAST_STATUS_OFS (0x598 + 0x197 * WordSize)
```

to:

```c++
#define LAST_STATUS_OFS (0x598 + 0x197 * sizeof(void*))
```

You shouldn't even have to recompile BlackBone for this, since it's just a header and doesn't actually change any behavior.

**Comment by huyi51462** [comment]
thanks bro,I have modified the name of the macro def, I searched all the source files, and there is no second reference to this macro definition.

**Comment by huyi51462** [comment]
> > I also encountered this frustrating problem, can you talk about the specific solution?
> 
> Sure. My workaround is to have a single header file that is included by every other file before anything else. In my case, it's config.h, but I believe most Visual Studio projects already have something like stdafx.h. In this file, I have the following:
> 
> ```c++
> // Macro.h uses some of it, so this means we have to include it in EVERY SINGLE FILE *sigh*
> #include <windows.h>
> 
> #ifdef WordSize
> #error Looks like you included a BlackBone header before including config.h. This won't work because of incompatibilities with Qt.
> #endif
> 
> #include <BlackBone/Include/Macro.h>
> 
> #undef WordSize
> ```
> 
> The last two lines are the important ones: It includes Macro.h and then removes the offending macro with #undef afterwards. Since Macro.h uses `#pragma once`, the macro will not be defined again when BlackBone headers are included later on, and Qt is happy. It's currently not a problem because no other BlackBone headers actually need to use the macro. Having to `#include <windows.h>` in every file probably doesn't even slow down compilation because of MSVC's precompiled headers feature, and you might want to do that anyway, depending on your project.
> 
> The other option - if you don't mind modifying BlackBone itself - is to just remove the `#define WordSize` line from Macro.h, and then change the following line in the same file:
> 
> ```c++
> #define LAST_STATUS_OFS (0x598 + 0x197 * WordSize)
> ```
> 
> to:
> 
> ```c++
> #define LAST_STATUS_OFS (0x598 + 0x197 * sizeof(void*))
> ```
> 
> You shouldn't even have to recompile BlackBone for this, since it's just a header and doesn't actually change any behavior.

thanks bro,I have modified the name of the macro def, I searched all the source files, and there is no second reference to this macro definition.

**Comment by huyi51462** [comment]
I think what you said is right, the name of this macro is too common and it is easy to conflict with other libs.

**Comment by alemariusnexus** [comment]
This will be fixed by https://github.com/DarthTon/Blackbone/pull/468.
