### ISSUE TITLE
Windows 10 official release issue with ManualMap and exception handling.

### ISSUE THREAD

**Issue by MMOMinion-Powder** [DarthTon/Blackbone#43]
Here is the tracelog for when I attempt to use ManualMap with ManualImports and exception handling. Works fine with NoExceptions. Perhaps the sigs changed again?

NativeLdr: LdrHeapBase not found
ManualMap: Mapping image 'MemoryImage_0x0311E020' with flags 0x4005
ManualMap: Loading new image 'MemoryImage_0x0311E020'
ManualMap: Image base allocated at 0x07CE0000
ManualMap: Performing image copy
ManualMap: Relocating image 'MemoryImage_0x0311E020'
ManualMap: Loading new dependency 'd3dx9_43.dll'
ManualMap: Dependency path resolved to 'C:\WINDOWS\system32\d3dx9_43.dll'
ManualMap: Loading new image 'C:\WINDOWS\system32\d3dx9_43.dll'
ManualMap: Image base allocated at 0x087F0000
ManualMap: Performing image copy
ManualMap: Relocating image 'C:\WINDOWS\system32\d3dx9_43.dll'
ManualMap: Enabling exception support for image 'd3dx9_43.dll'
ManualMap: Failed to enable exception handling for image d3dx9_43.dll
ManualMap: Failed to load dependency 'C:\WINDOWS\system32\d3dx9_43.dll'. Status = 0x0

**Comment by DarthTon** [comment]
Yes, most likely sigs were changes. Will fix shortly.

**Comment by DarthTon** [comment]
Yes, most likely sigs were changes. Will fix shortly.

**Comment by MINIONBOTS** [comment]
Hello, 

is it possible that MS updated their cheese again ? We have several cases where it just stopped working all of a sudden, sadly none of our computers yet, so I cannot give you an extended debug log ...yet ...
http://www.speedyshare.com/VrfSW/ntdll.dll
this is a win 10 Build 10240 file, where it did not work anymore. I will give you a proper log the moment my windows fails too ...but so far, no luck :/

**Comment by DarthTon** [comment]
NP. I'll wait for a log then.
