### ISSUE TITLE
I need a kernel manual map injecktor for C ++

### ISSUE THREAD

**Issue by maskelibesler4678** [DarthTon/Blackbone#431]
I want to load dll from cmd screen with c ++ codes, not from xenos. How can I make it happen?

**Comment by h4xu3lyn** [comment]
`#pragma once
#define _CRT_SECURE_NO_WARNINGS
#include <Windows.h>
#include <string>
#include <iostream>
#include <string>
#include "Blackbone/src/BlackBone/Config.h"
#include "Blackbone/src/BlackBone/Process/Process.h"
#include "Blackbone/src/BlackBone/PE/PEImage.h"
#include "Blackbone/src/BlackBone/Misc/Utils.h"

#pragma comment(lib, "Blackbone/src/BlackBone/BlackBone.lib")

using namespace blackbone;
using namespace std;
blackbone::Process _process;

void KernelMMap(DWORD programpid) {
    static bool DriverControl = blackbone::Driver().EnsureLoaded();
    if (!DriverControl)
    {
        if (!blackbone::Driver().MmapDll(programpid, L"dllpath.dll", KWipeHeader | KNoTLS)) {
            std::cout << " Injection Successful!" << std::endl;
        }
        else {
            std::cout << " Injection Failed!" << std::endl;
        }
    }
    else {
        std::cout << " Load BlackBone Driver." << std::endl;
    }
}
int main() {
    _process.Attach(L"test.exe");
    KernelMMap(_process.pid());
}`
I hope this code helped you XD.

**Comment by Narumiiii** [comment]
> ```
> #pragma once
> #define _CRT_SECURE_NO_WARNINGS
> #include <Windows.h>
> #include <string>
> #include <iostream>
> #include <string>
> #include "Blackbone/src/BlackBone/Config.h"
> #include "Blackbone/src/BlackBone/Process/Process.h"
> #include "Blackbone/src/BlackBone/PE/PEImage.h"
> #include "Blackbone/src/BlackBone/Misc/Utils.h"
> 
> #pragma comment(lib, "Blackbone/src/BlackBone/BlackBone.lib")
> 
> using namespace blackbone;
> using namespace std;
> blackbone::Process _process;
> 
> void KernelMMap(DWORD programpid) {
>     static bool DriverControl = blackbone::Driver().EnsureLoaded();
>     if (!DriverControl)
>     {
>         if (!blackbone::Driver().MmapDll(programpid, L"dllpath.dll", KWipeHeader | KNoTLS)) {
>             std::cout << " Injection Successful!" << std::endl;
>         }
>         else {
>             std::cout << " Injection Failed!" << std::endl;
>         }
>     }
>     else {
>         std::cout << " Load BlackBone Driver." << std::endl;
>     }
> }
> int main() {
>     _process.Attach(L"test.exe");
>     KernelMMap(_process.pid());
> }
> ```
> 
> I hope this code helped you XD.
> Contact me if u want a kernel manual map that doesn't use blackbone.

Hello how i cna contact you? i am interesed on a mmap without blackbone
