### ISSUE TITLE
error C2039 (VS2019, win10 x64)

### ISSUE THREAD

**Issue by akokarev** [DarthTon/Blackbone#435]
> 1>C:\Users\kokar\source\repos\Xenos\ext\BlackBone\src\BlackBone\Process\ProcessModules.cpp(194,14): error C2039: 'inserter': is not a member of 'std'
> 1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.27.29110\include\array(20): message : see declaration of 'std'
> 1>C:\Users\kokar\source\repos\Xenos\ext\BlackBone\src\BlackBone\Process\ProcessModules.cpp(194,22): error C3861: 'inserter': identifier not found

Try compile Xenos with BlackBone, but this error occured. I already install WDK, SDK and some other.

**Comment by alemariusnexus** [comment]
I'm getting this as well, but it's easy to fix. I believe all I had to do was add this line somewhere to the beginning of BlackBone/Process/ProcessModules.cpp:

```c++
#include <iterator>
```

**Comment by akokarev** [comment]
Thanks, it's work!
