### ISSUE TITLE
BlackBone Driver Error (StartService FAILED 50 : The request is not supported.)

### ISSUE THREAD

**Issue by furkankadirguzeloglu** [DarthTon/Blackbone#448]
Hello, "The request is not supported." has an error. Could you help?
OS Ver: Win10 20H2 (19042.630) 
SDK Ver: 10.0.19041.0

Thank you from now.
@DarthTon @CreepGin @verysimplenick  @Timboy67678 @mrgreywater

**Comment by inc-Majdev** [comment]
Fixed. Solution: https://github.com/DarthTon/Blackbone/issues/440#issuecomment-737353075
![image](https://user-images.githubusercontent.com/74448882/100903994-95286e80-34d7-11eb-8f37-a84c09649450.png)

**Comment by Qfrost911** [comment]
Excuse me, I also encountered your problem when using BlackBone today. Would like to ask if you can provide a more detailed solution, thank you very much

**Comment by inc-Majdev** [comment]
> Excuse me, I also encountered your problem when using BlackBone today. Would like to ask if you can provide a more detailed solution, thank you very much

Hi, the problem is probably because you are using Windows 10 20H2. 
20H2 Source: https://github.com/inc-Majdev/Blackbone
20H2 Driver: https://github.com/inc-Majdev/Blackbone/releases/tag/20H2
