### ISSUE TITLE
Cor.h error compile

### ISSUE THREAD

**Issue by AlexWhiteS** [DarthTon/Blackbone#452]
Visual Studio 2019. 
SDK 10 (10.0.19041.0)

**Comment by AlexWhiteS** [comment]
fix

**Comment by BeneficialCode** [comment]
> fix

Could you tell me the fix method? Thanks a lot.

**Comment by song234876** [comment]
The Windows SDK introduced a dependency on .Net Framework 4.7.1 Software Development Kit, which is currently not installed.  To rectify this issue, simply modify the Windows SDK setup to include this dependency.
see https://social.msdn.microsoft.com/Forums/windowsapps/en-US/80cddbe8-f881-4b33-8bab-c7ca2b1573e0/known-issue-fatal-error-c1083-cannot-open-include-file-corh-no-such-file-or-directory?forum=Win10SDKToolsIssues
