### ISSUE TITLE
MMap::MapImage maps image twice on Win10x64

### ISSUE THREAD

**Issue by csullivan** [DarthTon/Blackbone#50]
On Windows 10 x64, manually mapping a buffer into a remote process works, however the image is mapped twice (or two threads are created, not sure which). I have been using this on Windows 7 x64 for months without this double mapping.

The issue is easily reproduced by using 	TestMMapFromMem() in the TestApp executable. There, cmd is mapped into the current process. After 30s control is given back to the parent, and one can see "Successfully mapped image, unmapping", however at that point the image is mapped a second time. Here is the application trace:

```
Manual image mapping from buffer test
Trying to map C:\windows\system32\cmd.exe into current process
BlackBone: ManualMap: Mapping image 'MemoryImage_0x01020000' with flags 0x4042
BlackBone: ManualMap: Loading new image 'MemoryImage_0x01020000'
BlackBone: ManualMap: Image base allocated at 0x011C0000
BlackBone: ManualMap: Performing image copy
BlackBone: ManualMap: Relocating image 'MemoryImage_0x01020000'
BlackBone: ManualMap: Enabling exception support for image 'MemoryImage_0x01020000'
BlackBone: ManualMap: Performing security cookie initializtion for image 'MemoryImage_0x01020000'
BlackBone: ManualMap: Rebasing process to address 0x011C0000
BlackBone: ManualMap: Calling entry point for 'MemoryImage_0x01020000', Reason: 1
The system cannot find message text for message number 0x2350 in the message file for Application.

(c) 2015 Microsoft Corporation. All rights reserved.

C:\reversing\Blackbone\build\Win32\Debug>

Successfully mapped, unmapping
BlackBone: ManualMap: Unmapping image 'MemoryImage_0x01020000'
BlackBone: ManualMap: Calling entry point for 'MemoryImage_0x01020000', Reason: 0
The system cannot find message text for message number 0x2350 in the message file for Application.

(c) 2015 Microsoft Corporation. All rights reserved.

C:\reversing\Blackbone\build\Win32\Debug>

BlackBone: ManualMap: Disabling exception support for image 'MemoryImage_0x01020000'


C:\reversing\Blackbone\build\Win32\Debug>

```

**Comment by csullivan** [comment]
I wanted to leave it out of the issue, but the comment section afford me a separate opportunity: This is a masterpiece of a library. Well done DarthTon! Many of the techniques you employ have been quite helpful in honing my abilities, and I am very thankful.

**Comment by DarthTon** [comment]
That's because it's an exe. Entry point is called upon unmapping with DLL_PROCESS_DETACH reason, but in exe there is no such thing as DLL_PROCESS_DETACH, and cmd just executes normally once more. Shouldn't be an issue when mapping dlls.

**Comment by csullivan** [comment]
I agree that an exe will be called a second time from the DLL_PROCESS_DETACH call, however, the second mapping (or thread creation) is occurring on the call to DLL_PROCESS_ATTACH. You can reproduce this by removing all calls to DLL_PROCESS_DETACH (ie, remove calls to UnmapAllModules()). Still the exe is mapped twice. 

The issue is coming from 
```
            if (!RunModuleInitializers( img.get(), DLL_PROCESS_ATTACH ))
                return nullptr;
```
inside MMap::MapImageInternal. I see different behavior with this call in Win7 vs Win10. In windows 7, if I comment out this call, the exe is never mapped and the application closes. In windows 10, if I comment out this function call, the exe is this time mapped (presumably by FindOrMapModule), and only once! If I uncomment this line (how it is originally), the image is mapped a single time in Win7, and twice in Win10.

**Comment by DarthTon** [comment]
Here are the investigation results.
In win10 LdrShutdown process started to call module initializer upon process termination. Since image is mapped with 'CreateLdrRef' flag, its initializer gets called upon process termination.

**Comment by csullivan** [comment]
Ah, I see. Tricky. Well, thank you for these results.
