### ISSUE TITLE
blackbone visualstudio 2022 build error

### ISSUE THREAD

**Issue by qwer0123456** [DarthTon/Blackbone#503]
Microsoft Visual Studio 2022 17.4.1 version

ProcessModules.cpp

error function

call_result_t<ModuleDataPtr> ProcessModules::Inject( const std::wstring& path, ThreadPtr pThread /*= nullptr*/ )

ustr.Buffer = modName->ptr<std::decay_t<decltype(ustr)>::type>() + sizeof( ustr );

error C2672 'blackbone::MemBlock::ptr': no matching overloaded function
error C2275 'blackbone::_UNICODE_STRING_T<uint32_t>::type': expected expression instead of type
error C2275 'blackbone::_UNICODE_STRING_T<uint64_t>::type': expected expression instead of type

how fix?

**Comment by FightToDawn** [comment]
me too

**Comment by FightToDawn** [comment]
vs set project  property -> C/C++ -> language 
 /permissive

**Comment by wkingnet** [comment]
not because of permissive. The correct setting is:
vs set project property -> C / C++ -> language -> C++ language standard -> ISO C++ 17
