### ISSUE TITLE
Windows 22H2 support/Windows 11 support

### ISSUE THREAD

**Issue by git-eternal** [DarthTon/Blackbone#504]
Does anyone have the updated signatures needed to get blackbone working on 22h1/2+? I tried manually updating them to no avail.

I just keep getting these 2 errors:

BlackBone: PatternData: LdrpHandleTlsData64 not found
BlackBone: PatternData: LdrProtectMrdata not found 

Note: I have tried every other issue/commit and those also did not help

**Comment by paulhobbel** [comment]
Blackbone does currently not support Windows 11 22H2 yea. I solved it by adding new patterns in `PatternLoader.cpp`. I haven't been able to test my fixes on Windows 11 22H1 yet unfortunately.

I suppose I can open a PR with my fixes

**Comment by git-eternal** [comment]
> Blackbone does currently not support Windows 11 22H2 yea. I solved it by adding new patterns in `PatternLoader.cpp`. I haven't been able to test my fixes on Windows 11 22H1 yet unfortunately.
> 
> 
> 
> I suppose I can open a PR with my fixes
> 
> 
> 
> PS: I only fixed the 32bit patterns

Please do. Thanks! 

It's just weird how I updated everything perfectly for x64 and it still breaks

**Comment by paulhobbel** [comment]
@git-eternal try the code from my PR, should work on both 32bit and 64bit
