### ISSUE TITLE
Win 10, Unknown Problem

### ISSUE THREAD

**Issue by MINIONBOTS** [DarthTon/Blackbone#51]
Hi DarthTon, 
So I finally had the opportunity to do some more testings on a Win10 Computer where we keep having rare issues of being unable to attach our dll to the exe process. The computer I finally could look at, had Windows 10 updated and nothing weird running or installed either. Default Win10 Antivirus too. No other anti malware or similar software running. 
The code looks like this:
Process proc;
if( proc.Attach(Pid) == 0 ){
  
  proc.EnsureInit();
  blackbone::eLoadFlags flags = NoFlags ;
  if (proc.mmap().MapImage(DLLSize2, (void*)ostreamDll2.str().c_str(), false,flags) == 0)
  {
    // all goood 
  }
}

This code works for 99% of the people running win 10. I enabled blackbone trace but it didn't even create the log file on that computer (verified that it normally creates a log on my computer). 
The code freezes/hangs at "proc.EnsureInit()",  if I take that line out, it does the same at "proc.mmap().MapImage". 
It injects the dll fine if I use another injection method, so the actual dll is good, the ostreamDll2 as well. Like I said, it works fine for everyone but a few rare cases.

Do you have any idea where I could put more debug logging or anything that could help tracing down the cause of the problem, or maybe some other hints what I could try ?

Thanks a lot in advance!
fx

**Comment by DarthTon** [comment]
there is a debug log written into windows debug stream using OutputDebugString. You can use DbgView to export such log. But for this to work make sure BLACKBONE_NO_TRACE isn't defined (it is by default in release mode)

**Comment by MINIONBOTS** [comment]
I had already everything that was logged written into an output file, but it didn't even open/create the file on those win 10 computers where I tested it so far.
The only common thing that each of them had, was that they had the .exe (where the dll is being injected) inside the C:\Program Files (x86)\ folder.   ... I smell some access rights issue, but the c++ application injecting the dll is already being started with admin rights.
I'll try some more and will report back once I found something more useful....

thanks for your answer

**Comment by luukholleman** [comment]
I'm also noting this problem. We're using this library for a mod client for a game. Which runs on the Unity engine. The modding client is a c# wrapper around this library.

A small percentage of the users (5 so far) are reporting that mods aren't working, they're all running W10 (32 and 64 bits), which could be a coincidence but it seems to add up with this issue.

A user send me his windows event viewer log which has the following entry.

	Toepassing: ParkitectNexusClient.exe
	Framework-versie: v4.0.30319
	Beschrijving: het proces is beëindigd als gevolg van een onverwerkte
	uitzondering. < Uncaught exception
	Uitzonderingsinformatie: System.AccessViolationException
	Stack:
	   bij <Module>.inject(SByte*, SByte*, SByte*, SByte*, SByte*) < Blackbone
	   bij ParkitectNexus.ModLoader.ModInjector.Inject(System.String,
	System.String, System.String, System.String)
	   bij ParkitectNexus.Data.Parkitect.InjectModLoader()
	   bij ParkitectNexus.Data.Parkitect.LaunchWithMods(System.String)
	   bij ParkitectNexus.Client.Wizard.MenuUserControl.launchParkitectButton_Click(System.Object,
	System.EventArgs)
	   bij System.Windows.Forms.Control.OnClick(System.EventArgs)
	   bij System.Windows.Forms.Button.OnClick(System.EventArgs)
	   bij System.Windows.Forms.Button.OnMouseUp(System.Windows.Forms.MouseEventArgs)
	   bij System.Windows.Forms.Control.WmMouseUp(System.Windows.Forms.Message
	ByRef, System.Windows.Forms.MouseButtons, Int32)
	   bij System.Windows.Forms.Control.WndProc(System.Windows.Forms.Message ByRef)
	   bij System.Windows.Forms.ButtonBase.WndProc(System.Windows.Forms.Message
	ByRef)
	   bij System.Windows.Forms.Button.WndProc(System.Windows.Forms.Message ByRef)
	   bij System.Windows.Forms.Control+ControlNativeWindow.OnMessage(System.Windows.Forms.Message
	ByRef)
	   bij System.Windows.Forms.Control+ControlNativeWindow.WndProc(System.Windows.Forms.Message
	ByRef)
	   bij System.Windows.Forms.NativeWindow.Callback(IntPtr, Int32, IntPtr, IntPtr)
	   bij System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG ByRef)
	   bij System.Windows.Forms.Application+ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr,
	Int32, Int32)
	   bij System.Windows.Forms.Application+ThreadContext.RunMessageLoopInner(Int32,
	System.Windows.Forms.ApplicationContext)
	   bij System.Windows.Forms.Application+ThreadContext.RunMessageLoop(Int32,
	System.Windows.Forms.ApplicationContext)
	   bij System.Windows.Forms.Application.Run(System.Windows.Forms.Form)
	   bij ParkitectNexus.Client.Program.Main(System.String[])

The MSDN documentation indicates that there are 'several' pointer issues in unmanaged code.

https://msdn.microsoft.com/en-us/library/system.accessviolationexception(v=vs.110).aspx

We tried to get our own windows to block the memory injection with a high UAC, virus scanners. Admin rights etc. But nothing seems to protect it.

**Comment by MINIONBOTS** [comment]
Ok I FINALLY got a little bit closer, but sadly not to a solution. I added the following debug output to the code:
http://pasteboard.co/1PCjDzC1.png
http://pasteboard.co/1PCpIOkY.png
http://pasteboard.co/1PCwyVxM.png
http://pasteboard.co/1PCyWYQh.png

This is the output on one of these Win 10 computers where it just doesn't work:
[02-11-2015 03:25:58]=> Process::EnsureInit Start
[02-11-2015 03:25:58]=> ProcessModules::GetModule 1
[02-11-2015 03:25:58]=> ProcessModules::GetModule PID 5480
[02-11-2015 03:25:58]=> ProcessModules::GetModule 2: ntdll.dll
[02-11-2015 03:25:58]=> ProcessModules::GetModule type 0
[02-11-2015 03:25:58]=> ProcessModules::GetModule 4
[02-11-2015 03:25:58]=> ProcessModules::GetModule search 1 type 0
[02-11-2015 03:25:58]=> Native::EnumModules 1
[02-11-2015 03:25:58]=> Native::EnumModules Sections
[02-11-2015 03:25:58]=> Native::EnumSections 1
[02-11-2015 03:25:58]=> Native::EnumSections memptr 10000
[02-11-2015 03:25:58]=> Native::EnumSections status 0
[02-11-2015 03:25:58]=> Native::EnumSections mbi.Baseaddress 0 , mbi.RegionSize 10000
[02-11-2015 03:25:58]=> Native::EnumSections 2
[02-11-2015 03:25:58]=> Native::EnumSections memptr 870000
[02-11-2015 03:25:58]=> Native::EnumSections status 0
[02-11-2015 03:25:58]=> Native::EnumSections mbi.Baseaddress 0 , mbi.RegionSize 870000
[02-11-2015 03:25:58]=> Native::EnumSections 2
[02-11-2015 03:25:58]=> Native::EnumSections 3
[02-11-2015 03:25:58]=> Native::EnumSections 4
[02-11-2015 03:25:58]=> Native::EnumSections 5 0
[02-11-2015 03:25:58]=> Native::EnumSections 6
[02-11-2015 03:25:58]=> Native::EnumSections 7
[02-11-2015 03:25:58]=> Native::EnumSections 8 59e090 59e090
[02-11-2015 03:25:58]=> Native::EnumSections 11
[02-11-2015 03:25:58]=> Native::EnumSections 13
[02-11-2015 03:25:58]=> Native::EnumSections 13
[02-11-2015 03:25:58]=> Native::EnumSections 14
[02-11-2015 03:25:58]=> Native::EnumSections 15
[02-11-2015 03:25:58]=> Native::EnumSections memptr 871000
[02-11-2015 03:25:58]=> Native::EnumSections status 0
[02-11-2015 03:25:58]=> Native::EnumSections mbi.Baseaddress 0 , mbi.RegionSize 871000
[02-11-2015 03:25:58]=> Native::EnumSections 2
[02-11-2015 03:25:58]=> Native::EnumSections memptr 17cb000
[02-11-2015 03:25:58]=> Native::EnumSections status 0
[02-11-2015 03:25:58]=> Native::EnumSections mbi.Baseaddress 0 , mbi.RegionSize 17cb000
[02-11-2015 03:25:58]=> Native::EnumSections 2
[02-11-2015 03:25:58]=> Native::EnumSections memptr 17cc000

So it basicly stops at:
EnsureInit()-> _modules.GetModule(... ) ->  _core.native()->EnumModules(...) -> auto status = VirtualQueryExT( memptr, &mbi );

Out of some unknown reasons, I was unable to make it print out debug info from that VirtualQueryExt method, I added this to the functions:
http://pasteboard.co/1PCFQ2Cm.png
But it never managed to print anything into the log...now I'm not sure if that is just me being noobish without any breakfast or if there is really something wrong and it doesn't call the right function here ?

**Comment by MINIONBOTS** [comment]
Had another shot at it, 
It seems_LdrHeapBase  is 0 , aka could not be found for this case. 

And then later, when it iterates through the EnumModules -> VirtualQueryExt(), it just stops at some point while calling: NTSTATUS nt = static_cast<NTSTATUS>(_local.X64Call( ntqvm, _hProcess, lpAddress, 0, lpBuffer, sizeof( MEMORY_BASIC_INFORMATION64 ), 0 ));

It does work for a lot of calls, but it just stopped at some point.

Please let me know what I can do here, because that call is a bit over my c++ head.

**Comment by MINIONBOTS** [comment]
Another computer with that problem had also that _LdrHeapBase == 0 after the Init() function where it normally should get a value....

**Comment by MINIONBOTS** [comment]
Still having this issue 5 out of 100 users, win10 only. I'm out of options.

**Comment by DarthTon** [comment]
The best solution is probably a remote debug of problematic PCs, because I'm out of Ideas what can it be.

**Comment by MINIONBOTS** [comment]
Without being 100% sure yet, but it seems this issue happens ONLY on AMD cpus.....

**Comment by DarthTon** [comment]
I fixed AMD related a bug a while ago. a6747b69edfd0a7fa8fbd2b73412ff4e3196af53 to be precise

**Comment by MINIONBOTS** [comment]
Wonderful, I'll give it a shot and report back!

**Comment by MINIONBOTS** [comment]
WOW this really solved the issue :+1: 
Big thanks for you work and help, I'll close the ticket now :)
