### ISSUE TITLE
Windows 7 PromoteHandle BSOD [ SYSTEM_THREAD_EXCEPTION_NOT_HANDLED]

### ISSUE THREAD

**Issue by ArturK1338** [DarthTon/Blackbone#52]
Hello,

today I tried to Promote a Handle and give it All Acess rights, I can load a driver and all is fine.
But then I try to call PromoteHandle my PC bsod and I cannot do anything, so I testet the PromoteHandle on Windows 8, 8.1, 10 there is it working without a Problem but on Windows 7 it crashs.

Here is a Picture of the Bluescreen dump.
http://puu.sh/lVe6b/aa9d35a1cd.PNG
http://puu.sh/lVe7c/39ef985932.PNG

I hope you may can help me, to fix this error.

**Comment by DarthTon** [comment]
Can you send me a BSOD memory dump + your driver pdb?

**Comment by S0PEX** [comment]
Sure.
Here you go : s0pex.xyz/Debug.zip

Github dont wanted that I Upload it here normal it says Unfortunately, we don’t support that file type.

**Comment by DarthTon** [comment]
Weird. But this BSOD was triggered by failed security cookie initialization during driver startup.

**Comment by S0PEX** [comment]
And how I can prevent this or fix ?

**Comment by staticinvocation** [comment]
I know this is very late but WDK 8+ changed the way the security cookie is initialized.  Make sure you're targetting Windows 7.
