### ISSUE TITLE
BlackBoneDrv w10 v10586

### ISSUE THREAD

**Issue by R00T88** [DarthTon/Blackbone#56]
Hello man,
i have a problem retargeting project for w10 10586

1. I must include this addictional directory into project
C:\Program Files %28x86%29\Windows Kits\10\Include\10.0.10586.0\km\crt
C:\Program Files %28x86%29\Windows Kits\10\Include\10.0.10586.0\km

2. Project always check for lib for w10 10240
"C:\Program Files (x86)\Windows Kits\10\lib\10.0.10240.0\km\x64\BufferOverflowFastFailK.lib" "C:\Program Files (x86)\Windows Kits\10\lib\10.0.10240.0\km\x64\ntoskrnl.lib" "C:\Program Files (x86)\Windows Kits\10\lib\10.0.10240.0\km\x64\hal.lib" "C:\Program Files (x86)\Windows Kits\10\lib\10.0.10240.0\km\x64\wmilib.lib" 

but i have this lib into 10.0.10586.0 folder

3. i got this strange error on compile
command-line error: exception handling option can be used only when compiling C++	BlackBoneDrv

I try to retarget solution but i can only select 10.0.10240.0 and 8.1

Regards

**Comment by DarthTon** [comment]
I think it requires VS2015 Update 1.

**Comment by Reckt25** [comment]
Yep i can Build  10.0.10586.0 with the latest WDK and Latest Vs2015

**Comment by R00T88** [comment]
Yep thank you!

**Comment by tijesef** [comment]
c:\n\blackbone\src\blackbone\pe\ImageNET.h(11): fatal error C1083: Cannot open include file: 'cor.h': No such file or directory
