### ISSUE TITLE
Driver Manual Map issue

### ISSUE THREAD

**Issue by universelle** [DarthTon/Blackbone#58]
Hi,

First of all, very nice lib.
Secondly, I'm trying to have the driver manual map a DLL, but I'm stuck on the driver trying to resolve a forwarded import, specifically:

> api-ms-win-crt-runtime-l1-1-0.terminate

Here's the output from the driver: http://pastebin.com/raw/GAuRWj4Q

It would mean the world to me if you could perhaps point me in the right direction on how to solve the issue.

Thanks in advance

**Comment by DarthTon** [comment]
Do you have VS2015 x86 redistributable installed?
