### ISSUE TITLE
Support for Process-level Pattern Matching through Driver?

### ISSUE THREAD

**Issue by ZirakC** [DarthTon/Blackbone#65]
Hi Darthton,

I noticed in the TestApp example there is a sample of pattern matching, however this pattern match on explorer.exe is done through the TestApp.exe process, and not at the Driver level, is it possible to accomplish this at the driver level?

Thanks!

**Comment by DarthTon** [comment]
Yest it is possible, but there is no CTL code currently. As a workaround you can read memory through driver and do a pattern match locally.

**Comment by ZirakC** [comment]
Ah I see, one more question, is there a way to read memory regions on a process through the driver? This way I can pass this information and can use it to pattern match on my app.

**Comment by DarthTon** [comment]
Yes, there is a CTL code for memory reading.

**Comment by ZirakC** [comment]
Sorry to be more clear, I meant the memory region addresses & sizes of valid memory sections?

**Comment by ZirakC** [comment]
I was able to implement it on the blackbone code, if you'd like I can contribute it somehow, however I'm not too familiar with how I can upload the updated files for you :)

**Comment by DarthTon** [comment]
Do a pull request from your branch or just gimmy zip with changed files.

**Comment by DarthTon** [comment]
Implemented in 30e5db4a7e9a2c7710f93c815121cbe35a0bee2b.

**Comment by dummy0stud** [comment]
hey darthton, why you like to implement modifier methods rather than pure functions? better performance?

**Comment by DarthTon** [comment]
What do you mean by 'modifier methods'?

**Comment by dummy0stud** [comment]
methods that accept arguments, and modifies them, rather then returning the value, or collection of values(pure functions)

**Comment by DarthTon** [comment]
Because i don't use exceptions and functions tend to return error code.

**Comment by ZirakC** [comment]
I think he means like the COPY Mem function specifically, where it takes the pointer and updates the buffer at the process directly, which I think is a very efficient way of reading memory.
