### ISSUE TITLE
use BB_POOL_TAG in Utils.c

### ISSUE THREAD

**Issue by verysimplenick** [DarthTon/Blackbone#66]
Hi, thanks for awesome project. I just start with it. I found typo.
I see `#define BB_POOL_TAG ` in Profile.h, but in Utils.c in BlackBoneDrv proj you dont use this define, maybe need something like
`ExAllocatePoolWithTag( PagedPool, size, BB_POOL_TAG);`  
?

**Comment by DarthTon** [comment]
Not a typo but my laziness. The tag is the same as BB_POOL_TAG but for some reason I haven't used the define directly. Will fix this soon.
