### ISSUE TITLE
Blackbone Driver Load Error: 0xC0000034 

### ISSUE THREAD

**Issue by JasonTomas** [DarthTon/Blackbone#67]
----------------------------------------------------------------------------------
Screenshot of the error: 
http://imgur.com/WfHkoJ8

Pastebin system details/compile information:
http://pastebin.com/Tcjb8k7L
----------------------------------------------------------------------------------

I continue to receive this error despite having done everything you can see from the pastebin link. I've tried almost everything I can do from my perspective (windows driver development isn't my forte) and still can't seem to identify the cause of the error. 

I can tell from looking at the code that this is an excellent project. I would greatly appreciate it if you could help me to remedy this error so that I can experience the full functionality of this library.

Thank you.

**Comment by DarthTon** [comment]
Do you load driver from proper path? By default it searches for driver file at the executable folder but BlackBoneDrv is compiled into different place.

**Comment by JasonTomas** [comment]
It seems as though I was loading the driver from an invalid path. I was using the path to the folder "Win10Release" rather than "Win10Debug".  

Thanks for the help. Sometimes the most "complex" of errors turn out to have the simplest solutions. Haha.
