### ISSUE TITLE
Unload a module

### ISSUE THREAD

**Issue by SergeyLAI** [DarthTon/Blackbone#68]
Hello, Darthton.
Thank you for your library it is really something great!
I looking for a working solution to inject and eject (unload) DLLs into process memory. I found Xenos injector and reused a part of code with native injection into existing thread. But I can't unload this dll after. Is the blackbone library supports this function? Which API's can be useful for me?

**Comment by DarthTon** [comment]
ProcessModules::Unload for unloading non manually mapped module. For manual case there is function in MMap class, but you can only unload manual modules if there is still injection info present, i.e. mapping address, dependencies, etc.

**Comment by SergeyLAI** [comment]
Thank you for the help
