### ISSUE TITLE
KMODE_EXCEPTION_NOT_HANDLED Windows 10

### ISSUE THREAD

**Issue by ZirakC** [DarthTon/Blackbone#69]
Hey DarthTon,

Using the BlackBone Driver code as base, I moved over the Copy_Mem and ProtectMem functions over to a "driverless" driver solution, copy memory works in terms of reading + writing memory, however when I want to write memory to an area that's flagged as read only, I try to call for ProtectMem, however this results in a bluescreen "KMODE_EXCEPTION_NOT_HANDLED". I was wondering if there may be incompatibilities with the ProtectMem functionality when loading it as a driverless driver, would there be a way of identifying what causes this BSOD?
[DummyDrv2.zip](https://github.com/DarthTon/Blackbone/files/181014/DummyDrv2.zip)

Thank you,

**Comment by ZirakC** [comment]
Seems like the BSOD occurs on BBFindVAD function, still trying to debug it line by line to figure out the exact spot.

**Comment by DarthTon** [comment]
So, what was the issue behind this BSOD?

**Comment by ZirakC** [comment]
initially I was missing the BBInit function to set up all of the offsets, then I had to ensure I was using 0x40 as the new protect flag since for some reason all_access flag wasn't working correctly.
