### ISSUE TITLE
QueueUserAPC related code in dll crash the target process

### ISSUE THREAD

**Issue by RovingBit** [DarthTon/Blackbone#71]
const ModuleData\* MMap::MapImage(
        size_t size, void\* buffer,
        bool asImage = false,
        eLoadFlags flags = NoFlags,
        MapCallback mapCallback = nullptr,
        void\* context = nullptr,
        CustomArgs_t\* pCustomArgs_t = nullptr
        );

succeed mapped hack.dll to target.exe when call this method in excutable
failed when call this method in a dll(my loader.dll)
1. I debugging and tracing every line in this method in above two using situation
2. Then I found:
   a. QueueUserAPC(remoteProc,remotecode) will crash the target.exe when the loader is a dll
   b. If call MMap::MapImage() in a exe, mapped hack.dll into target.exe succeed
3. Finnaly:
   I changged all QueueUserAPC into ExecInNewThread(remoteProc, remoteCode)
   And then hack.dll mapped into target.exe succeed both in exe and dll type loader.

QUESTION:
Why QueueUserAPC will crash the target exe when called in a dll module?
But performing perfectly when called this method in a exe module?

**Comment by 739480474** [comment]
I googled a lot with no useful results.
I guess QueueUserAPC is a big black box, its not simple as it seems like.
I think I cant figure it out.

Waiting for you.
Thanks.

**Comment by DarthTon** [comment]
Can you provide process dump of any crashed application?

**Comment by 739480474** [comment]
Thanks for your reply and the great Blackbone.

I will make a test envirment as small as I can relates to this 'BUG'(maybe).

But these days I have no time.
I will back as soon as I can.

Thanks.

**Comment by DarthTon** [comment]
May be fixed in 172fd60cd1afbf17daee0e70e85a46a58ca253ca.

**Comment by Kruemmelmonster** [comment]
got the same problem wich seemed to have been fixed by 172fd60 but it wasnt

**Comment by demonxjj** [comment]
I also met the same problem , is On some computers.
