### ISSUE TITLE
Restore hook from hooked func not working.

### ISSUE THREAD

**Issue by verysimplenick** [DarthTon/Blackbone#73]
For now I go sleep and don't have time to learn and understand why int3 breaks (hooks) can't be restored internally (in hook). memcpy\WPM + read return what byte changed, but it's not. I think something like cpu cache. Maybe you know something?
p.s. check pull request (small fixes)

**Comment by verysimplenick** [comment]
Closed. Fix in my pull request #74.

**Comment by verysimplenick** [comment]
maybe not :) need time to check.

**Comment by verysimplenick** [comment]
I found something info

> When executing self-modifying code the use of FlushInstructionCache is required on CPU architectures that do not implement a transparent (self-snooping) I-cache.  These include PPC, MIPS, Alpha, and Itanium.  FlushInstructionCache is not necessary on x86 or x64 CPU architectures as these have a transparent cache.

> Cross-Modifying Code: Intel defines cross-modifying code as a scenario where Thread 1 on Processor 1 modifies instructions that are then immediately executed by Thread 2 on Processor 2.   The execution of a barrier instruction to serialize the data prefetch queue (LOCK prefix, XCHG, MFENCE, etc) will not serialize the instruction prefetch queue.  To serialize the instruction prefetch queue the other processors must do a context switch (e.g., SuspendThread followed by ResumeThread) or execute a serializing instruction such as CPUID.  See the topic "Handling Self- and Cross-Modifying Code", in the Intel Architecture manual.

But if I restore hook from hooked function with any of
```
// maybe is not necessary on x86 or x64, but we do
if (!FlushInstructionCache(GetCurrentProcess(), NULL, 0))
		return false;
// Execute a some of serializing instruction (needed with self-modifying code)
// According to the `Intel 64 and IA-32 Architectures Software Deverloper's Manual, Volume 3A: System Programming Guide, Part 1`, #8.1.3 Handling Self - and Cross - Modifying Code
__cpuid(contextSwitchHelper,0);
```

But nothing changes, first byte of hooked function still 0xCC (int3). If I do restore from another thread all is ok. Maybe someone know whats wrong with this change first byte of running function?

**Comment by verysimplenick** [comment]
Found [something](http://www.ownedcore.com/forums/world-of-warcraft/world-of-warcraft-bots-programs/wow-memory-editing/389616-ntflushinstructioncache-windows-8-a.html) like I get.
For history my proc: Intel Core i7 4770K

**Comment by DarthTon** [comment]
Can you provide me with some test code?

**Comment by verysimplenick** [comment]
Yes, it's something like this:
```
#include "../BlackBone/localHook/VTableHook.hpp"

typedef int(__fastcall *testFunc) (int a, int b, int c);

int __fastcall Test( int a, int b, int c )
{
    return 100+a+b+c;
}

Detour<testFunc> det;

int __fastcall hkTest(int& a, int& b, int& c)
{
	std::cout << "hkTest called. ";
	det.Restore();
	return 200 + a + b + c;
}

void TestLocalHook()
{
    det.Hook((testFunc)Test, &::hkTest, HookType::Int3, CallOrder::NoOriginal, ReturnMethod::UseNew);
    int val = Test( 1,2,3);
    std::cout << "Returned value = " << val << "\r\n";
	val = Test(1, 2, 3);
	std::cout << "Returned value = " << val << "\r\n";
	val = Test(1, 2, 3);
	std::cout << "Returned value = " << val << "\r\n";
}
```
I get
```
hkTest called. Returned value = 206
hkTest called. Returned value = 206
hkTest called. Returned value = 206
```
But need only one time hook, results must be something like this:
```
```
hkTest called. Returned value = 206
Returned value = 106
Returned value = 106
```
```

**Comment by verysimplenick** [comment]
I was thinked about Restore() only, hah. Anyway many thanks @DarthTon .
