### ISSUE TITLE
Driver load failed

### ISSUE THREAD

**Issue by alkantanju** [DarthTon/Blackbone#77]
Hi when try to use driver with xenos injector on vmware (OS:Win10 64bit) injector says driver load failed, 
i turned on test mode, and also disabled driver signing moreover it working in my laptop what can be the problem ?

**Comment by Timboy67678** [comment]
This is the wrong project, you should make an issue here: https://github.com/DarthTon/Xenos
Also try adding the error code

**Comment by DarthTon** [comment]
Can you post the log?

**Comment by verysimplenick** [comment]
Check build version(if win 10 works only on 10586 build) and add error code

**Comment by DarthTon** [comment]
Any updates?
