### ISSUE TITLE
Dependency path resolves to wrong file, any ideas ?

### ISSUE THREAD

**Issue by MINIONBOTS** [DarthTon/Blackbone#78]
Hi, 
I have the weird issue, that, while injecting my dll, it randomly does not resolve the dependency to d3dx9.dll file. Never had any issues before, this just started recently...
Here is a screenshot of the logs:
- LEFT side a working injection run with extended logging.
- RIGHT side first a working injection and right after a 2nd try where it failed.
This is completely randomly happening...

![index](https://cloud.githubusercontent.com/assets/2842405/14703018/e5b9c094-07ad-11e6-818d-9917ed1c4fd9.png)

Do you have any ideas what this could be or why it is happening ? I know I'm not alone with this issue, but I was never able to trace it down before.

**Comment by DarthTon** [comment]
In the failing case i don't see d3d9.dll being loading. It seems it's already present in a process and it fails to find export properly. Can you check whether dll is correct and has export in such case?

**Comment by MINIONBOTS** [comment]
I'm injecting into a game, which by default loads/uses the d3d9.dll. 
I don't understand what you mean with "Can you check whether dll is correct and has export in such case?", could you please explain it differently ?

**Comment by DarthTon** [comment]
Can you dump d3d9.dll used by the game and send it to me?

**Comment by MINIONBOTS** [comment]
The game does not have a seperate d3d9.dll, afaik it uses the one from my Windows System folder. 
Here is the dump:
[d3d9.dll_6FDA0000.zip](https://github.com/DarthTon/Blackbone/files/229774/d3d9.dll_6FDA0000.zip)

**Comment by MINIONBOTS** [comment]
Seems that without my dll, there is only the d3d9.dll in the target process, the moment I inject, the d3dx9_43.dll is loaded as well, I guess I'm using a function which is not in d3d9.dll

**Comment by DarthTon** [comment]
Hm. Can you then check if older version is indeed free of this bug? I don't recall pushing any export related commit in last few month but could be anything. Are you able to debug this issue? Because I can't seem to reproduce it myself and teamviewer session will help.

**Comment by MINIONBOTS** [comment]
Exactly, it could be anything :/ I have a hard time reproducing it right now, happens once every 20 attempts...So it must be a timing issue I assume, I'll test a bit more with/without starting the target process in debug mode.

**Comment by MINIONBOTS** [comment]
I tested it some more and solved my issue. The problem never existed before, but something in your recent commits maybe happened to change the time it takes to attach or I don't know :D 
Long story short, I had the target process started by my dll in debug mode to patch a few things, then resumed the target process, called EnsureInit() and then injected right after. I noticed that when I manually attach to an already fully started target process, it did work fine. So I had to add a (silly but working) Sleep() before calling EnsureInit() , then it all started to work fine again. I would assume that some imports were not yet done by the target process when injecting so fast, and therefore the weird error happened, sadly I have no further information regarding the exact cause of the problem. 
Thanks :)

**Comment by MINIONBOTS** [comment]
One little update on this, I had to REMOVE the EnsureInit() ,then it magically started to work....but I don't unerstand why :D 
Anyway, as others mentioned already, if you have a Donate button somewhere, I would be happy to donate you some beer ;)
