### ISSUE TITLE
Xenos ? BlackBone Manual Mapping Error?

### ISSUE THREAD

**Issue by kainpark7894** [DarthTon/Blackbone#79]
User Manual Mapping & Kernel Manual Mapping

Test OS:windows 7 x64 ultimate

32bit & 64bit dll File Manual Mapping No option Injection

But 10~20 Time -> ManualMapping dll Thread Dead

Extreme Injector ManualMapping dll Thread no dead

test.dll file cmd.exe <-- manual mapping injection!

[test.zip](https://github.com/DarthTon/Blackbone/files/233368/test.zip)

**Comment by DarthTon** [comment]
So what's the actual issue? It doesn't inject or what?

**Comment by kainpark7894** [comment]
manual mapping dll injection The resulting thread dies within 10~20 seconds

**Comment by DarthTon** [comment]
Thread must die, injector leaves no traces after job is done.

**Comment by kainpark7894** [comment]
no injector form dead video
https://youtu.be/6eTlFOq2BcE

**Comment by DarthTon** [comment]
It's a bug in your dll. You do not return from DllMain. Create new thread and start your from it.
