### ISSUE TITLE
Incorrect function arguments on return hook

### ISSUE THREAD

**Issue by k-sky** [DarthTon/Blackbone#86]
Congratulations for the great work.

I noticed an issue with the function arguments on return hooks. The arguments are correct in the function call (regular hook) but they are invalid/incorrect in the return hook.

I hook a function like this:

    bool IsValidPath(std::string* path);

In the regular hook I can read the string value successfully, but in the return hook of the same call, the argument (`context.getArg(0)`) is not the same address as the first one. It looks like garbage instead. I confirmed that the function does not alter the argument during its execution.

**Comment by DarthTon** [comment]
Entry and Return hook contexts are equal now.
