### ISSUE TITLE
Calling a remote function inside a hook callback hangs both processes

### ISSUE THREAD

**Issue by k-sky** [DarthTon/Blackbone#87]
Maybe it's not an issue but a characteristic of BlackBone's architecture.

I call a remote function inside the callback of a remote hook. The caller and target processes hang. By my limited knowledge I suppose it's because the remote worker thread is busy waiting for the return of the callback, so when I try to call a remote function it cannot be executed until the callback returns. I can't execute it in other threads because they're all paused (because of the hook bp?), and I guess that it would still need the worker thread.

Is there any way I can call a remote function inside the hook callback? Unfortunately I can't see any other way to do what I need other than calling the function inside the hook callback.

**Comment by DarthTon** [comment]
It's because remote hooking works through native debugger. Breakpoints work through debug events. And when debug event is being handled process is suspended entirely. To make it work, entire remote hooking mechanism should be reworked.

**Comment by k-sky** [comment]
So, there's no way to call a remote function inside the callback?

**Comment by k-sky** [comment]
There's no way. I will have to hook locally. Thank you.
