### ISSUE TITLE
Remote Hook Function

### ISSUE THREAD

**Issue by AnnaSokolovaAnna** [DarthTon/Blackbone#97]
Здравствуйте!
Имеется ли возможность установить хук на функцию(не WinAPI) в удаленном процессе?

например я знаю адресс нужной мне функции и внутри процесса(посредством длл) с помощью Detour  свободно устанавливаю перехват

```C++
typedef BOOL(__stdcall FunctionFn)(unsigned int, int);
FunctionFn pFunction = nullptr;

int __stdcall hkFunction(unsigned int a1, int a2)
{
 //......
 return pFunction(a1, a2);
}

pFunction = (FunctionFn)xDetour((PBYTE)dAdress, `(PBYTE)hkFunction);```


/*--------------*/
Hello!
Is there a way to set the hook to a function(not WinAPI) in the remote process?
for example, I know the address I need and functions within the process(via a DLL) by using the Detour freely set the interception

**Comment by DarthTon** [comment]
Yes. Look at Detour class in Localhook.hpp. There are some examples in LocalHookTest.cpp.

**Comment by AnnaSokolovaAnna** [comment]
Большое спасибо.
Общая логика мне понятна, но не могли бы вы облегчить мне немного жизнь и привести небольшой пример основываясь на коде из первого поста?

/*--------------*/
Thank you very much.
The General logic is clear to me, but could you lighten me a bit of life and lead a small example based on the code from the first post?

**Comment by DarthTon** [comment]
```C++
typedef BOOL( __stdcall* FunctionFn )(unsigned int, int);

int __stdcall hkFunction( unsigned int& a1, int& a2 )
{
    //......
    return 0;
}

int main( )
{
   blackbone::Detour<FunctionFn> detour;
    detour.Hook( (FunctionFn)dAdress, &hkFunction, blackbone::HookType::Inline, blackbone::CallOrder::HookLast );
}
```

**Comment by AnnaSokolovaAnna** [comment]
Спасибо.
Видимо я не правильно выразилась или не совсем понимаю.
Задача: поставить хук в чужом процессе.

Пример: Имеется моя консоль(MyConsole.exe), нужно из этого приложения установить хук в чужом процессе(Target.exe), зная адрес и прототип нужной функции(не WinAPI).

/*------------------*/
Thank you.
Apparently I misspoke or don't understand.
Objective: set the hook in another process.

Example: There is my console(MyConsole.exe), you need this application to set the hook in another process(Target.exe), knowing the address and the prototype of the desired functionality(not WinAPI).

**Comment by DarthTon** [comment]
Ah, I see.
```C++
void hkFunction( RemoteContext& ctx )
{
    unsigned int a1 = ctx.getArg( 0 );
    int a2 = ctx.getArg( 1 );
    //......
}

int main( )
{
    Process proc;
    std::vector<DWORD> pids;
    Process::EnumByName( L"Target.exe", pids );
    proc.Attach( pids.front() );
    proc.hooks().Apply( RemoteHook::hwbp, dAdress, hkFunction );
}
```

**Comment by AnnaSokolovaAnna** [comment]
`error C2664: "NTSTATUS blackbone::RemoteHook::Apply(blackbone::RemoteHook::eHookType,uint64_t,blackbone::RemoteHook::fnCallback,blackbone::Thread *)": невозможно преобразовать аргумент 3 из "int (__cdecl *)(blackbone::RemoteContext &)" в "blackbone::RemoteHook::fnCallback"`



```C++
using namespace blackbone;

int hkFunction(RemoteContext& ctx)
{
		unsigned int a1 = ctx.getArg(0);
		int a2 = ctx.getArg(1);
		//return (a1 + a2 + 8);
}

int main()
{
	
	Process proc;
	std::vector<DWORD> pids;
	Process::EnumByName(L"Target.exe", pids);
	proc.Attach(pids.front());
	proc.hooks().Apply(RemoteHook::hwbp, 0xC11040, hkFunction);

	getch();
	return 0;
}
```

**Comment by Velixium** [comment]
Try this
`proc.hooks().Apply(RemoteHook::hwbp, (uint64_t)0xC11040, hkFunction);`

**Comment by DarthTon** [comment]
```void hkFunction( RemoteContext& ctx )```

**Comment by LiLejia** [comment]
Hi, guys, I tried to 

``` C
void original_call() {
    std::cout << "Original call" << std::endl;
    Sleep(1000);
}

int main()
{
    // find the original_call address
    std::cout << "Origial call address: " << original_call << std::endl;
    system("pause");
    for (;;) {
        original_call();
    }
}
```

Obove is the process code I wan't to hook, I run the process and print the function address out and use this address to hook this function.  
The hook status is `0`, which means ok, but I don't get the callback.

``` C
void hkFunction(RemoteContext& ctx){
   std::wcout << L"My hooked function\n";
}
int main(){
    // ...

    // 0x0045AA91 is the address printed above;
    NTSTATUS status = target.hooks().Apply(RemoteHook::hwbp, 0x0045AA91, hkFunction);
    // the status is zero, which means ok, but I don't get the callback.
}
```

However, if I use same address above to make a remote call function, it works, which means the address is correct.

``` C

auto print_original_function = MakeRemoteFunction<void(__stdcall*)(void)>(target, 0x0045AA91);
auto result = print_original_function.Call({});
// print "Original call" in the original process.

```

Do I run into some CFG walls?
