### ISSUE TITLE
ManualMap 64bit crashes with std::thread used

### ISSUE THREAD

**Issue by MINIONBOTS** [DarthTon/Blackbone#98]
Hey, after wasting nearly 1,5 days to narrow down the reason why manual mapping my dll in x64 crashes instantly before DLL_PROCESS_ATTACH was being called, I am now looking at an EMPTY project which crashes the moment I have a single line defined that uses std::thread in a .cpp file which is not even used anywhere. 

It works all fine in 32bit manual mapping, it also works fine with native injection method even in 64bit. 
It just instantly crashes with 64bit and manual mapping. 

I cannot explain why it happens, but maybe you can.

[Win32Project1.zip](https://github.com/DarthTon/Blackbone/files/424383/Win32Project1.zip)

Edit: Fun fact, I took out all std::thread calls from my main project, but libraries which the project uses still have the same std::thread implemented, it still works in x64 manual mapping... weird

**Comment by MINIONBOTS** [comment]
I played a bit more with my project in x64 now that I can inject, it looks like exception handling is not working (it works fine in 32bit for my code), any kind of exception instantly crashes it.

**Comment by DarthTon** [comment]
Exception handling is fine, sort of. Problems begin with CRT static linkage - /MT. Some CRT functions use  RtlPcToFileHeader to get mapped image base. That function walks InvertedFunctionTable which is empty because Dynamic exception table is used instead.
I've implemented InvertedFunctionTable support for x64 (Win10 only for now) in c39fc6057a86497f1a5519c1d0fc3bdb0754e38b.

**Comment by MINIONBOTS** [comment]
Thank you for the quick response, I'll try to compile it with /MD and see if that helps :)

**Comment by DarthTon** [comment]
> I'll try to compile it with /MD and see if that helps :) 
It should work with /MT too after that commit.

> Btw. do you have a "donate button" somewhere ? 
No. No yet at least :)

**Comment by MINIONBOTS** [comment]
Maybe check if https://www.patreon.com/ is something for you, you can put the link on the frontpage of you repo. I would subscribe then on a monthly basis ;) 

Thanks again for the super quick response and solution!
